### ISSUE TITLE
请问：72B模型量化后，和7B/14B模型对比，效果怎么样呢？

### ISSUE THREAD

**Issue by ybdesire** [QwenLM/Qwen1.5#10]
请教一下：和不量化的7B/14B模型对比，72B模型量化后，效果怎么样呢？是量化的72B会差很多，还是完全没有可比性呢？

**Comment by hwb96** [comment]
同问

**Comment by JustinLin610** [comment]
check qwen1 you can get some results. for qwen1.5 we didn't provide this. we internally evaluate the quantized models on benchmark datasets such as mmlu, ceval, gsm8k, humaneval. quantized models only suffer a very small margin of performance drop, so you can just believe that it is always worthy to use a larger model no matter it is quantized or not. we usually applied gptq and awq by performing calibration on our own alignment datasets.

**Comment by hwb96** [comment]
感谢您的回复。进行 gptq 量化需要加载校准数据集，不同的校准数据对量化结果影响大吗？Qwen 使用的校准数据集未来是否有开源的打算？
