### ISSUE TITLE
有关sft代码的attention mask的问题

### ISSUE THREAD

**Issue by yzxyzh** [QwenLM/Qwen1.5#103]
通义团队的同学你们好！

我有个小问题。我看你们sft的代码的时候，你们的attention mask只覆盖了padding的token，并没有覆盖prompt中user和system的部分。请问这是刻意为之吗？因为根据我的历史经验，包括你们1.0的代码，一般微调的时候都是会mask掉user和system的部分的。是否全部计算loss会比只计算assistant的loss的方法获得更好的效果？

期待你们的回复！

**Comment by 128Ghe980** [comment]
> 通义团队的同学你们好！
> 
> 我有个小问题。我看你们sft的代码的时候，你们的attention mask只覆盖了padding的token，并没有覆盖prompt中user和system的部分。请问这是刻意为之吗？因为根据我的历史经验，包括你们1.0的代码，一般微调的时候都是会mask掉user和system的部分的。是否全部计算loss会比只计算assistant的loss的方法获得更好的效果？
> 
> 期待你们的回复！

老哥你代码是直接进transformer包里看的吗？我看他们的例子里直接trainer就完事儿了，没看见细节

**Comment by WangJianQ-cmd** [comment]
请问Qwen1.5的微调方法，除了替换Qwen1.5给出的那几个文件，其他的都复用Qwen的吗

**Comment by qinxithu** [comment]
我也想知道， 这是训练base模型的代码吧， 好像训练chat模型要把user和system的mask掉？

**Comment by sunyclj** [comment]
> 我试了在预处理数据时候，把system和user prompt target id位置都置IGNORE_TOKEN_ID，loss曲线就小多了，并且最后推理的结果也是reasonable的

请问只是处理target_ids就可以了是吗？input_ids是不是不用处理？

**Comment by jklj077** [comment]
Please also see:
- https://github.com/QwenLM/Qwen1.5/issues/222
- https://github.com/QwenLM/Qwen1.5/issues/229
- https://github.com/QwenLM/Qwen1.5/issues/343

**Comment by HaoRenkk123** [comment]
我也有个疑问，我看很多训练框架sft部分的代码，在数据处理部分，只计算出了input_ids和labels，传入Trainer即可，attention_mask是在transformers的对应model 的forward里边计算出来吗，不需要在数据处理部分计算出来传入？
