### ISSUE TITLE
qwen和qwen1.5的vocab的问题

### ISSUE THREAD

**Issue by Yuhuajoe** [QwenLM/Qwen1.5#107]
在qwen中vocab中是字节，例如第81705个token是b'\xe6\xb5\x8b\xe8\xaf\x95'　utf-8对应为　测试　这个词；但是在qwen1.5中第81705个token是'æµĭè¯ķ'，并且decode出来也是 测试 这个词，请问这是什么原因

**Comment by jklj077** [comment]
The `Qwen2Tokenizer` follows the established practice within the `transformers` library, where tokens are consistently represented as strings (type `str`). To achieve this, it follows the approach taken by GPT-2 and related models. The tokenizer employs a byte-to-unicode encoder (`tokenizer.byte_encoder`) to transform each individual byte into a corresponding unicode code point. During the decoding process, there is a reciprocal step where a unicode-to-byte decoder is utilized to revert these transformations. Finally, the decoded byte sequences are then properly interpreted back into their original form using UTF-8 encoding.

`Qwen2Tokenizer`为了与`transformers`库的实践保持一致，确保token均以字符串类型(`str`)表示，在编码过程中采用了类似于GPT-2及其相关代码的方法。该tokenizer使用一个byte到Unicode编码器(`tokenizer.byte_encoder`)将每个单独的byte转换为特定的Unicode码点。在解码过程中，会有一个对应的逆向操作步骤，即利用Unicode到byte解码器进行转化还原。最后，对解码得到的字节序列采用UTF-8编码方式进行正确解读，还原其原始形式。
