### ISSUE TITLE
vllm return only 2word for long prompt

### ISSUE THREAD

**Issue by sparkfax** [QwenLM/Qwen1.5#109]
### long prompt only output word:   text='。'.  

//same prompt is output normal, if use AutoModelForCausalLM version
model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen1.5-4B-Chat",
    torch_dtype=torch.float16,
    device_map="auto"
)

//vllm code below output incorrect
import torch
from vllm import LLM
llm = LLM(model="Qwen/Qwen1.5-4B-Chat",tensor_parallel_size=2, quantization=None,max_model_len=10288,enforce_eager=True,dtype=torch.float16,download_dir="/kaggle/temp/",)  

prompts='摘取以下内容中，叶文杰的行为，态度和观点。 以下内容：第38章 雷志成、杨卫宁之死    审问者：姓名？    叶文洁：叶文洁。    审问者：出生日期？    叶文洁：1947年6月。    审问者：职业？    叶文洁：清华大学物理系天体物理专业教授，2004年退休。    审问者：鉴于你的身体情况，谈话过程中你可以要求暂停休息。    叶文洁：谢谢，不用。    审问者：我们今天进行的是普通刑事案件的调查，不涉及更高层次的内容，这不是本次调查的主要部分，我们希望快些结束，希望你能配合。    叶文洁：我知道你指的是什么，我会配合的。    审问者：调查发现，在红岸基地工作期间，你有杀人嫌疑。    叶文洁：我杀死过两个人。    审问者：时间？    叶文洁：1979年10月21日下午。    审问者：受害者的姓名？    叶文洁：基地政委雷志成和基地工程师、我的丈夫杨卫宁。    审问者：讲述一下你作案的动机。    叶文洁：我……是不是能假设你对当时相关的背景有所了解？    审问者：基本了解，不清楚的我会提问。    叶文洁：好的。在接收到外星信息并回信后的当天，我得知收到该信息的不止我一个人，雷志成也收到了。雷政委是那个年代典型的政治干部，政治神经很敏感，用当时的话说，就是阶级斗争这根弦绷得很紧。他背着红岸基地的大部分技术人员，在主计算机中长期后台运行着一个小程序，这个程序不断读取发射和接收的信息缓冲区，并将读到的内容存贮在一个隐藏很深的加密文件中，这样，红岸系统发射出去和接收到的信息就有了一个只有他能读取的备份，正是从这个备份中，他发现了红岸接收到的外星文明信息。在我向初升的太阳发出回答信息的当天下午，也就是我从医务室中刚得知自己怀孕后，雷志成把我叫到他的办公室。我看到，他办公桌上的终端屏幕上赫然显示着昨夜收到的来自三体世界的信息……    “从接收到第一批信息到现在，已经过去了八个多小时，你没有报告，反而将原始信息删除或隐藏起来了，是吗？”    我低着头没有回答。    “你下一步的企图我也清楚，你打算回电。如果不是我发现得及时，整个人类文明都将毁在你手中！当然，这不是说我们惧怕来自宇宙的入侵，退一万步说，那种事真的发生了，外星侵略者必然会淹没于人民战争的汪洋大海之中！”    我现在明白了，他还不知道我已经发出了回电，我将回答信息放入发射缓冲区时，使用的不是常规文件接口，这无意中绕开了他的监视程序。    “叶文洁，你是会做出这种事的，对于党和人民，你一直怀有刻骨的仇恨，不会放过任何一个报复的机会。你知道这样做的后果吗？”    我当然知道，于是点点头，雷志成沉默片刻，下面的话却出乎我的预料。    “叶文洁，对于你，我是不会有任何恻隐之心的，你一直都是一个与人民为敌的阶级敌人。但我与杨卫宁是多年的战友，我不能看着他和你一同彻底毁掉，更不能看着他的孩子也跟着毁掉，你有孩子了，不是吗？”    他这话并非随便说说，如果事发，在那个年代，这样性质的问题，不管我丈夫与此事有无关系，都会受到很大牵连，当然还有未出世的孩子。    雷志成压低了声音说：“目前，这件事情还只有我们俩知道，现在要做的，就是把这件事情的影响降到最小。你什么都不要管，就当这件事没有发生，不要向任何人提起，包括杨卫宁，剩下的事情，就由我来处理吧。小叶啊，请相信我，只要你配合，就能避免可怕的后果。”    我立刻明白了雷志成的用心：他想成为第一个发现外星文明的人，这确实是一个名垂青史的绝好机会。\n\n我答应了他，然后离开了办公室，这时我已经在心里决定了一切。    我拿了一只小扳手，走进了接收系统前端处理模块的设备间，打开主机柜，将最下方的接地线的螺栓小心地拧松了，由于我时常需要检查设备，所以谁也没有注意到我干了什么。这时，接地电阻由0.6欧姆一下子上升到5欧姆，接收系统的干扰骤然增大。    值班技术员立刻就知道是接地线故障，因为这种故障以前多次发生，判断起来很容易，但他不会想到是接地线顶端的故障，因为那里固结很好，一般没人动，况且我刚说过顺便看过了。雷达峰的顶部是一种很不寻常的地质结构，覆盖着一层十几米厚的胶泥，这种胶泥层导电性很差，接地线埋下后，接地电阻总是达不到要求；把接地电极深埋也不行，因为这种胶泥层对导线有很强的腐蚀作用，时间长了可能从中部将接地线蚀断。最后，只好将接地线排从那道悬崖上垂下去，沿着崖壁一直垂到没有胶泥层的地方，将接地电极埋设在崖壁上的那个位置。即使这样，接地仍然不稳定，电阻常常超标，问题都是出在接地线位于悬崖壁上的部分，这时维修人员就要用绳索吊下去修。那名技术员就向外围维修班打招呼，班里的一名战士在一根铁柱上系好绳索就顺着崖壁下去了，在下面折腾了半个多小时，满头大汗地上来，说找不到故障。这次监听作业眼看就要受到影响，只好上报基地指挥部。我就在悬崖顶上那个系绳索的铁柱旁等着，事情果然如我预料，雷志成跟着那名战士来了。    应该说，雷志成是一名很敬业的政工干部，忠实地按照那时对他们的要求去做：与群众打成一片，时时站在第一线。也许是为了做姿态，但他确实做得很好，基地急难险重的工作中，都少不了他的身影，而以往他干得最多的，就是抢修接地线这个既危险又累的活儿。这工作虽然没有多高的技术含量，但需要经验，因为故障可能是因接地线暴露在露天产生的难以察觉的接触不良，也可能是因为接地电极埋设处因干燥等原因导致的导电性差，现在负责外围维修的这批志愿兵刚刚调换过，都没有经验，所以我估计他多半要来。他系好安全带，就顺着绳索下去了，好像我不存在似的。我借口把那名战士支走了，悬崖顶上只剩下我一人，然后我从衣袋中掏出了一件东西，那是一叠短钢锯，是一条长锯条折成三段后叠在一起的，这样绳索的断口看不出是锯断的。    正在这时，我丈夫杨卫宁来了。    问清事情的缘由后，他向悬崖下看了看，说要是检查接地电极的话需要开挖，老雷一个人在下面太费劲，他要下去帮忙，于是就系上了那名战士留下的安全带。我说再拿一条绳索吧，他说不用，这条绳子就挺粗挺结实，承带两个人没问题。我坚持要拿，他说那你去吧。等我急跑着取回另一条绳索回到悬崖顶时，他早顺着那条绳索下去了。我探头向下看，见他和雷志成已经检查完毕，正沿着同一条绳索向上爬，雷志成在前。    真的不会再有机会了，我掏出那叠钢锯，锯断了绳索。    审问者：我问一句，回答不记录。你当时的感受？    叶文洁：冷静、毫不动感情地做了。我找到了能够为之献身的事业，付出的代价，不管是自己的还是别人的，都不在乎。同时我也知道，全人类都将为这个事业付出史无前例的巨大牺牲，这仅仅是一个微不足道的开始。    审问者：好的，继续吧。    叶文洁：我听到两三声短促的惊叫，然后是身体摔到崖底乱石上的声音，等了一会儿，我看到从崖底流出的那条小溪变红了……关于这件事，我能说的就这些了。    审问者：好的，这是记录，请你仔细看看，准确无误的话，请在这儿签字'
outputs = llm.generate(prompts)  # Generate texts from the prompts.
print(outputs)

 outputs=[CompletionOutput(index=0, text='。', token_ids=[1773, 151645], cumulative_logprob=-0.3745987694710493, logprobs=None, finish_reason=stop)], finished=True, metrics=RequestMetrics(arrival_time=1521.532966993, last_token_time=1521.532966993, first_scheduled_time=1709279097.677883, first_token_time=1709279098.2628815, time_in_queue=1709277576.1449158, finished_time=1709279098.3491971), lora_request=None)]

**Comment by jklj077** [comment]
`llm.generate` does not apply the chat template, which means the model conducts text completion, thus the result. Try using the vLLM OpenAI API, or apply the chat template yourself.
