### ISSUE TITLE
GPTQ-int4 vllm部署出错

### ISSUE THREAD

**Issue by su-zelong** [QwenLM/Qwen1.5#110]
ValueError : the model's max seq len (32768) is larger than the maxinum number of tokens that can be stored in KV cache, Try increasing 'gpu_memory_utilization' or decreasing 'max_model_len' when initializing the engine

**Comment by menkeyi001** [comment]
我也遇到这个问题  这个模型 不行 Qwen1.5-72B-Chat-GPTQ-Int4  这个可以vllm跑  Qwen1.5-7B-Chat-GPTQ-Int4  。我8个 A100 80G   1T内存     Qwen1.5-72B-Chat-GPTQ-Int4居然资源出错

**Comment by MrRace** [comment]
Qwen1.5-0.5B-Chat-GPTQ-Int4、Qwen1.5-0.5B-Chat-GPTQ-Int8、Qwen1.5-0.5B-Chat-GPTQ-Int8 这3个模型用vllm部署后，请求都报错了。只有Qwen1.5-0.5B-Chat-AWQ和Qwen1.5-0.5B-Chat可以正常返回。
报错内容都是：
```
ransformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'
```

**Comment by chongqingwei** [comment]
vllm 部署qwen1.5的量化版本，会出错，有没有官方基于qwen1.5的gptq的代码？

**Comment by ticoAg** [comment]
```sh
export VLLM_USE_MODELSCOPE=True

python -m vllm.entrypoints.openai.api_server \
    --model qwen/Qwen1.5-72B-Chat-GPTQ-Int4 \
    --served-model-name Qwen1.5-72B-Chat-Int4
```

使用Qwen1.5-72B-Chat-Int4调用就可以了

**Comment by zhanpengjie** [comment]
改下vllm参数，模型输入32K太大了，可以改小点
--tensor-parallel-size 2  
--max-model-len 8192 
还有些别的参数都可以试下

**Comment by su-zelong** [comment]
> 改下vllm参数，模型输入32K太大了，可以改小点 --tensor-parallel-size 2 --max-model-len 8192 还有些别的参数都可以试下

这样虽然能部署成功，但是这样的接口只能响应 < max-model-len 的请求，这样不是限制了上下文长度吗

**Comment by su-zelong** [comment]
> 改下vllm参数，模型输入32K太大了，可以改小点 --tensor-parallel-size 2 --max-model-len 8192 还有些别的参数都可以试下

--tensor-parallel-size我理解是将服务部署在多卡，这种方式我试过但是它直接闪退

**Comment by su-zelong** [comment]
> ```shell
> export VLLM_USE_MODELSCOPE=True
> 
> python -m vllm.entrypoints.openai.api_server \
>     --model qwen/Qwen1.5-72B-Chat-GPTQ-Int4 \
>     --served-model-name Qwen1.5-72B-Chat-Int4
> ```
> 
> 使用Qwen1.5-72B-Chat-Int4调用就可以了

不论是官方量化版本还是我自己的量化版本错误类型一样

**Comment by ticoAg** [comment]
问题不就是

> > 改下vllm参数，模型输入32K太大了，可以改小点 --tensor-parallel-size 2 --max-model-len 8192 还有些别的参数都可以试下
> 
> 这样虽然能部署成功，但是这样的接口只能响应 < max-model-len 的请求，这样不是限制了上下文长度吗

问题不是现在显存不足以支持32k上下文的推理么......要不先了解一下vllm？

**Comment by zhanpengjie** [comment]
> > 改下vllm参数，模型输入32K太大了，可以改小点 --tensor-parallel-size 2 --max-model-len 8192 还有些别的参数都可以试下
> 
> 
> 
> --tensor-parallel-size我理解是将服务部署在多卡，这种方式我试过但是它直接闪退

建议看下vllm文档，一般都是参数设置的问题
