### ISSUE TITLE
vllm inference problem after llama-factory lora sft on qwen1.5-14B-Chat

### ISSUE THREAD

**Issue by lebronjamesking** [QwenLM/Qwen1.5#112]
Hi there,

Does anyone know that vllm inference on a lora sft adapter abnormal, but original model.generate like inference is alright. Puts it simple, vllm inference generate unexpected words after llama-factory lora sft, but orignial transformer based model.generate() is ok. Please anyone have any idea or shall I use finetune_sft_ds.sh from Qwen1?

Many thanks!

**Comment by hiyouga** [comment]
Which template did you use when fine-tuning the model with llama-factory?

**Comment by lebronjamesking** [comment]
> Which template did you use when fine-tuning the model with llama-factory?

Hi I think I use qwen as the template.

**Comment by hiyouga** [comment]
1. Did you apply the correct chat template to model.generate()?
2. Check if vllm used the same chat template to infer the fine-tuned model

**Comment by lebronjamesking** [comment]
BTW, the train shell looks like this:
CUDA_VISIBLE_DEVICES=0,1 accelerate launch src/train_bash.py \
    --stage sft \
    --do_train \
    --model_name_or_path /root/Qwen1.5-14B-Chat \
    --dataset data1 \
    --template qwen \
    --finetuning_type lora \
    --lora_target q_proj,k_proj,v_proj,o_proj,gate_proj,down_proj,up_proj \
    --output_dir qwen1.5-14b \
    --overwrite_output_dir True \
    --overwrite_cache \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type constant \
    --logging_steps 10 \
    --save_steps 10 \
    --learning_rate 2e-4 \
    --num_train_epochs 20 \
    --plot_loss yes \
    --cutoff_len 6000 \
    --bf16

**Comment by lebronjamesking** [comment]
> 1. Did you apply the correct chat template to model.generate()?
> 2. Check if vllm used the same chat template to infer the fine-tuned model

Many thanks, let me check it now

**Comment by lebronjamesking** [comment]
I think the problem of inference is solved by enforcing qwen_template.jinja. However, I am still suffering from the vllm inference speed. On a A100 80G GPU, the inference speed is very slow. Any clue please?

Here is the code to launch a server.
```
python -m vllm.entrypoints.openai.api_server \
--model ckpt_path \
--trust-remote-code \
--host localhost  \
--port 80 \
--gpu-memory-utilization 0.95 \
--enforce-eager \
--max-model-len 2048 \
--chat-template ./qwen-template.jinja \
--tensor-parallel-size 1 \
--served-model-name qwen-chat
```

And here is the code to infer the result
```
def chat_with_me(content:str):
    msg=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": content},
        ]
    chat_response = client.chat.completions.create(
        model="qwen-chat",
        messages=msg
    )
    
    response=chat_response.choices[0].message.content
    return response
```

**Comment by wxqyyds** [comment]
Why my llama_factory dont have qwen template

**Comment by hiyouga** [comment]
@wxqyyds update your code

**Comment by lebronjamesking** [comment]
Hi, the problem of slow inference speed is resolved by limiting max_tokens to be something 500 other than the default 6000.

The updated inference code snippet is something like the following:

```
call_args = {
        'temperature': 0.8,
        'top_p': 0.95,
        'top_k': 10,
        'presence_penalty': 1.0,
        'frequency_penalty': 0.0,
        'repetition_penalty':1.0,
        'max_tokens':500,
        "stream":False
    }

def chat_with_me(content:str):
    msg=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": content},
        ]
    chat_response = client.chat.completions.create(
        model="qwen-chat",
        messages=msg,
        extra_body=call_args
    )
    
    response=chat_response.choices[0].message.content
    return response
```

> I think the problem of inference is solved by enforcing qwen_template.jinja. However, I am still suffering from the vllm inference speed. On a A100 80G GPU, the inference speed is very slow. Any clue please?
> 
> The version of relvant packages:
> 
> **vllm 0.3.3 transformers 4.38.2 openai 1.13.3**
> 
> Here is the code to launch a server.
> 
> ```
> python -m vllm.entrypoints.openai.api_server \
> --model ckpt_path \
> --trust-remote-code \
> --host localhost  \
> --port 80 \
> --gpu-memory-utilization 0.95 \
> --enforce-eager \
> --max-model-len 2048 \
> --chat-template ./qwen-template.jinja \
> --tensor-parallel-size 1 \
> --served-model-name qwen-chat
> ```
> 
> And here is the code to infer the result
> 
> ```
> def chat_with_me(content:str):
>     msg=[
>             {"role": "system", "content": "You are a helpful assistant."},
>             {"role": "user", "content": content},
>         ]
>     chat_response = client.chat.completions.create(
>         model="qwen-chat",
>         messages=msg
>     )
>     
>     response=chat_response.choices[0].message.content
>     return response
> ```

**Comment by lebronjamesking** [comment]
Pls feel free to the close the ticket or I will close it now.
