### ISSUE TITLE
azureml parameters 超出 200 到达207， 用llama factory 跑微调的时候

### ISSUE THREAD

**Issue by beihaiarbitration** [QwenLM/Qwen1.5#113]
INVALID_PARAMETER_VALUE: Response: {'Error': {'Code': 'ValidationError', 'Severity': None, 'Message': 'A field of the entity is over the size limit. FieldName=Parameters, Limit=200, Size=207. See https://aka.ms/azure-machine-learning-limits for service limits documentation.', 'MessageFormat': None, 'MessageParameters': None, 'ReferenceCode': None, 'DetailsUri': None, 'Target': None, 'Details': [], 'InnerError': None, 'DebugInfo': None, 'AdditionalInfo': None}, 'Correlation': {'operation': 'dc81c66a2be484df8773274efc3d4831', 'request': '7a37d21ceed4f9c3'}, 'Environment': 'centralus', 'Location': 'centralus', 'Time': '2024-03-02T18:15:19.9925416+00:00', 'ComponentName': 'mlflow', 'statusCode': 400, 'error_code': 'INVALID_PARAMETER_VALUE'}

**Comment by beihaiarbitration** [comment]
azureml parameters 超出 200 到达207， 用llama factory 跑微调的时候， 其他的模型都可以跑除了qwen不知道为什么

**Comment by jklj077** [comment]
Unfortunately, this limitation is imposed by AzureML, which leverages `mlflow` to integrate with the `transformers`-related library and it seems the run has exceeded its 200 parameter support limit.

这一限制是由AzureML强加的，它使用`mlflow`与`transformers`生态进行集成，此次运行超出了其对200个参数的支持上限。

Given that the actual parameters are constructed by LLaMA-Factory and transformers, and the restriction is enforced by AzureML, it's not feasible for us to address this issue directly. 

由于实际参数由LLaMA-Factory和transformers构建，且该限制由AzureML实施，我们无法从自身端解决这个问题。

Please refer to <https://github.com/huggingface/transformers/issues/18870#issuecomment-1254321622>, where a workaround using a custom callback has been proposed. However, please note that this information is provided only for reference purposes, and we have not tested the viability of this workaround, and indeed, it is quite outdated.

您可以参考<https://github.com/huggingface/transformers/issues/18870#issuecomment-1254321622>中提出的使用自定义回调函数的解决方案。但请注意，这只是供参考的信息，我们尚未测试这个解决方案的可行性，这个方案有可能已经过时了。
