### ISSUE TITLE
    raise ValueError("No available memory for the cache blocks. " ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.

### ISSUE THREAD

**Issue by DAAworld** [QwenLM/Qwen1.5#12]
python -m vllm.entrypoints.openai.api_server --model data/Qwen1.5-14B-Chat --host 0.0.0.0 --port 30005 --dtype half --gpu-memory-utilization 0.95

![image](https://github.com/QwenLM/Qwen1.5/assets/46104689/6a0b2003-36c8-4c4f-9495-c89b52ef625f)

报这个错是什么原因，用的是32GB显存V100

**Comment by JustinLin610** [comment]
Level up the --gpu-memory-utilization . vllm works differently as it will take a lot of memory of the device

**Comment by sparkfax** [comment]
> Level up the --gpu-memory-utilization . vllm works differently as it will take a lot of memory of the device
already use --gpu-memory-utilization 0.95, how to level up?
