### ISSUE TITLE
After deploying VLLM, requests are throwing an error: "argument 'tokens': 'NoneType' object cannot be converted to 'PyString'."

### ISSUE THREAD

**Issue by MrRace** [QwenLM/Qwen1.5#122]
After deploying the Qwen1.5-0.5B-Chat-GPTQ-Int4, Qwen1.5-0.5B-Chat-GPTQ-Int8, and Qwen1.5-0.5B-Chat-GPTQ-Int8 models using VLLM, all requests are throwing errors. Only the Qwen1.5-0.5B-Chat-AWQ and Qwen1.5-0.5B-Chat models are returning successfully.

The error message for all the failing requests is:

```
File "transformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'
```

**Comment by fyabc** [comment]
@MrRace current vLLM implementation of Qwen2 has a bug when `tie_word_embeddings is True` (Qwen1.5-0.5B models).
<https://github.com/vllm-project/vllm/pull/3344> fixed this bug, you can update your vLLM version and try again.
