### ISSUE TITLE
qwen1.5-template.jinja文件在哪里呀？格式是什么样的呀

### ISSUE THREAD

**Issue by xinzaifeixiang1992** [QwenLM/Qwen1.5#126]
I think the problem of inference is solved by enforcing qwen_template.jinja. However, I am still suffering from the vllm inference speed. On a A100 80G GPU, the inference speed is very slow. Any clue please?

The version of relvant packages:

**vllm 0.3.3
transformers 4.38.2
openai 1.13.3**

Here is the code to launch a server.
```
python -m vllm.entrypoints.openai.api_server \
--model ckpt_path \
--trust-remote-code \
--host localhost  \
--port 80 \
--gpu-memory-utilization 0.95 \
--enforce-eager \
--max-model-len 2048 \
--chat-template ./qwen-template.jinja \
--tensor-parallel-size 1 \
--served-model-name qwen-chat
```

And here is the code to infer the result
```
def chat_with_me(content:str):
    msg=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": content},
        ]
    chat_response = client.chat.completions.create(
        model="qwen-chat",
        messages=msg
    )
    
    response=chat_response.choices[0].message.content
    return response
```

_Originally posted by @lebronjamesking in https://github.com/QwenLM/Qwen1.5/issues/112#issuecomment-1974970716_

**Comment by lebronjamesking** [comment]
Pls use something like the following:

`{% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system\nYou are a helpful assistant<|im_end|>\n' }}{% endif %}{{'<|im_start|>' + message['role'] + '\n' + message['content']}}{% if (loop.last and add_generation_prompt) or not loop.last %}{{ '<|im_end|>' + '\n'}}{% endif %}{% endfor %}{% if add_generation_prompt and messages[-1]['role'] != 'assistant' %}{{ '<|im_start|>assistant\n' }}{% endif %}`

**Comment by jklj077** [comment]
see chat_template in tokenizer_config.json
