### ISSUE TITLE
ollama中的模型和huggingface的模型是否一致？

### ISSUE THREAD

**Issue by lyj555** [QwenLM/Qwen1.5#132]
1、huggingface中，Qwen/Qwen1.5-0.5B-Chat模型大小约1.2G；
2、通过ollama加载0.5B模型，模型文件仅有394M；

问题：
1）为何huggingface的模型大小和ollama差异这么大？
2）另外确认下，ollama中的qwen模型应该是对应的chat系列模型吧？

**Comment by jklj077** [comment]
1. ollama uses quantized checkpoints in GGUF format.
2. qwen-chat.

**Comment by lyj555** [comment]
thanks
