### ISSUE TITLE
What has been updated on modelscope for qwen1.5-72b-chat?  2024/03/07

### ISSUE THREAD

**Issue by uuuidada** [QwenLM/Qwen1.5#135]
Hi.
I saw the model files has been updated today.
Can you tell me what has been updated?
Thanks!

**Comment by JustinLin610** [comment]
We found some model repos' checkpoints in HF and MS not aligned and we fixed.

**Comment by xyfZzz** [comment]
> We found some model repos' checkpoints in HF and MS not aligned and we fixed.

Are the models of qwen1.5-72b-chat-awq in HF and MS aligned? Because I found that the qwen1.5-72b-chat-awq model in MS was not updated.

**Comment by xyfZzz** [comment]
> We found some model repos' checkpoints in HF and MS not aligned and we fixed.

@JustinLin610 Are the models of qwen1.5-72b-chat-awq in HF and MS aligned? Because I found that the qwen1.5-72b-chat-awq model in MS was not updated.
