### ISSUE TITLE
Qwen1.5-7B-base模型推理速度比Qwen1.5-7B-chat模型速度慢很多

### ISSUE THREAD

**Issue by waltonfuture** [QwenLM/Qwen1.5#140]
如题。我使用的huggingface格式的推理。请问是什么原因呢？

**Comment by endNone** [comment]
我也是，我感觉不是7b-base慢了，Qwen1.5-7B-chat变快了

**Comment by xyw7** [comment]
求教哪里有qwen1.5-base的推理脚本

**Comment by endNone** [comment]
我是用fastchat的

**Comment by JustinLin610** [comment]
They are of same code and same model arch. Check the generation length of them. For chat models, it will automatically stop with the generation of im_end token, so probably its generation length is much shorter
