### ISSUE TITLE
Could you please show an example of sft data like Qwen1 did?

### ISSUE THREAD

**Issue by HuXinjing** [QwenLM/Qwen1.5#156]
可以给一个sft的数据例子吗

**Comment by jklj077** [comment]
See here: https://qwen.readthedocs.io/zh-cn/latest/training/SFT/example.html

**Comment by HuXinjing** [comment]
thx, it seems as same as qwen1



---Original---
From: "Ren ***@***.***&gt;
Date: Thu, Mar 14, 2024 20:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QwenLM/Qwen1.5] Could you please show an example of sft datalike Qwen1 did? (Issue #156)




 
See here: https://qwen.readthedocs.io/zh-cn/latest/training/SFT/example.html

**Comment by jklj077** [comment]
The content is similar but the format is very different.

**Comment by HuXinjing** [comment]
> The content is similar but the format is very different.

[
  {
    "id": "identity_0",
    "conversations": [
      {
        "from": "user",
        "value": "你好"
      },
      {
        "from": "assistant",
        "value": "我是一个语言模型，我叫通义千问。"
      }
    ]
  }
]

I see it, for someone else to compare qwen1 and qwen1.5, I list them here. The top is format of qwen1 and the bottom is the format of qwen1.5.

{
    "type": "chatml",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "Tell me something about large language models."
        },
        {
            "role": "assistant",
            "content": "Large language models are a type of language model that is trained on a large corpus of text data. They are capable of generating human-like text and are used in a variety of natural language processing tasks..."
        }
    ],
    "source": "unknown"
}
