### ISSUE TITLE
vllm deploy failed

### ISSUE THREAD

**Issue by wxz1996** [QwenLM/Qwen1.5#16]
**deploy platform：**RTX3090-24G
**model：**Qwen1.5-7B-Chat-GPTQ-Int4
**bash:**
`CUDA_VISIBLE_DEVICES=7 python -m vllm.entrypoints.openai.api_server     --model qwen/Qwen1.5-7B-Chat-GPTQ-Int4     --served-model-name qwen/Qwen1.5-7B-Chat-GPTQ-Int4     --quantization gptq`

**error:**
`ValueError: The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (24320). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.`

**Comment by YingchaoX** [comment]
memory is not enough for kv cache.
add  `--max-model-len 24320` in your cmd

**Comment by coreyho** [comment]
2*A100

qwen-72b-chat可以启动

qwen1.5报错

ValueError: The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (4464). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.

**Comment by riverzhou** [comment]
显存不够，用 --max-model-len 控制最大上下文长度
