### ISSUE TITLE
请问：model_qwen.generate 可以在异步不阻塞下运行吗？

### ISSUE THREAD

**Issue by suxuanning** [QwenLM/Qwen1.5#160]
我用并发请求我的异步接口，其中model_qwen.generate也放在了异步方法内，但是还是阻塞了全部接口的响应，请问model_qwen.generate 可以在异步不阻塞下运行吗？
如果大量用户访问推理接口，会造成响应慢的情况，因为目前看generate方法是阻塞推理的

**Comment by JustinLin610** [comment]
we usually advise to use vllm to deploy your service. not sure if this can solve your problem.

**Comment by suxuanning** [comment]
多谢，已经使用vllm

**Comment by chuangzhidan** [comment]
> not sure if this can solve your problem.

请问，vllm和slang支持多并发吗？

**Comment by suxuanning** [comment]
> > not sure if this can solve your problem.
> 
> 请问，vllm和slang支持多并发吗？

vllm 支持多并发

**Comment by chuangzhidan** [comment]
> > > not sure if this can solve your problem.
> > 
> > 
> > 请问，vllm和slang支持多并发吗？
> 
> 自己写函数 用vllm 调用支持多并发，或者直接openai接口调用就行了

直接调用openai api风格就行，天然支持多并发？

**Comment by suxuanning** [comment]
> > > > not sure if this can solve your problem.
> > > 
> > > 
> > > 请问，vllm和slang支持多并发吗？
> > 
> > 
> > 自己写函数 用vllm 调用支持多并发，或者直接openai接口调用就行了
> 
> 直接调用openai api风格就行，天然支持多并发？

再怎么并发，模型的处理能力有限，都得排队生成
