### ISSUE TITLE
The WeChat Group link is broken, will there be another one?

### ISSUE THREAD

**Issue by shenxiangzhuang** [QwenLM/Qwen1.5#161]
The picture in [https://github.com/QwenLM/Qwen1.5/blob/main/assets/wechat.png](https://github.com/QwenLM/Qwen1.5/blob/main/assets/wechat.png) is deleted, will there be another one?

**Comment by JustinLin610** [comment]
here https://github.com/QwenLM/Qwen/blob/main/assets/wechat.png
