### ISSUE TITLE
昇腾NPU运行qwen1.5报错

### ISSUE THREAD

**Issue by blue-U** [QwenLM/Qwen1.5#169]
qwen1.5在昇腾npu上运行
运行自带的finetune.sh，报错如下：
![企业微信截图_17104082302326](https://github.com/QwenLM/Qwen1.5/assets/88299664/695393f1-20f9-4e60-8734-bbf1f583cf93)
使用mindspore运行qwen1.5-7B推理时，vocab_file选项需要指定词表文件，之前使用qwen推理时，使用的qwen.tiktoken文件，在qwen1.5模型中未找到该文件，因此换用了之前qwen中的文件，最后推理结果如下：
![企业微信截图_1710405154214](https://github.com/QwenLM/Qwen1.5/assets/88299664/3a967dcd-19fc-48e3-ab94-5509b48abe68)
怀疑是词表文件导致的，是否有好的解决方案呢

**Comment by jklj077** [comment]
Please see if the following could help: https://gitee.com/mindspore/mindformers/blob/dev/research/qwen1_5/qwen1_5.md
