### ISSUE TITLE
千问1.5-api以及显存问题

### ISSUE THREAD

**Issue by bimver** [QwenLM/Qwen1.5#17]
想问下1.5版本部署还支持上一版的openai_api吗，还是必须要用vLLM和SGlang了？其次想问一下72B_int4模型大概需要多大的显存，输入长度怎么样？我之前下了int8模型，在80Ga100上可以部署，但是输入长度超过一两百就显存不够了。

**Comment by vmn171** [comment]
通过HF部署的的openai_api要大改，没找到现成的，谁写好了的可以分享下

**Comment by zouhuigang** [comment]
坐等呀

**Comment by takemars** [comment]
> 通过HF部署的的openai_api要大改，没找到现成的，谁写好了的可以分享下

+1

**Comment by helloHKTK** [comment]
> > 通过HF部署的的openai_api要大改，没找到现成的，谁写好了的可以分享下
> 
> +1

+1

**Comment by JustinLin610** [comment]
https://qwen.readthedocs.io/en/latest/benchmark/hf_infer.html
