### ISSUE TITLE
stop_words_ids 在generate中无法设置？

### ISSUE THREAD

**Issue by wellcasa** [QwenLM/Qwen1.5#172]
generated_ids = self.model.generate(model_inputs.input_ids, stop_words_ids=[[1]],**kwargs)

  ValueError: The following `model_kwargs` are not used by the model: ['stop_words_ids'] (note: typos in the generate arguments will also show up in this list)

**Comment by JianxinMa** [comment]
参考这个qwen1的代码：https://huggingface.co/Qwen/Qwen-72B-Chat/blob/main/modeling_qwen.py#L1250

通过配置StopWordsLogitsProcessor来实现对stop_words的支持。

唉，hf是真不好用，有条件还是用vllm或ollama启动个openai兼容api好用些。

**Comment by wellcasa** [comment]
> 参考这个qwen1的代码：https://huggingface.co/Qwen/Qwen-72B-Chat/blob/main/modeling_qwen.py#L1250
> 
> 通过配置StopWordsLogitsProcessor来实现对stop_words的支持。
> 
> 唉，hf是真不好用，有条件还是用vllm或ollama启动个openai兼容api好用些。

嗯嗯。看到这个地方了。我也在想抄这个地方。但是我想为啥官方不写好呢。毕竟这个是经常用的组件。

**Comment by JianxinMa** [comment]
Qwen团队人手不足，帮我们骂骂老板，给我们加人手

**Comment by wellcasa** [comment]
> Qwen团队人手不足，帮我们骂骂老板，给我们加人手

花名？

**Comment by wellcasa** [comment]
```

import os
import re
import copy
import json
import time
# from argparse import ArgumentParser
# from contextlib import asynccontextmanager
# from typing import Dict, List, Literal, Optional, Union
# from dataclasses import dataclass, field
# from types import MethodType
import torch
import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers.generation import GenerationConfig
from fastapi.responses import JSONResponse, StreamingResponse, Response
from colorama import Fore, Back, Style, init
import time
import threading
from collections import deque
from multiprocessing import Process, Manager
import subprocess
import numpy as np 
import time
import threading
from collections import deque
import subprocess
import numpy as np 
from datetime import datetime
import time
import asyncio
import random  

checkpoint_path = '/llm/model/manual/qwen1.5/Qwen1.5-1.8B-Chat/v0206/'
tokenizer = AutoTokenizer.from_pretrained(
    checkpoint_path,
    trust_remote_code=True,
)
model = AutoModelForCausalLM.from_pretrained(
    checkpoint_path,
    device_map="cuda:0",
    torch_dtype="auto",
    pad_token_id=151645,
    trust_remote_code=True,
).eval()
model.generation_config = GenerationConfig.from_pretrained(
    checkpoint_path,
    pad_token_id=151645,
    trust_remote_code=True,
)
from utils.qwen_generation_utils import  StopWordsLogitsProcessor

from transformers.generation.logits_process import LogitsProcessorList
def msg(messages,**kwargs):
    start_time = time.time()
    kwargs.setdefault('max_new_tokens', 512)
    stop_words=kwargs.pop("stop",None)
    if stop_words is not None:
        print(f"stop_words : {stop_words}")
        stop_words_ids = [tokenizer.encode(_) for _ in stop_words]
        print(f"stop_words_ids : {stop_words_ids}")
        
        stop_words_logits_processor = StopWordsLogitsProcessor(
            stop_words_ids=stop_words_ids,
            eos_token_id=model.generation_config.eos_token_id,
        )
        logits_processor = LogitsProcessorList([stop_words_logits_processor])
    else:
        logits_processor = None


    text = tokenizer.apply_chat_template(messages,tokenize=False,add_generation_prompt=True)
    model_inputs = tokenizer([text], return_tensors="pt").to(model.device)
    generated_ids = model.generate( model_inputs.input_ids,
                                    generation_config=model.generation_config,  
                                    logits_processor=logits_processor,
                                   **kwargs)
    generated_ids = [output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)]
    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

    for stop_word in stop_words:
        response = response.replace(stop_word, "").strip()
        
    # print(f"'tokenizer.encode(response) : '{tokenizer.encode(response)}")
    messages.append({"role": "assistant", "content": response})
    end_time = time.time()  # 现在
    return response
    
messages1 = [
    {"role": "system", "content": "你是商家小助手"}
    ,{"role": "user", "content": "你是谁，20个字说明"}]
resp= msg(messages=copy.deepcopy(messages1),stop=['小助手'])
print(resp)
```

**Comment by aldebran97** [comment]
> ```
> 
> import os
> import re
> import copy
> import json
> import time
> # from argparse import ArgumentParser
> # from contextlib import asynccontextmanager
> # from typing import Dict, List, Literal, Optional, Union
> # from dataclasses import dataclass, field
> # from types import MethodType
> import torch
> import uvicorn
> from fastapi import FastAPI, HTTPException
> from fastapi.middleware.cors import CORSMiddleware
> from pydantic import BaseModel, Field
> from transformers import AutoTokenizer, AutoModelForCausalLM
> from transformers.generation import GenerationConfig
> from fastapi.responses import JSONResponse, StreamingResponse, Response
> from colorama import Fore, Back, Style, init
> import time
> import threading
> from collections import deque
> from multiprocessing import Process, Manager
> import subprocess
> import numpy as np 
> import time
> import threading
> from collections import deque
> import subprocess
> import numpy as np 
> from datetime import datetime
> import time
> import asyncio
> import random  
> 
> checkpoint_path = '/llm/model/manual/qwen1.5/Qwen1.5-1.8B-Chat/v0206/'
> tokenizer = AutoTokenizer.from_pretrained(
>     checkpoint_path,
>     trust_remote_code=True,
> )
> model = AutoModelForCausalLM.from_pretrained(
>     checkpoint_path,
>     device_map="cuda:0",
>     torch_dtype="auto",
>     pad_token_id=151645,
>     trust_remote_code=True,
> ).eval()
> model.generation_config = GenerationConfig.from_pretrained(
>     checkpoint_path,
>     pad_token_id=151645,
>     trust_remote_code=True,
> )
> from utils.qwen_generation_utils import  StopWordsLogitsProcessor
> 
> from transformers.generation.logits_process import LogitsProcessorList
> def msg(messages,**kwargs):
>     start_time = time.time()
>     kwargs.setdefault('max_new_tokens', 512)
>     stop_words=kwargs.pop("stop",None)
>     if stop_words is not None:
>         print(f"stop_words : {stop_words}")
>         stop_words_ids = [tokenizer.encode(_) for _ in stop_words]
>         print(f"stop_words_ids : {stop_words_ids}")
>         
>         stop_words_logits_processor = StopWordsLogitsProcessor(
>             stop_words_ids=stop_words_ids,
>             eos_token_id=model.generation_config.eos_token_id,
>         )
>         logits_processor = LogitsProcessorList([stop_words_logits_processor])
>     else:
>         logits_processor = None
> 
> 
>     text = tokenizer.apply_chat_template(messages,tokenize=False,add_generation_prompt=True)
>     model_inputs = tokenizer([text], return_tensors="pt").to(model.device)
>     generated_ids = model.generate( model_inputs.input_ids,
>                                     generation_config=model.generation_config,  
>                                     logits_processor=logits_processor,
>                                    **kwargs)
>     generated_ids = [output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)]
>     response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
> 
>     for stop_word in stop_words:
>         response = response.replace(stop_word, "").strip()
>         
>     # print(f"'tokenizer.encode(response) : '{tokenizer.encode(response)}")
>     messages.append({"role": "assistant", "content": response})
>     end_time = time.time()  # 现在
>     return response
>     
> messages1 = [
>     {"role": "system", "content": "你是商家小助手"}
>     ,{"role": "user", "content": "你是谁，20个字说明"}]
> resp= msg(messages=copy.deepcopy(messages1),stop=['小助手'])
> print(resp)
> ```

亲测有效！
