### ISSUE TITLE
Qwen1.5-7B-Chat 最佳学习实践教程~

### ISSUE THREAD

**Issue by KMnO4-zx** [QwenLM/Qwen1.5#18]
**_Qwen1.5实测确实表现很优秀，hhh。火速更新了一手Qwen1.5的学习实践教程~ 大家可以春节愉快的做卷王了!_**

**_项目地址：https://github.com/datawhalechina/self-llm.git_**

![image](https://github.com/QwenLM/Qwen1.5/assets/77671993/0f1f3e65-79fc-49e2-804c-2b1195765237)

**Comment by Jintao-Huang** [comment]
modelscope swift也支持了qwen1.5 serires的微调, 推理, 部署.
微调的脚本可以查看这里: https://github.com/modelscope/swift/tree/main/examples/pytorch/llm/scripts/qwen1half_7b_chat

😊 哈哈哈哈
