### ISSUE TITLE
模型微调训练数据处理问题

### ISSUE THREAD

**Issue by sunyclj** [QwenLM/Qwen1.5#184]
[https://github.com/QwenLM/Qwen1.5/blob/main/examples/sft/finetune.py#L156](url)
对训练数据处理这块，为什么input_ids、target_ids除了补充的token是不一致的，其他都是一致的呢？按照这个逻辑训练没问题嘛？我理解的模型训练，input_ids应该是 { "role": "user","content": ""}、target_ids应该是{ "role": "assistant", "content": ""}，我的理解有问题嘛？

**Comment by houlong666** [comment]
求问理解了么？后续sft是按这个方式做的么？效果如何？

**Comment by jklj077** [comment]
I would suggest you to read the original GPT paper.

Qwen, like GPT or any other current large language models, is a decoder-only language model or causal language model, where the main training objective is just to predict the next token given the provided tokens. It is not a sequence-to-sequence models, where source sequences and target sequences are modeled differently.
