### ISSUE TITLE
CUDA_VISIBLE_DEVICES=0,1,2,3,4 python3 -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-72B-Chat --model /data/models/Qwen1.5-72B-Chat 只能在一张卡上运行

### ISSUE THREAD

**Issue by cuiyongchao** [QwenLM/Qwen1.5#187]
CUDA_VISIBLE_DEVICES=0,1,2,3,4 python3 -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-72B-Chat --model /data/models/Qwen1.5-72B-Chat --host 0.0.0.0 --port 8089
出现问题：
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 768.00 MiB. GPU 0 has a total capacty of 79.15 GiB of which 752.31 MiB is free. Process 25252 has 18.65 GiB memory in use. Process 36870 has 19.11 GiB memory in use. Process 28066 has 728.00 MiB memory in use. Process 40071 has 4.90 GiB memory in use. Process 39903 has 1.87 GiB memory in use. Process 56994 has 3.66 GiB memory in use. Including non-PyTorch memory, this process has 29.47 GiB memory in use. Of the allocated memory 28.83 GiB is allocated by PyTorch, and 12.70 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
为什么只能在0号卡上运行

**Comment by Jarvanen** [comment]
--tensor-parallel-size 4

**Comment by Jarvanen** [comment]
--tensor-parallel-size 4

**Comment by Jarvanen** [comment]
--tensor-parallel-size 4
