### ISSUE TITLE
Do you support local stream inference？

### ISSUE THREAD

**Issue by CVer2022** [QwenLM/Qwen1.5#191]
I didn't find an example of local stream inference in the tutorial, what should I do？

**Comment by JustinLin610** [comment]
https://qwen.readthedocs.io/en/latest/inference/chat.html check it here

**Comment by JustinLin610** [comment]
Just learn about TextStreamer

**Comment by JustinLin610** [comment]
I'll just close this and you can reopen if you have any more questions
