### ISSUE TITLE
微调后，qwen 1.5 14B 远弱于 qwen 1.0 14B

### ISSUE THREAD

**Issue by songyingxin** [QwenLM/Qwen1.5#194]
采用 llama_factory 训练， 参数都一样，长度 4096， 学习率 1e-5。 
实际结果测下来，微调后的 qwen 1.5 远弱于 qwen 1.0。

目前在测 qwen 7B / qwen 1.5 7B。

**Comment by 2286573608** [comment]
是在垂直领域微调的吗

**Comment by songyingxin** [comment]
conifg设置错了
