### ISSUE TITLE
求助：CUDA out of memory  （14B的模型文件无法在4块A10上运行，提示显存不足）

### ISSUE THREAD

**Issue by aaronyy9** [QwenLM/Qwen1.5#195]
报错：
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 134.00 MiB. GPU 0 has a total capacity of 21.98 GiB of which 34.44 MiB is free. Including non-PyTorch memory, this process has 21.93 GiB memory in use. Of the allocated memory 21.58 GiB is allocated by PyTorch, and 136.34 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
截图：
<img width="1258" alt="image" src="https://github.com/QwenLM/Qwen1.5/assets/54395520/8e6fa883-6ac7-4255-afb0-141c02762e3f">
显卡截图：
<img width="761" alt="image" src="https://github.com/QwenLM/Qwen1.5/assets/54395520/bd781dd6-66f1-46b3-a00a-795700d24705">

程序：
```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

def main():
    # 设置CUDA设备
    device = "cuda" if torch.cuda.is_available() else "cpu"

    # 加载模型和分词器
    model = AutoModelForCausalLM.from_pretrained(
        "Qwen/Qwen1.5-14B-Chat",
        torch_dtype="auto",
        device_map="auto"
    ).to(device)
    tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen1.5-14B-Chat")

    # 循环与用户进行对话
    while True:
        prompt = input("请输入您的问题（输入'退出'来结束对话）: ")
        if prompt.lower() == '退出':
            break

        messages = [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]

        # 准备输入数据
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        model_inputs = tokenizer([text], return_tensors="pt").to(device)

        # 生成回应
        generated_ids = model.generate(
            model_inputs.input_ids,
            max_new_tokens=512
        )
        generated_ids = [
            output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
        ]

        # 解码生成的回应
        response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

        print("模型回应:", response)

if __name__ == "__main__":
    main()
```

**Comment by Xls1994** [comment]
看起来是只在一块显卡上跑了

**Comment by JustinLin610** [comment]
Check if you have setup your `CUDA_VISIBLE_DEVICES` correctly

**Comment by aaronyy9** [comment]
> 看起来是只在一块显卡上跑了
谢谢回复。程序运行时我有确定没块GPU上都有明显的GPU占用（10G以上），最后加载完毕后才报的错。从日志看确实是显示似乎把0给跑死了，我也没有找到指定模型文件到具体GPU的方法

**Comment by aaronyy9** [comment]
> Check if you have setup your `CUDA_VISIBLE_DEVICES` correctly
1. The screenshot below shows the GPU resource usage when the model is loaded onto the 7th block. It can be seen that each graphics card is utilized. After the last, the eighth, model file, the initial prompt of insufficient GPU memory appears.
![image](https://github.com/QwenLM/Qwen1.5/assets/54395520/cbb3f869-bd30-4c0a-b253-1913d7f4b100)


3. In response to what you mentioned, I have added the following code to specify 4 GPUs, but the problem persists. The code is as follows:
```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"
```

**Comment by GXKIM** [comment]
> > 看起来是只在一块显卡上跑了
> > 谢谢回复。程序运行时我有确定没块GPU上都有明显的GPU占用（10G以上），最后加载完毕后才报的错。从日志看确实是显示似乎把0给跑死了，我也没有找到指定模型文件到具体GPU的方法

官方的脚本不知道为什么现在都很吃显存

**Comment by JustinLin610** [comment]
https://qwen.readthedocs.io/en/latest/benchmark/hf_infer.html This doc might provide some more info for you to debug. You can also check whether the loading is not in bf16 but in fp32 (it shouldn't happen with `torch_dtype="auto"` btw).

**Comment by jklj077** [comment]
The total memory at start was 26~27GB, which is about right for the 14B model in half precision floating point.

May I know how long is the input?

**Comment by jklj077** [comment]
Also, you should not do this:
```python
def main():
    # 设置CUDA设备
    device = "cuda" if torch.cuda.is_available() else "cpu"

    # 加载模型和分词器
    model = AutoModelForCausalLM.from_pretrained(
        "Qwen/Qwen1.5-14B-Chat",
        torch_dtype="auto",
        device_map="auto"
    ).to(device)
```

Try this instead:
```python
def main():
    # 加载模型和分词器
    model = AutoModelForCausalLM.from_pretrained(
        "Qwen/Qwen1.5-14B-Chat",
        torch_dtype="auto",
        device_map="auto" if torch.cuda.is_available() else "cpu",
    ).to(device)
```
