### ISSUE TITLE
微调后，模型回答会在正确的答案后继续输出很多内容

### ISSUE THREAD

**Issue by trunks023** [QwenLM/Qwen1.5#198]
微调后，模型回答会在正确的答案后继续输出很多内容，一共大概会输出800个字符左右。有大佬知道是什么原因吗？

**Comment by jklj077** [comment]
To offer more targeted advice, I would kindly ask for additional context as the current details provided are quite sparse. With such limited information, it's difficult to offer anything but speculative suggestions.

My hypothesis, given the scant data, is that perhaps you're fine-tuning a base model without adjusting the "generation_config.json" file accordingly. If this indeed is the case, a potential solution might be to simply replace your current "generation_config.json" file with one specifically tailored for a chat-oriented model.

However, please do provide more specifics, so a more comprehensive and applicable solution can be given.

**Comment by trunks023** [comment]
我微调是的通义千问 QwenV1.5-1.8B-Chat对话模型(不是base模型)，generation_config.json使用的是默认配置：
```
{
  "bos_token_id": 151643,
  "pad_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "repetition_penalty": 1.1,
  "top_p": 0.8,
  "transformers_version": "4.37.0"
}


```


> To offer more targeted advice, I would kindly ask for additional context as the current details provided are quite sparse. With such limited information, it's difficult to offer anything but speculative suggestions.
> 
> My hypothesis, given the scant data, is that perhaps you're fine-tuning a base model without adjusting the "generation_config.json" file accordingly. If this indeed is the case, a potential solution might be to simply replace your current "generation_config.json" file with one specifically tailored for a chat-oriented model.
> 
> However, please do provide more specifics, so a more comprehensive and applicable solution can be given.

**Comment by trunks023** [comment]
@jklj077 大佬，您好，今天我尝试了使用swift框架来进行微调，我分别尝试了使用deepspeed和不使用deepspeed。微调后的模型均可以输出正确的答案，不会附加其他的内容。我猜想，可能是示例微调代码的某处存在bug。

**Comment by jklj077** [comment]
maybe @JustinLin610 could take a look. but we still need steps to reproduce, including the data examples.

**Comment by trunks023** [comment]
> maybe @JustinLin610 could take a look. but we still need steps to reproduce, including the data examples.

采用的以下模板进行的微调。
```
{
        "type": "chatml",
        "messages": [
            {
                "role": "system",
                "content": "你是一个智能问答助手"
            },
            {
                "role": "user",
                "content":  "content"
            },
            {
                "role": "assistant",
                "content": "answer"
            }
        ],
        "source": "unknown"
    }
```

**Comment by STHSF** [comment]
![image](https://github.com/QwenLM/Qwen1.5/assets/8037442/7db09092-a37f-41fd-b0e0-50f083b65a67)
我在微调后也出现同样的问题，把训练数据打印出来后发现每一条数据最后没有'<|im_end|>'，猜测可能是这个原因。

**Comment by STHSF** [comment]
> ![image](https://private-user-images.githubusercontent.com/8037442/317742516-7db09092-a37f-41fd-b0e0-50f083b65a67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzQzNDUsIm5iZiI6MTcxMTYzNDA0NSwicGF0aCI6Ii84MDM3NDQyLzMxNzc0MjUxNi03ZGIwOTA5Mi1hMzdmLTQxZmQtYjBlMC01MGYwODNiNjVhNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTM1NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzlkM2ViMzBiYjM2MTE3Y2ExMzg2Zjg5MTQwMWI1NTNhOTRhNGJhNTRjOWI1MzYwMjA3ZWMyMDdhNDcxNjVlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cLWN3ml7guK_tM97RrqLzHYbcmaZVynkiLBBxygB0y4) 我在微调后也出现同样的问题，把训练数据打印出来后发现每一条数据最后没有'<|im_end|>'，猜测可能是这个原因。 以下是参考https://github.com/QwenLM/Qwen/blob/3ad0c83bb9a31fb3ccb8b70b6ec5a92caa4f7170/finetune.py#L328 使用qwen-14B-chat 添加 ` tokenizer.eos_token = "<|endoftext|>" tokenizer.pad_token = tokenizer.eos_token` 后的结果，我理解下面的才是准确的数据格式@jklj077 ![image](https://private-user-images.githubusercontent.com/8037442/317748080-91b73ace-2f38-4970-8bf8-ef8513ef187e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzQzNDUsIm5iZiI6MTcxMTYzNDA0NSwicGF0aCI6Ii84MDM3NDQyLzMxNzc0ODA4MC05MWI3M2FjZS0yZjM4LTQ5NzAtOGJmOC1lZjg1MTNlZjE4N2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTM1NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTRlODA1ZmQ2NTBlNjZlMzIxNmM3ZTJkZDMxMDMzMzY5OGMyNWE2NzhiZTA0OTNmYmYwZWIyNTQ0Nzk4MDIwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bnkIcJpAAvtb_VUjAfR1fwtwTRIODbah1ypcLzsjDMo)

补充：按照下面截图的方式，把default_chat_template中的template提取出来再引用进去，发现最后一个<|in_end|>就出现了，有点不可思议
![image](https://github.com/QwenLM/Qwen1.5/assets/8037442/6414fc24-c349-483d-8cfb-fdcdd44c1c06)

**Comment by jklj077** [comment]
Hi, @STHSF, thank you very much for this info. We have fixed in main; please give it a try.

**Comment by smallflyingpig** [comment]
> > ![image](https://private-user-images.githubusercontent.com/8037442/317742516-7db09092-a37f-41fd-b0e0-50f083b65a67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzQzNDUsIm5iZiI6MTcxMTYzNDA0NSwicGF0aCI6Ii84MDM3NDQyLzMxNzc0MjUxNi03ZGIwOTA5Mi1hMzdmLTQxZmQtYjBlMC01MGYwODNiNjVhNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTM1NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzlkM2ViMzBiYjM2MTE3Y2ExMzg2Zjg5MTQwMWI1NTNhOTRhNGJhNTRjOWI1MzYwMjA3ZWMyMDdhNDcxNjVlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cLWN3ml7guK_tM97RrqLzHYbcmaZVynkiLBBxygB0y4) 我在微调后也出现同样的问题，把训练数据打印出来后发现每一条数据最后没有'<|im_end|>'，猜测可能是这个原因。 以下是参考https://github.com/QwenLM/Qwen/blob/3ad0c83bb9a31fb3ccb8b70b6ec5a92caa4f7170/finetune.py#L328 使用qwen-14B-chat 添加 ` tokenizer.eos_token = "<|endoftext|>" tokenizer.pad_token = tokenizer.eos_token` 后的结果，我理解下面的才是准确的数据格式@jklj077 ![image](https://private-user-images.githubusercontent.com/8037442/317748080-91b73ace-2f38-4970-8bf8-ef8513ef187e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzQzNDUsIm5iZiI6MTcxMTYzNDA0NSwicGF0aCI6Ii84MDM3NDQyLzMxNzc0ODA4MC05MWI3M2FjZS0yZjM4LTQ5NzAtOGJmOC1lZjg1MTNlZjE4N2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTM1NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTRlODA1ZmQ2NTBlNjZlMzIxNmM3ZTJkZDMxMDMzMzY5OGMyNWE2NzhiZTA0OTNmYmYwZWIyNTQ0Nzk4MDIwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bnkIcJpAAvtb_VUjAfR1fwtwTRIODbah1ypcLzsjDMo)
> 
> 补充：按照下面截图的方式，把default_chat_template中的template提取出来再引用进去，发现最后一个<|in_end|>就出现了，有点不可思议 ![image](https://private-user-images.githubusercontent.com/8037442/317766400-6414fc24-c349-483d-8cfb-fdcdd44c1c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjQ5MjEsIm5iZiI6MTcxMjQ2NDYyMSwicGF0aCI6Ii84MDM3NDQyLzMxNzc2NjQwMC02NDE0ZmMyNC1jMzQ5LTQ4M2QtOGNmYi1mZGNkZDQ0YzFjMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMDQzNzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzU0ODlhNjMwMDJhNDkwYWU0Mjg4ZDQzNDc2NGZhMzUxOWU5ODY4OGVkMGMxYzM4MTY2YTgyYTRiYTc1OTE0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aAeCr07pFQjJPzc8B1dP4BKrGg6WPA8pZrIy_Xsn_Hg)

对比了qwen1.5 tokenizer_config.json和huggingface transformers中的default chat template(https://github.com/huggingface/transformers/blob/76fa17c1663a0efeca7208c20579833365584889/src/transformers/tokenization_utils_base.py#L1838)，发现qwen1.5的chat template没有在多轮对话中间轮次末尾添加eos_token，只在多轮对话最后一轮后面添加eos_token，这应该是一个BUG。所以将chat_template改为default chat template后能有效解决这个问题

**Comment by smallflyingpig** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/8037442/317742516-7db09092-a37f-41fd-b0e0-50f083b65a67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzQzNDUsIm5iZiI6MTcxMTYzNDA0NSwicGF0aCI6Ii84MDM3NDQyLzMxNzc0MjUxNi03ZGIwOTA5Mi1hMzdmLTQxZmQtYjBlMC01MGYwODNiNjVhNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTM1NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzlkM2ViMzBiYjM2MTE3Y2ExMzg2Zjg5MTQwMWI1NTNhOTRhNGJhNTRjOWI1MzYwMjA3ZWMyMDdhNDcxNjVlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cLWN3ml7guK_tM97RrqLzHYbcmaZVynkiLBBxygB0y4) 我在微调后也出现同样的问题，把训练数据打印出来后发现每一条数据最后没有'<|im_end|>'，猜测可能是这个原因。 以下是参考https://github.com/QwenLM/Qwen/blob/3ad0c83bb9a31fb3ccb8b70b6ec5a92caa4f7170/finetune.py#L328 使用qwen-14B-chat 添加 ` tokenizer.eos_token = "<|endoftext|>" tokenizer.pad_token = tokenizer.eos_token` 后的结果，我理解下面的才是准确的数据格式@jklj077 ![image](https://private-user-images.githubusercontent.com/8037442/317748080-91b73ace-2f38-4970-8bf8-ef8513ef187e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzQzNDUsIm5iZiI6MTcxMTYzNDA0NSwicGF0aCI6Ii84MDM3NDQyLzMxNzc0ODA4MC05MWI3M2FjZS0yZjM4LTQ5NzAtOGJmOC1lZjg1MTNlZjE4N2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTM1NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTRlODA1ZmQ2NTBlNjZlMzIxNmM3ZTJkZDMxMDMzMzY5OGMyNWE2NzhiZTA0OTNmYmYwZWIyNTQ0Nzk4MDIwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bnkIcJpAAvtb_VUjAfR1fwtwTRIODbah1ypcLzsjDMo)
> > 
> > 
> > 补充：按照下面截图的方式，把default_chat_template中的template提取出来再引用进去，发现最后一个<|in_end|>就出现了，有点不可思议 ![image](https://private-user-images.githubusercontent.com/8037442/317766400-6414fc24-c349-483d-8cfb-fdcdd44c1c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjQ5MjEsIm5iZiI6MTcxMjQ2NDYyMSwicGF0aCI6Ii84MDM3NDQyLzMxNzc2NjQwMC02NDE0ZmMyNC1jMzQ5LTQ4M2QtOGNmYi1mZGNkZDQ0YzFjMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMDQzNzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzU0ODlhNjMwMDJhNDkwYWU0Mjg4ZDQzNDc2NGZhMzUxOWU5ODY4OGVkMGMxYzM4MTY2YTgyYTRiYTc1OTE0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aAeCr07pFQjJPzc8B1dP4BKrGg6WPA8pZrIy_Xsn_Hg)
> 
> 对比了qwen1.5 tokenizer_config.json和huggingface transformers中的default chat template([https://github.com/huggingface/transformers/blob/76fa17c1663a0efeca7208c20579833365584889/src/transformers/tokenization_utils_base.py#L1838)，发现qwen1.5的chat](https://github.com/huggingface/transformers/blob/76fa17c1663a0efeca7208c20579833365584889/src/transformers/tokenization_utils_base.py#L1838)%EF%BC%8C%E5%8F%91%E7%8E%B0qwen1.5%E7%9A%84chat) template在add_generation_prompt为false时不会在最后一轮后面添加eos_token，而微调脚本在构造数据时add_generation_prompt=false

三天前官方huggingface仓库中的chat模型都更新了一下，把tokenizer_config.json中的chat_template更新了，现在应该不会出现这个问题了
