### ISSUE TITLE
"Qwen2Tokenizer" cannot encode some words correctly

### ISSUE THREAD

**Issue by Line290** [QwenLM/Qwen1.5#199]
Below is the BUG:
transformers==4.37.1
```python

t = AutoTokenizer.from_pretrained("Qwen1.5-72B-Chat", trust_remote_code=True, use_fast=False)
t_fast = AutoTokenizer.from_pretrained("Qwen1.5-72B-Chat", trust_remote_code=True, use_fast=True)

t.encode("#######")
# Out: [2, 2, 2, 2, 2, 2, 2]

t_fast.encode("#######")
# Out: [97864]
```
There are 120+ words in the vocabulary with the same BUG.

**Comment by jklj077** [comment]
For the issues related to "#" in the slow tokenizer (Qwen2Tokenizer), please try [this branch](https://github.com/jklj077/transformers/tree/patch-1) and see if the problem could be fixed. There should be 121 tokens affected by this.

**Comment by Line290** [comment]
It was fixed after I followed your branch and modified the code at [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/qwen2/tokenization_qwen2.py#L188). Thank you.
