### ISSUE TITLE
微调loss下降很快，但有时会出现不按微调格式输出的情况，有时会多余输出乱码等

### ISSUE THREAD

**Issue by heimaojinzhangyz** [QwenLM/Qwen1.5#203]
规定输出格式为json，5万条数据微调，微调后有时会自行改变输出的json字段，即在规定字段后面多生成一些符号或乱码字符

**Comment by Jarvanen** [comment]
一样的情况 请问下微调的参数你是怎么设置的  我用了同样的参数和数据 1.0微调没问题

**Comment by heimaojinzhangyz** [comment]
> 一样的情况 请问下微调的参数你是怎么设置的 我用了同样的参数和数据 1.0微调没问题

这个触发条件找到了，利用cpu推理会出现这个现象但GPU没事

**Comment by jklj077** [comment]
Hi, all, if you were using `examples/sft/finetune.py` and the issue is that the model cannot generate "<|im_end|>" at the right place, which causes it to generate more text than it should, the issue has been fixed in the main branch.
