### ISSUE TITLE
请问HF上Qwen1.5-14B-Chat-GPTQ-Int4对应ollama里面哪个tag

### ISSUE THREAD

**Issue by SoaringTiger** [QwenLM/Qwen1.5#206]
我在ollama里面下载了 qwen:14b-chat-q4_0, 对比HF上的 Qwen1.5-14B-Chat-GPTQ-Int4 , 结果似乎差异很大

**Comment by JustinLin610** [comment]
no ollama is sth based on gguf. this is the official release not ours. it should be consistent with our q4_0 gguf file

**Comment by SoaringTiger** [comment]
> no ollama is sth based on gguf. this is the official release not ours. it should be consistent with our q4_0 gguf file

谢谢
