### ISSUE TITLE
[BUG] Qwen1.5-14B回答不会停止，会自动进行对话，或者出现重复回答

### ISSUE THREAD

**Issue by Parasolation** [QwenLM/Qwen1.5#217]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

采用本库给的cli_demo.py或者web_demo.py启动都会遇到该问题
![image](https://github.com/QwenLM/Qwen/assets/51755826/4823ea08-dba2-4acc-b427-c6c011b16915)
![image](https://github.com/QwenLM/Qwen/assets/51755826/f0363d29-1b08-4e36-b3d5-50bbf3cfc191)

### 期望行为 | Expected Behavior

希望能得到正确回答，如上图只需要回答“你好！有什么我可以帮助你的吗？”以及重复的只回答一遍

### 运行环境 | Environment

```Markdown
- OS:Ubuntu22.04
- Python:3.10
- Transformers:4.39.1
- PyTorch:2.21
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by jklj077** [comment]
Please try using the code from QwenLM/Qwen1.5 (the current repo).

**Comment by zhenfenxiao** [comment]
> Please try using the code from QwenLM/Qwen1.5 (the current repo).

I met the same question using code from QwenLM/Qwen1.5.

**Comment by wrl1224** [comment]
遇到了同样的问题

**Comment by JustinLin610** [comment]
I suspect that you are using base model instead of chat model? Use Qwen1.5-14B-Chat and follow the example code

**Comment by Riel1998** [comment]
我也遇到同样的问题，但是切换到chat版本就没有问题。。。

**Comment by jklj077** [comment]
Opt for chat models instead, as base models lack the chat template functionality. Their primary application revolves around text completion leveraging in-context learning.
