### ISSUE TITLE
14b-base模型推理脚本怎么没有呀？和chat模型的推理脚本肯定不一样吧？

### ISSUE THREAD

**Issue by yawzhe** [QwenLM/Qwen1.5#223]
我该怎么评估续写BASE模型的能力呀

**Comment by jklj077** [comment]
For base models, you could simply use

```python
inputs = tokenizer("...").to(model.device)
outputs = model.generate(**inputs)
```

Please be aware that the **base** models may require a lot of efforts to make them work.
