### ISSUE TITLE
能不能给个微信群呢？

### ISSUE THREAD

**Issue by sirliuyang** [QwenLM/Qwen1.5#224]
之前的微信群都失效了，麻烦给个新的群。

**Comment by jklj077** [comment]
![image](https://github.com/QwenLM/Qwen1.5/assets/17811943/fe2ad7d9-e94c-4cf7-ae31-314f52e56cba)

I don't think No. 29 is full.

**Comment by jklj077** [comment]
Please reopen if you still cannot join the WeChat group.
