### ISSUE TITLE
qwen:1.5-cu121 镜像 run提示

### ISSUE THREAD

**Issue by peterliang5678** [QwenLM/Qwen1.5#226]
Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

**Comment by jklj077** [comment]
If the image is to be deleted at a later time, you are still able to use the pre-built docker image from us at <https://hub.docker.com/r/qwenllm/qwen/tags>.

**Comment by peterliang5678** [comment]
我下周的就是你们提供的镜像
然后run 报错......
The error you encountered when starting the pre-built Docker image you downloaded from us is the one you posted above. The command you used for downloading is:
下载地址方式docker pull qwenllm/qwen:1.5-cu121

**Comment by peterliang5678** [comment]
未解决....

**Comment by jklj077** [comment]
Please provide the actual error logs.

**Comment by peterliang5678** [comment]
命令如下
sudo docker run --gpus all -it --rm --name qwen-model --mount type=bind,source=/home/zhdk-admin/ai/Qwen/Qwen1.5-1.8B-Chat,target=/data/shared/Qwen/Qwen-Chat --mount type=bind,source=/home/zhdk-admin/ai/Qwen/code1.5,target=/data/shared/Qwen --mount type=bind,source=/home/zhdk-admin/ai/Qwen/data,target=/data/shared/Qwen/data --mount type=bind,source=/home/zhdk-admin/ai/Qwen/output/checkpoint,target=/data/shared/Qwen/output_qwen -p 80:80 --shm-size=12gb qwenllm/qwen:1.5-cu121


--------------
进入容器后运行 python web_demo.py 
报错


Traceback (most recent call last):
  File "web_demo.py", line 183, in <module>
    main()
  File "web_demo.py", line 177, in main
    model, tokenizer = _load_model_tokenizer(args)
  File "web_demo.py", line 38, in _load_model_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 773, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 1100, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 634, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py", line 425, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Qwen/Qwen-Chat is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

备注：已经挂载成功了模型和源码
