### ISSUE TITLE
Qwen1.5如何适配华为昇腾910B?能适配吗？

### ISSUE THREAD

**Issue by yawzhe** [QwenLM/Qwen1.5#238]
Qwen1.5如何适配华为昇腾910B?能适配吗？

**Comment by jklj077** [comment]
There is a community PR at <https://gitee.com/mindspore/mindformers/pulls/2619>. It looks promising, but we are unable to test it due to lack of the specific devices.

**Comment by dongdongqiang2018** [comment]
look this: https://gitee.com/mindspore/mindformers/blob/r1.0/research/qwen1_5/qwen1_5.md

**Comment by jklj077** [comment]
The inference code has been merged but the training code seems not. Closed for now; please kindly seek support from mindformers maintainers.
