### ISSUE TITLE
QWen1.5 推理报错：KeyError: 'qwen2'

### ISSUE THREAD

**Issue by zhl970124** [QwenLM/Qwen1.5#247]
按照quick start中的 transformer调用方法，给的例子运行。报错KeyError: 'qwen2' 。 是不是因为transformers版本低于4.37.0导致的。 我尝试了安装transformers==4.37.1， 但是超时。换源也找不到资源，求教~

**Comment by jklj077** [comment]
`transformers>=4.37.0` should be fine. The package is on PyPI, which should be accessible.

If you mean the model downloading timed out, try using ModelScope to download the model files.
