### ISSUE TITLE
chat 模型，如何适配多轮对话的输入

### ISSUE THREAD

**Issue by minmummax** [QwenLM/Qwen1.5#249]
我理解的不知道对不对
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt1}，
 {"role": "assistant", "content": prompt1_answer},
    {"role": "user", "content": prompt2}，
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
是这么组合吗？是的话回复1

**Comment by jklj077** [comment]
It is indeed the case.
