### ISSUE TITLE
Qwen1.5 72B Chat AWQ 需要多少显存可以运行

### ISSUE THREAD

**Issue by deku0818** [QwenLM/Qwen1.5#253]

**Comment by JustinLin610** [comment]
https://qwen.readthedocs.io/zh-cn/latest/benchmark/hf_infer.html#

**Comment by Lu0Key** [comment]
> https://qwen.readthedocs.io/zh-cn/latest/benchmark/hf_infer.html#

这里的内存是不是笔误，应该改成显存呀
