### ISSUE TITLE
这么大公司不测试自己的模型就发布？

### ISSUE THREAD

**Issue by xinyujituan** [QwenLM/Qwen1.5#256]
Ubuntu20,python3.9，安装最新的所有模块，运行模型预测demo，无论怎么预测都会自我疯狂对话，难道你们不测试就发不出来了？

**Comment by JianxinMa** [comment]
大公司的一个团队能有多小，你们可能不知道。:(

**Comment by LiuChen19960902** [comment]
谢帝 谢帝

**Comment by JustinLin610** [comment]
请列清楚具体使用的问题，并且说明报错。这类issue我都会统一关闭。
