### ISSUE TITLE
Qwen1.5-32B-Chat 的编码能力似乎不如14B和72B

### ISSUE THREAD

**Issue by lordk911** [QwenLM/Qwen1.5#259]
1、基于RAG的text2sql场景
2、用户提问时，会把相关的表结构信息给到LLM, 要求LLM用SQL回答问题
3、假如问题是：最近一个月已签退的会议有多少？
4、需要生成的SQL方言为Doris

Qwen 32B 生成的SQL在调用数据库函数时不会加括号：
```
ERROR parse_view_response error!(pymysql.err.OperationalError) (1054, "errCode = 2, detailMessage = Unknown column 'CURRENT_DATE' in 'table list'")
[SQL: SELECT COUNT(*) FROM meeting_info WHERE meeting_status = 40 AND meeting_date BETWEEN DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH) AND CURRENT_DATE]
```
如上所示，取当前日期应该是
`CURRENT_DATE()`

14与72B的规格都能正确生成数据库函数调用的SQL.

**Comment by lordk911** [comment]
@JianxinMa 110B 同样的问题，有什么发现吗？

**Comment by JianxinMa** [comment]
@huybery qwen2这方面会有改善吗？

**Comment by huybery** [comment]
Qwen2 的 Text-to-SQL 能力会改善，敬请期待 @lordk911

**Comment by lordk911** [comment]
> Qwen2 的 Text-to-SQL 能力会改善，敬请期待 @lordk911

<img width="525" alt="image" src="https://github.com/QwenLM/Qwen2/assets/19989300/fbecc9d4-c2fd-4e03-af5c-2d3727183f1a">

@huybery
