### ISSUE TITLE
Question about finetuning

### ISSUE THREAD

**Issue by hn529945497** [QwenLM/Qwen1.5#261]
想问一下微调之后，Qwen1.5的base版本，{'input_ids': [None, 32, 25, 220, 108386, 35946, 108850, 102815, 94444, 20412, 99459, 55502, 39953, 73296, 104673, 99901, 24156, 198, 33, 25, 69372, 98749, 51154, 25177, 99720, 102289, 108617, 198, 22043, 264, 3239, 362, 323, 264, 21085, 425, 11, 8253, 3425, 279, 21085, 5610, 458, 4226, 311, 279, 3239, 553, 8241, 264, 19639, 315, 2987, 364, 9454, 6, 476, 364, 2753, 4427, 198, 22043, 264, 3239, 362, 323, 264, 21085, 425, 11, 8253, 3425, 279, 21085, 5610, 458, 4226, 311, 279, 3239, 553, 8241, 264, 19639, 315, 2987, 364, 9454, 6, 476, 364, 2753, 4427], 生成的token开头变成none了，如何去解决。

**Comment by hn529945497** [comment]
return tokenizer.pad(
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3320, in pad
    raise ValueError(
ValueError: type of None unknown: <class 'NoneType'>. Should be one of a python, numpy, pytorch or tensorflow object.
加载的时候是这个报错

**Comment by jklj077** [comment]
I think you need to set the padding token if you need to pad the input token sequences somehow. Normally, using `<|endoftext|>` should be fine in inference. For training, you may need to also consider how masking is applied.

**Comment by hn529945497** [comment]
这个是咋推理的时候，感觉是tokenization的时候，一句话的开始的标识符，给变成了none，这个能在词表里修改<|endoftext|>吗，或者还有什么别的解决方案，

**Comment by jklj077** [comment]
There is no such thing as signifier of start of a sentence in Qwen/Qwen1.5 and the error suggests you are padding the input sequences.

If you need more specific comments, please provide steps to reproduce.

**Comment by JustinLin610** [comment]
and
