### ISSUE TITLE
Qwen1.5 has adopted a different way to support long-context extension and DynamicNTK and LogN attention are no longer in use.

### ISSUE THREAD

**Issue by TZJ12** [QwenLM/Qwen1.5#265]
Qwen1.5 has adopted a different way to support long-context extension and DynamicNTK and LogN attention are no longer in use.

_Originally posted by @jklj077 in https://github.com/QwenLM/Qwen1.5/issues/208#issuecomment-2017323208_

**Comment by TZJ12** [comment]
我想问一下Qwen1.5可以通过什么方式来扩展上下文呢

**Comment by jklj077** [comment]
The settings in provided model files have already extended the support of sequence length to 32K. May I ask how long is expected in your application?
