### ISSUE TITLE
使用vllm部署qwen1.5-32b-gptq-int4输出token为0

### ISSUE THREAD

**Issue by WSR-wsr** [QwenLM/Qwen1.5#269]
当输入token比较短（约50以内）时，logprob变为nan，输出token变为0，表现为输出为'!!!!...'，且不会停止，输出到上限为止。
长文本正常
awq正常

**Comment by JustinLin610** [comment]
This is a recent known issue perhaps caused by vLLM. We are now reporting this issue to the official github repo. Temporarily we advise you to use AWQ model and also vLLM 0.3.3 but not the latest 0.4.

**Comment by kratorado** [comment]
met the same problem
