### ISSUE TITLE
请问Qwen1.5在prompt和stop token上和1代有变化吗？

### ISSUE THREAD

**Issue by mzh1996** [QwenLM/Qwen1.5#27]
我尝试了沿用以前部署Qwen-chat-14b的代码对Qwen1.5-chat-14b进行vllm部署，然后在RAG流程中沿用之前的请求方式。
发现回答结果有不少变得很长，甚至出现了一些类似"\n\n\n\n\n"的内容，或吐出了一些不太相关的内容
根据经验判断，要么是没有配置好prompt，要么是没有配置好stopword
请问Qwen1.5b的prompt、stopword等相比于上一代是否发生了变化？

**Comment by JustinLin610** [comment]
参考readme的用例，直接使用vllm，要用apply_chat_template给输入封上chatml格式

**Comment by mzh1996** [comment]
> apply_chat_template

感谢

**Comment by junjzhang** [comment]
@mzh1996 请问你\n\n\n问题解决了吗，我在vllm中使用了chatml的template还是会有这个问题

**Comment by mzh1996** [comment]
> @mzh1996 请问你\n\n\n问题解决了吗，我在vllm中使用了chatml的template还是会有这个问题

暂时没有，我觉得我还是没成功套上chatml模板

**Comment by junjzhang** [comment]
@mzh1996 我解决了，在请求时使用 skip_special_tokens=False

**Comment by mzh1996** [comment]
@junjzhang 牛的，不过感觉可能咱们用的方式还是不对（比如template的加载），按理来说不应该这样的。我尝试硬在prompt构造时加上You are a helpful assistant的那个模板，效果改善不少
