### ISSUE TITLE
请问使用qwen1.5-1.8，生成停不下来，官方给的预测代码，qwen1.5-1.8B-chat没有问题，那qwen1.5-1.8该如何预测呢？

### ISSUE THREAD

**Issue by Riel1998** [QwenLM/Qwen1.5#270]
`model_path = "./model/qwen1_5-1_8b"
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_path)

prompt = '苹果是什么颜色'
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

model_inputs = tokenizer([text], return_tensors="pt").to(device)

generated_ids = model.generate(
        input_ids=model_inputs.input_ids,
        max_new_tokens=512,
        do_sample=False,  # 关闭采样
        top_p=0.9,
        temperature=1,
        repetition_penalty=1,
        eos_token_id=tokenizer.eos_token_id
    )
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]
response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
print(response)`

输出结果如下
`>>> print(response)
答案：苹果的颜色有红、绿、黄、紫、橙、棕、黑、白等。苹果的品种很多，有红富士、嘎啦、金帅、国光、红玉、红玉冠、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、红玉早、`

**Comment by Riel1998** [comment]
我测试了qwen1.5-1.8B-chat版本生成没有问题

**Comment by Riel1998** [comment]
已解决：
![image](https://github.com/QwenLM/Qwen1.5/assets/67248243/af4ddf3e-ed3b-472e-a2bf-293a04a8b2e3)
![Uploading img_v3_029o_7e3ac8fc-d785-4f36-860e-c4cae4b5bc2g.jpg…]()

**Comment by JustinLin610** [comment]
Models without `-chat` in their names do not serve for chatting. In fact, the base models are usually for finetuning. It is totally trained by next token prediction on large-scale corpus and thus it has no idea when to stop even in a dialog setting. Instead, for chat models, they have been trained with special tokens like `<|im_end|>` (id 151645) indicating the end of a turn in a dialog and they know how to stop if you have set the eos token right.
