### ISSUE TITLE
DATA="path_to_data",请问数据集在哪下载？

### ISSUE THREAD

**Issue by zhanghaobucunzai** [QwenLM/Qwen1.5#272]
torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \

**Comment by zhanghaobucunzai** [comment]
有可以直接下载的jsonl文件吗

**Comment by JustinLin610** [comment]
no. just organize the data yourself following the doc.
