### ISSUE TITLE
疑问: 为什么我的 72b, 回复的速度很慢呢.

### ISSUE THREAD

**Issue by Dssssds** [QwenLM/Qwen1.5#276]
![image](https://github.com/QwenLM/Qwen1.5/assets/17268259/2c2fd1e2-4747-4aaa-baa8-6c9eda7709df)

![image](https://github.com/QwenLM/Qwen1.5/assets/17268259/e6e1a04f-dce4-45e0-b7bd-cc37fdf4f65e)

这个配置应该还不错,但是回复速度超级慢.

**Comment by jklj077** [comment]
Please report your actual speed result. There are results at <https://qwen.readthedocs.io/en/latest/benchmark/hf_infer.html> for reference.

For the model at <https://ollama.com/library/qwen:72b>, the parameters alone take up about 41GB memory, and A10 normally has 24GB GPU Memory, which is far from sufficient. The generation is likely also bounded by device/host I/O.

**Comment by Dssssds** [comment]
Thank you for the reply, I will adjust the configuration.
