### ISSUE TITLE
部署了Qwen1.5-32B-Chat-GPTQ-Int4可以运行，但出现了CUDA extension not installed，推理速度很慢

### ISSUE THREAD

**Issue by qingwu11** [QwenLM/Qwen1.5#277]
![image](https://github.com/QwenLM/Qwen1.5/assets/41281228/1c19d20a-4afa-4c3f-a3c5-7f01d2bf9d21)

**Comment by Dssssds** [comment]
同问.

**Comment by WSR-wsr** [comment]
qwen1时遇到过这个问题
把auto-gptq，optimum换个版本就可以了

**Comment by yihaozuifan** [comment]
确实特点慢，如何解决？

**Comment by yihaozuifan** [comment]
确实特别慢，如何解决？

**Comment by weiminw** [comment]
32B-Chat-AWQ 在A100 40G上跑 回复差不多相同的内容,时间大约是20秒, 14B-Chat-AWQ 在4090 24G上跑, 回复差不多6秒内.

是不是我需要做什么配置才能让32B-Chat-AWQ 推理速度快一些?

**Comment by JustinLin610** [comment]
for the installation of auto-gptq, we advise you to install from source (git clone the repo and run `pip install -e .`) or you will meet "CUDA not installed" issue.

**Comment by zengraoli** [comment]
这是我的requirements.txt内容，你参考下，我跑qwen/Qwen1___5-32B-Chat-GPTQ-Int4速度没问题
`
absl-py==2.0.0
accelerate==0.29.2
addict==2.4.0
aiofiles==23.2.1
aiohttp==3.9.4
aiosignal==1.3.1
aliyun-python-sdk-core==2.15.0
aliyun-python-sdk-kms==2.16.2
altair==5.3.0
annotated-types==0.6.0
anyio==4.2.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.2.0
auto-gptq==0.6.0
Babel==2.14.0
beautifulsoup4==4.12.2
bleach==6.1.0
brotlipy==0.7.0
cachetools==5.3.2
certifi @ file:///croot/certifi_1671487769961/work/certifi
cffi @ file:///croot/cffi_1670423208954/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click==8.1.7
coloredlogs==15.0.1
comm==0.2.1
conda==22.11.1
conda-content-trust @ file:///tmp/abs_5952f1c8-355c-4855-ad2e-538535021ba5h26t22e5/croots/recipe/conda-content-trust_1658126371814/work
conda-package-handling @ file:///croot/conda-package-handling_1666940373510/work
contourpy==1.2.0
crcmod==1.7
cryptography @ file:///croot/cryptography_1665612644927/work
cycler==0.12.1
datasets==2.18.0
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.8
einops==0.7.0
exceptiongroup==1.2.0
executing==2.0.1
fastapi==0.110.1
fastjsonschema==2.19.1
ffmpy==0.3.2
filelock==3.13.1
fonttools==4.47.0
fqdn==1.5.1
frozenlist==1.4.1
fsspec==2023.12.2
gast==0.5.4
gekko==1.1.1
google-auth==2.26.1
google-auth-oauthlib==1.2.0
gradio==3.41.2
gradio_client==0.5.0
grpcio==1.60.0
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
huggingface-hub==0.22.2
humanfriendly==10.0
idna @ file:///croot/idna_1666125576474/work
importlib_metadata==7.1.0
importlib_resources==6.4.0
ipykernel==6.28.0
ipython==8.20.0
ipywidgets==8.1.1
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.2
jmespath==0.10.0
json5==0.9.14
jsonpointer==2.4
jsonschema==4.20.0
jsonschema-specifications==2023.12.1
jupyter-events==0.9.0
jupyter-lsp==2.2.1
jupyter_client==8.6.0
jupyter_core==5.7.1
jupyter_server==2.12.2
jupyter_server_terminals==0.5.1
jupyterlab==4.0.10
jupyterlab-language-pack-zh-CN==4.0.post6
jupyterlab-widgets==3.0.9
jupyterlab_pygments==0.3.0
jupyterlab_server==2.25.2
kiwisolver==1.4.5
latex2mathml==3.77.0
Markdown==3.5.1
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
mdtex2html==1.3.0
mistune==3.0.2
modelscope==1.13.3
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.16
nbclient==0.9.0
nbconvert==7.14.0
nbformat==5.9.2
nest-asyncio==1.5.8
networkx==3.2.1
notebook_shim==0.2.3
numpy==1.26.3
oauthlib==3.2.2
optimum==1.18.1
orjson==3.10.0
oss2==2.18.4
overrides==7.4.0
packaging==23.2
pandas==2.2.2
pandocfilters==1.5.0
parso==0.8.3
peft==0.10.0
pexpect==4.9.0
pillow==10.2.0
platformdirs==4.1.0
pluggy @ file:///tmp/build/80754af9/pluggy_1648024709248/work
prometheus-client==0.19.0
prompt-toolkit==3.0.43
protobuf==4.23.4
psutil==5.9.7
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==15.0.2
pyarrow-hotfix==0.6
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycosat @ file:///croot/pycosat_1666805502580/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pycryptodome==3.20.0
pydantic==2.7.0
pydantic_core==2.18.1
pydub==0.25.1
Pygments==2.17.2
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyparsing==3.1.1
PySocks @ file:///home/builder/ci_310/pysocks_1640793678128/work
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.1
pyzmq==25.1.2
referencing==0.32.1
regex==2023.12.25
requests==2.31.0
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rouge==1.0.1
rpds-py==0.16.2
rsa==4.9
ruamel.yaml @ file:///croot/ruamel.yaml_1666304550667/work
ruamel.yaml.clib @ file:///croot/ruamel.yaml.clib_1666302247304/work
safetensors==0.4.2
scipy==1.13.0
semantic-version==2.10.0
Send2Trash==1.8.2
sentencepiece==0.2.0
simplejson==3.19.2
six @ file:///tmp/build/80754af9/six_1644875935023/work
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.5
stack-data==0.6.3
starlette==0.37.2
supervisor==4.2.5
sympy==1.12
tensorboard==2.15.1
tensorboard-data-server==0.7.2
terminado==0.18.0
tiktoken==0.6.0
tinycss2==1.2.1
tokenizers==0.15.2
tomli==2.0.1
toolz @ file:///croot/toolz_1667464077321/work
torch @ http://download.pytorch.org/whl/cu121/torch-2.1.2%2Bcu121-cp310-cp310-linux_x86_64.whl
torchvision @ http://download.pytorch.org/whl/cu121/torchvision-0.16.2%2Bcu121-cp310-cp310-linux_x86_64.whl
tornado==6.4
tqdm @ file:///opt/conda/conda-bld/tqdm_1664392687731/work
traitlets==5.14.1
transformers==4.37.2
transformers-stream-generator==0.0.4
triton==2.1.0
types-python-dateutil==2.8.19.20240106
typing_extensions==4.9.0
tzdata==2024.1
uri-template==1.3.0
urllib3 @ file:///croot/urllib3_1670526988650/work
uvicorn==0.29.0
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
websockets==11.0.3
Werkzeug==3.0.1
widgetsnbextension==4.0.9
xxhash==3.4.1
yapf==0.40.2
yarl==1.9.4
zipp==3.18.1
`

**Comment by zengraoli** [comment]
> 确实特别慢，如何解决？

这是我的requirements.txt内容，你参考下，我跑qwen/Qwen1___5-32B-Chat-GPTQ-Int4速度没问题
[Uploading requirements.txt…]()

**Comment by YYGe01** [comment]
Qwen1.5-14B-Chat-GPTQ-Int4 实测：transformers==4.38.2  auto-gptq=0.6.0 速度没问题

**Comment by heart18z** [comment]
32B-Chat-AWQ回复慢，vllm4部署，有什么解决办法吗

**Comment by ATP-BME** [comment]
> Qwen1.5-14B-Chat-GPTQ-Int4 实测：transformers==4.38.2 auto-gptq=0.6.0 速度没问题

我也遇到相同的问题，原来的auto-gptq版本为0.7.0，降级为0.6.0后问题解决

**Comment by SongXiaoMao** [comment]
为何不是用AWQ呢 精度要比GPTQ高一丢丢 VLLM部署很容易

**Comment by zengraoli** [comment]
> 为何不是用AWQ呢 精度要比GPTQ高一丢丢 VLLM部署很容易

这个问题你得问问官方了

**Comment by lijiaoyang** [comment]
> > 确实特别慢，如何解决？
> 
> 这是我的requirements.txt内容，你参考下，我跑qwen/Qwen1___5-32B-Chat-GPTQ-Int4速度没问题 [requirements.txt](https://github.com/QwenLM/Qwen1.5/files/14977873/requirements.txt)

感谢！用了你的配置快多了
