### ISSUE TITLE
请问使用TextStreamer推理的时候如何接收到流式生成过程中的值呢？

### ISSUE THREAD

**Issue by controZheng** [QwenLM/Qwen1.5#278]
我按照官方推荐的流式生成代码推理，但是获取不到中间的值，请问有办法获取吗

**Comment by jklj077** [comment]
If you are referring to the code at <https://qwen.readthedocs.io/en/latest/getting_started/quickstart.html>. That piece of code uses the `TextStreamer` class, which prints the results incrementally to **the standard output** and returns only the final results to the caller, which is suitable for console scripts.

I think you need TextIteratorStreamer.
```python
from transformers import TextIteratorStreamer
from threading import Thread

streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, decode_kwargs={"errors": "ignore"})

inputs = tokenizer(tokenizer.apply_chat_template([{"role": "user", "content": "Hello!"}], add_generation_prompt=True, tokenize=False), return_tensors='pt')

# Run the generation in a separate thread, so that we can fetch the generated text in a non-blocking way.
# Only for demo use, you don't need to create a thread in application
thread = Thread(target=model.generate, kwargs={**inputs, "streamer": streamer, "max_new_tokens": 20})
thread.start()

output_text = ""
for incremental_text in streamer:
    output_text += incremental_text
    print(output_text)
```

![image](https://github.com/QwenLM/Qwen1.5/assets/17811943/fa2f4cab-c764-444a-aec5-8d54cda786ed)

**Comment by gg22mm** [comment]
怎么解决重复问题呢？

(mygptback) [root@localhost 千问]# python trains_desc.py
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
----查看聊天历史拼接---： <|im_start|>system
你是个乐于助人的助手<|im_end|>
<|im_start|>user
怀孕前需要到医院哪些常规检查<|im_end|>
<|im_start|>assistant

你好，怀孕前需要到医院做以下检查：1、血常规检查：血常规检查是检查孕妇血常规的常用方法，血常规检查包括血红蛋白、红细胞、白细胞、血小板、血沉、血常规、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、
