### ISSUE TITLE
72b-text-v1.5-q6_K 和 72b-text-v1.5-fp16 哪一个性能更强？

### ISSUE THREAD

**Issue by stan1233** [QwenLM/Qwen1.5#280]
想请教一下，QWEN的72b-text-v1.5-q6_K 和 72b-text-v1.5-fp16 哪一个性能更强？
模型tag中的"_k"和"-q"分别代表什么，例如：
```
72b-chat-v1.5-q3_K_L
```

[72b-chat-v1.5-q3_K_L](https://ollama.com/library/qwen:72b-chat-v1.5-q3_K_L)

**Comment by JustinLin610** [comment]
it is about the quantization, q6 you can regard it as 6 bit quantization, q2 you can regard it as 2 bit quantization. for sure, fp16 / bf16 should perform the best. check maxime's article and learn more about it. https://towardsdatascience.com/quantize-llama-models-with-ggml-and-llama-cpp-3612dfbcc172
