### ISSUE TITLE
Tokenizer size and embedding size mismatch

### ISSUE THREAD

**Issue by lhamax** [QwenLM/Qwen1.5#29]
Hi, what is the correct way to get the vocab size from the tokenizer in HF?

I tried the following:
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen1.5-7B-Chat-GPTQ-Int8")

tokenizer.vocab_size and len(tokenizer) give 151643 and 151646 whereas the model outputs 151936

**Comment by JustinLin610** [comment]
The first one refers to the vocab size without special tokens, while the second includes them. The embedding size is larger with padding tokens due to distributed training in our pretraining stage.

**Comment by lhamax** [comment]
Thanks @JustinLin610! Is there a recommended way of getting the full vocab size (with the special tokens) from the tokenizer?

**Comment by jklj077** [comment]
you could use `len(tokenizer)` and then pad (or not pad) the embedding according to your need.

**Comment by yiakwy-xpu-ml-framework-team** [comment]
> Hi, what is the correct way to get the vocab size from the tokenizer in HF?
> 
> I tried the following: tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen1.5-7B-Chat-GPTQ-Int8")
> 
> tokenizer.vocab_size and len(tokenizer) give 151643 and 151646 whereas the model outputs 151936

You should use --extra-vocabulary-size in megatron. For models < 7b this value is 293, for models >= 14b this value is 421

**Comment by Autumn1998** [comment]
> > Hi, what is the correct way to get the vocab size from the tokenizer in HF?
> > I tried the following: tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen1.5-7B-Chat-GPTQ-Int8")
> > tokenizer.vocab_size and len(tokenizer) give 151643 and 151646 whereas the model outputs 151936
> 
> You should use --extra-vocabulary-size in megatron. For models < 7b this value is 293, for models >= 14b this value is 421

I can find "--extra-vocabulary-size" in megatron,  wihch megatron did you mean?

**Comment by fazhdo** [comment]
> you could use `len(tokenizer)` and then pad (or not pad) the embedding according to your need.

Hi, I'm using QwenVL recently. I also noticed the problem that len(tokenizer) and lm_head output dimensions do not match. So if I introduce additional special tokens, do I only need to retrain lm_head and embedding, or continue to increase their output or input dimensions before retrain?
