### ISSUE TITLE
补充一个32B的生成速度测试

### ISSUE THREAD

**Issue by Lu0Key** [QwenLM/Qwen1.5#291]
使用[QWEN](https://github.com/QwenLM/Qwen)项目中提供的profile.py 代码
Model | Num. GPU | Input Length | Speed | Memory
-- | -- | -- | -- | --
Qwen1.5-32B-Chat | 1 | 1 |16.51| 62.70
Qwen1.5-32B-Chat | 1 | 6144 |12.65| 68.44
Qwen1.5-32B-Chat | 1 | 14336 |9.02| 77.48
Qwen1.5-32B-Chat | 2 | 30720|5.54|117.19

GPU 为 A100-SXM4-80GB

**Comment by JustinLin610** [comment]
Similar to our test. We'll double check and update the statistics to the Doc.
