### ISSUE TITLE
如何本地起服务，然后调服务？

### ISSUE THREAD

**Issue by Hzzhang-nlp** [QwenLM/Qwen1.5#294]
怎么去本地部署一个模型，然后起API，再去调这个API

**Comment by jklj077** [comment]
Have you read the README?

For commodity hardware
- https://github.com/QwenLM/Qwen1.5?tab=readme-ov-file#-run-locally

For workstation- or server-level or enterprise hardware
- https://github.com/QwenLM/Qwen1.5?tab=readme-ov-file#deployment
