### ISSUE TITLE
vllm  部署 Qwen1.5-7B-Chat  出错 KV cache 怎么是7344呢？

### ISSUE THREAD

**Issue by cqray1990** [QwenLM/Qwen1.5#295]
python -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-7B-Chat --model  /models--Qwen--Qwen1.5-7B-Chat

 raise ValueError(
ValueError: The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (7344). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.

**Comment by jklj077** [comment]
vllm adopts efficient management of attention key and value memory with PagedAttention, that is, the so-called KV cache. The size of the KV cache is computed online based on the model architecture and the available GPU memory.

The errors means that the token sequences (32768 tokens) are too long for your GPU devices to accommodate. You could increae the gpu_memory_utilization to increase the size of the KV cache (but risking OOM) or decreasing the max_model_len. For example,
```
python -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-7B-Chat --model /models--Qwen--Qwen1.5-7B-Chat --max_model_len 7200
```
