### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by gw00297020** [QwenLM/Qwen1.5#297]
问题概述：用官方提供代码lora微调qwen1.5-14B后，合并权重并保存，发现合并后权重较之前增大了2倍，（目前怀疑是bf16精度变成了fp32），但不知道为什么会这样以及如何解决

用官方github上的finetune.sh的脚本进行的微调，即：
`bash finetune.sh -m /root/work/model/Qwen1.5-14B/ -d new_data.jsonl --deepspeed ds_config_zero3.json --use_lora True | tee log.txt
`
合并lora权重的代码为：
```
from peft import AutoPeftModelForCausalLM
import os
dir = '/root/work/code/Qwen1.5/examples/sft/new_model_qw32b_checkpoint-40'
os.mkdir(dir)
model = AutoPeftModelForCausalLM.from_pretrained(
    '/root/work/code/Qwen1.5/examples/sft/output_qwen_100_2/checkpoint-40', 
    device_map='auto',
    trust_remote_code=True
).eval()

merged_model = model.merge_and_unload()
merged_model.save_pretrained(dir, max_shard_size="4096MB", `safe_serialization=True)
```
合并后的权重大小为：
```
total 55324424
drwxr-xr-x  2 root root       8192 Apr  8 16:02 ./
drwxr-xr-x 14 root root      12288 Apr 11 17:06 ../
-rw-r--r--  1 root root        714 Apr  9 17:27 config.json
-rw-r--r--  1 root root        117 Apr  8 15:59 generation_config.json
-rw-r--r--  1 root root 4086191240 Apr  8 15:59 model-00001-of-00015.safetensors
-rw-r--r--  1 root root 4063584600 Apr  8 16:00 model-00002-of-00015.safetensors
-rw-r--r--  1 root root 3992805824 Apr  8 16:00 model-00003-of-00015.safetensors
-rw-r--r--  1 root root 3992785232 Apr  8 16:00 model-00004-of-00015.safetensors
-rw-r--r--  1 root root 4063543448 Apr  8 16:00 model-00005-of-00015.safetensors
-rw-r--r--  1 root root 4063543440 Apr  8 16:00 model-00006-of-00015.safetensors
-rw-r--r--  1 root root 4063584640 Apr  8 16:00 model-00007-of-00015.safetensors
-rw-r--r--  1 root root 3992805864 Apr  8 16:01 model-00008-of-00015.safetensors
-rw-r--r--  1 root root 3992785272 Apr  8 16:01 model-00009-of-00015.safetensors
-rw-r--r--  1 root root 4063543448 Apr  8 16:01 model-00010-of-00015.safetensors
-rw-r--r--  1 root root 4063543440 Apr  8 16:01 model-00011-of-00015.safetensors
-rw-r--r--  1 root root 4063584640 Apr  8 16:01 model-00012-of-00015.safetensors
-rw-r--r--  1 root root 3992805864 Apr  8 16:01 model-00013-of-00015.safetensors
-rw-r--r--  1 root root 1051280384 Apr  8 16:01 model-00014-of-00015.safetensors
-rw-r--r--  1 root root 3105710208 Apr  8 16:02 model-00015-of-00015.safetensors
-rw-r--r--  1 root root      39584 Apr  8 16:02 model.safetensors.index.json
```

**Comment by jklj077** [comment]
Please first try passing `torch_dtype="auto"` to `AutoPeftModelForCausalLM.from_pretrained`.

**Comment by gw00297020** [comment]
> Please first try passing `torch_dtype="auto"` to `AutoPeftModelForCausalLM.from_pretrained`.

您好，我按照上面更改了代码，发现代码运行不了了，怀疑是远端代码更新所致，我尝试了重新运行微调脚本生成新adapter权重，再运行合并权重的代码：
```
from peft import AutoPeftModelForCausalLM
import os
dir = '/root/work/code/Qwen1.5/examples/sft/new_model_qw32b_checkpoint-40'
os.mkdir(dir)
model = AutoPeftModelForCausalLM.from_pretrained(
    '/root/work/code/Qwen1.5/examples/sft/output_qwen_100_2/checkpoint-40', 
    device_map='auto',
    trust_remote_code=True,
    torch_dtype="auto"
).eval()

merged_model = model.merge_and_unload()
merged_model.save_pretrained(dir, max_shard_size="4096MB", `safe_serialization=True)
```
报错如下：
```
(qwen1.5) (base) root@ks-120-76f858b95d-gv8zd:~/work/code/Qwen1.5/examples/sft# /opt/conda/envs/qwen1.5/bin/python /root/work/code/Qwen1.5/examples/sft/merge_model.py
/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/accelerate/utils/modeling.py:1363: UserWarning: Current model requires 268437504 bytes of buffer for offloaded layers, which seems does not fit any GPU's remaining memory. If you are experiencing a OOM later, please consider using offload_buffers=True.
  warnings.warn(
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:01<00:00,  7.69s/it]
WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/accelerate/utils/modeling.py:1363: UserWarning: Current model requires 1342187520 bytes of buffer for offloaded layers, which seems does not fit any GPU's remaining memory. If you are experiencing a OOM later, please consider using offload_buffers=True.
  warnings.warn(
Traceback (most recent call last):
  File "/root/work/code/Qwen1.5/examples/sft/merge_model.py", line 7, in <module>
    model = AutoPeftModelForCausalLM.from_pretrained(
  File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/peft/auto.py", line 128, in from_pretrained
    return cls._target_peft_class.from_pretrained(
  File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/peft/peft_model.py", line 353, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/peft/peft_model.py", line 727, in load_adapter
    dispatch_model(
  File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/accelerate/big_modeling.py", line 488, in dispatch_model
    model.to(device)
  File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```
期待您的回答

**Comment by GXKIM** [comment]
> > Please first try passing `torch_dtype="auto"` to `AutoPeftModelForCausalLM.from_pretrained`.
> 
> 您好，我按照上面更改了代码，发现代码运行不了了，怀疑是远端代码更新所致，我尝试了重新运行微调脚本生成新adapter权重，再运行合并权重的代码：
> 
> ```
> from peft import AutoPeftModelForCausalLM
> import os
> dir = '/root/work/code/Qwen1.5/examples/sft/new_model_qw32b_checkpoint-40'
> os.mkdir(dir)
> model = AutoPeftModelForCausalLM.from_pretrained(
>     '/root/work/code/Qwen1.5/examples/sft/output_qwen_100_2/checkpoint-40', 
>     device_map='auto',
>     trust_remote_code=True,
>     torch_dtype="auto",
>     offload_folder='/root/work/code/Qwen1.5/examples/sft/output/checkpoint-10'
> ).eval()
> 
> merged_model = model.merge_and_unload()
> merged_model.save_pretrained(dir, max_shard_size="4096MB", `safe_serialization=True)
> ```
> 
> 报错如下：
> 
> ```
> (qwen1.5) (base) root@ks-120-76f858b95d-gv8zd:~/work/code/Qwen1.5/examples/sft# /opt/conda/envs/qwen1.5/bin/python /root/work/code/Qwen1.5/examples/sft/merge_model.py
> /opt/conda/envs/qwen1.5/lib/python3.9/site-packages/accelerate/utils/modeling.py:1363: UserWarning: Current model requires 268437504 bytes of buffer for offloaded layers, which seems does not fit any GPU's remaining memory. If you are experiencing a OOM later, please consider using offload_buffers=True.
>   warnings.warn(
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:01<00:00,  7.69s/it]
> WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu.
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> /opt/conda/envs/qwen1.5/lib/python3.9/site-packages/accelerate/utils/modeling.py:1363: UserWarning: Current model requires 1342187520 bytes of buffer for offloaded layers, which seems does not fit any GPU's remaining memory. If you are experiencing a OOM later, please consider using offload_buffers=True.
>   warnings.warn(
> Traceback (most recent call last):
>   File "/root/work/code/Qwen1.5/examples/sft/merge_model.py", line 7, in <module>
>     model = AutoPeftModelForCausalLM.from_pretrained(
>   File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/peft/auto.py", line 128, in from_pretrained
>     return cls._target_peft_class.from_pretrained(
>   File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/peft/peft_model.py", line 353, in from_pretrained
>     model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
>   File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/peft/peft_model.py", line 727, in load_adapter
>     dispatch_model(
>   File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/accelerate/big_modeling.py", line 488, in dispatch_model
>     model.to(device)
>   File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1152, in to
>     return self._apply(convert)
>   File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
>     module._apply(fn)
>   File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
>     module._apply(fn)
>   File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 802, in _apply
>     module._apply(fn)
>   File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 825, in _apply
>     param_applied = fn(param)
>   File "/opt/conda/envs/qwen1.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1150, in convert
>     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
> NotImplementedError: Cannot copy out of meta tensor; no data!
> ```
> 
> 期待您的回答

请问解决了吗

**Comment by gw00297020** [comment]
@GXKIM 解决了，就是用那段代码成功运行了，torch_type和offload_folder同时指定
