### ISSUE TITLE
docker镜像麻烦跟进更新一下谢谢

### ISSUE THREAD

**Issue by Past-Tang** [QwenLM/Qwen1.5#3]
docker镜像麻烦跟进更新一下谢谢

**Comment by sisuad** [comment]
今天xinference会马上发版支持，到时候可以关注一下。 [xinference github](https://github.com/xorbitsai/inference/blob/main/README_zh_CN.md)

**Comment by Past-Tang** [comment]
> 今天xinference会马上发版支持，到时候可以关注一下。 [xinference github](https://github.com/xorbitsai/inference/blob/main/README_zh_CN.md)

好的已经看到 感谢qwen团队
