### ISSUE TITLE
KeyError: 'qwen2'  Successfully installed transformers-4.37.2 vllm

### ISSUE THREAD

**Issue by sparkfax** [QwenLM/Qwen1.5#30]
use modelscope jupiter:
!pip install modelscope
import os
os.environ['VLLM_USE_MODELSCOPE'] = 'True'
!pip install vllm
!pip install --upgrade transformers==4.37.2
----- 
      ms-swift 1.5.1 requires transformers<4.37,>=4.33, but you have transformers 4.37.2 which is incompatible.
      Successfully installed transformers-4.37.2
-----
from vllm import LLM
llm = LLM(model="Qwen/Qwen1.5-0.5B",trust_remote_code=True,gpu_memory_utilization=0.95)  # Create an LLM.
prompts='叶文杰在三体里的角色'
outputs = llm.generate(prompts) 
-------------
qwen model has downloaded from modelscope,then get following error:
-------------
KeyError                                  Traceback (most recent call last)
Cell In[21], line 2
      1 from vllm import LLM
----> 2 llm = LLM(model="Qwen/Qwen1.5-0.5B",trust_remote_code=True,gpu_memory_utilization=0.95)  # Create an LLM.
      3 prompts='叶文杰在三体里的角色'
      4 outputs = llm.generate(prompts)  # Generate texts from the prompts.

File /opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py:105, in LLM.__init__(self, model, tokenizer, tokenizer_mode, trust_remote_code, tensor_parallel_size, dtype, quantization, revision, tokenizer_revision, seed, gpu_memory_utilization, swap_space, enforce_eager, max_context_len_to_capture, **kwargs)
     87     kwargs["disable_log_stats"] = True
     88 engine_args = EngineArgs(
     89     model=model,
     90     tokenizer=tokenizer,
   (...)
    103     **kwargs,
    104 )
--> 105 self.llm_engine = LLMEngine.from_engine_args(engine_args)
    106 self.request_counter = Counter()

File /opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py:304, in LLMEngine.from_engine_args(cls, engine_args)
    302 """Creates an LLM engine from the engine arguments."""
    303 # Create the engine configs.
--> 304 engine_configs = engine_args.create_engine_configs()
    305 parallel_config = engine_configs[2]
    306 # Initialize the cluster.

File /opt/conda/lib/python3.10/site-packages/vllm/engine/arg_utils.py:218, in EngineArgs.create_engine_configs(self)
    215 def create_engine_configs(
    216     self,
    217 ) -> Tuple[ModelConfig, CacheConfig, ParallelConfig, SchedulerConfig]:
--> 218     model_config = ModelConfig(self.model, self.tokenizer,
    219                                self.tokenizer_mode, self.trust_remote_code,
    220                                self.download_dir, self.load_format,
    221                                self.dtype, self.seed, self.revision,
    222                                self.tokenizer_revision, self.max_model_len,
    223                                self.quantization, self.enforce_eager,
    224                                self.max_context_len_to_capture)
    225     cache_config = CacheConfig(self.block_size,
    226                                self.gpu_memory_utilization,
    227                                self.swap_space,
    228                                model_config.get_sliding_window())
    229     parallel_config = ParallelConfig(self.pipeline_parallel_size,
    230                                      self.tensor_parallel_size,
    231                                      self.worker_use_ray,
    232                                      self.max_parallel_loading_workers)

File /opt/conda/lib/python3.10/site-packages/vllm/config.py:101, in ModelConfig.__init__(self, model, tokenizer, tokenizer_mode, trust_remote_code, download_dir, load_format, dtype, seed, revision, tokenizer_revision, max_model_len, quantization, enforce_eager, max_context_len_to_capture)
     98     self.download_dir = model_path
     99     self.tokenizer = model_path
--> 101 self.hf_config = get_config(self.model, trust_remote_code, revision)
    102 self.dtype = _get_and_verify_dtype(self.hf_config, dtype)
    103 self.max_model_len = _get_and_verify_max_len(self.hf_config,
    104                                              max_model_len)

File /opt/conda/lib/python3.10/site-packages/vllm/transformers_utils/config.py:23, in get_config(model, trust_remote_code, revision)
     19 def get_config(model: str,
     20                trust_remote_code: bool,
     21                revision: Optional[str] = None) -> PretrainedConfig:
     22     try:
---> 23         config = AutoConfig.from_pretrained(
     24             model, trust_remote_code=trust_remote_code, revision=revision)
     25     except ValueError as e:
     26         if (not trust_remote_code and
     27                 "requires you to execute the configuration file" in str(e)):

File /opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1098, in AutoConfig.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
   1096     return config_class.from_pretrained(pretrained_model_name_or_path, **kwargs)
   1097 elif "model_type" in config_dict:
-> 1098     config_class = CONFIG_MAPPING[config_dict["model_type"]]
   1099     return config_class.from_dict(config_dict, **unused_kwargs)
   1100 else:
   1101     # Fallback: use pattern matching on the string.
   1102     # We go from longer names to shorter names to catch roberta before bert (for instance)

File /opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:795, in _LazyConfigMapping.__getitem__(self, key)
    793     return self._extra_content[key]
    794 if key not in self._mapping:
--> 795     raise KeyError(key)
    796 value = self._mapping[key]
    797 module_name = model_type_to_module_name(key)

KeyError: 'qwen2'

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 12.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10          On   | 00000000:00:07.0 Off |                    0 |
|  0%   30C    P8    16W / 150W |      0MiB / 22731MiB |      0%      Default |

**Comment by carpe1** [comment]
The code of Qwen1.5 has been in the latest Hugging face transformers and we advise you to install transformers>=4.37.0, or you might encounter the following error:  
KeyError: 'qwen2'
**You can solve it by upgrading 'transformers'
`pip uninstall transformers
pip install --upgrade transformers==4.37.0
`**

**Comment by carpe1** [comment]
The code of Qwen1.5 has been in the latest Hugging face transformers and we advise you to install transformers>=4.37.0, or you might encounter the following error:  
KeyError: 'qwen2'
**You can solve it by upgrading 'transformers'
`pip uninstall transformers

pip install --upgrade transformers==4.37.0
`**

**Comment by carpe1** [comment]
The code of Qwen1.5 has been in the latest Hugging face transformers and we advise you to install transformers>=4.37.0, or you might encounter the following error:  
KeyError: 'qwen2'
**You can solve it by upgrading 'transformers'**
```
pip uninstall transformers
pip install --upgrade transformers==4.37.0
