### ISSUE TITLE
qwen 1.5 72B以及qwen 72B分别是否可以商用（高月活），以及怎么将qwen 72B的ckpt转为qwen 1.5 72B？

### ISSUE THREAD

**Issue by wuyaoxuehun** [QwenLM/Qwen1.5#303]
qwen 1.5 72B以及qwen 72B分别是否可以商用（高月活），以及怎么将qwen 72B的ckpt转为qwen 1.5 72B 的ckpt？

**Comment by JustinLin610** [comment]
follow the license in the hf repo. if your mau is higher than 100 million, you need to contact us. if no, no worries. 

transformation is simple, just some name changing and mixed qkv needs to be split into q, k, v.

**Comment by wuyaoxuehun** [comment]
> follow the license in the hf repo. if your mau is higher than 100 million, you need to contact us. if no, no worries.
> 
> transformation is simple, just some name changing and mixed qkv needs to be split into q, k, v.

我看不到Qwen/Qwen1.5-72B-Chat的hf repo有关于license的事情，是不是需要给你们官方邮箱发邮件呀？
![image](https://github.com/QwenLM/Qwen1.5/assets/26178145/b0b720d5-ae8d-447b-a1cc-9e5e4d98e276)
