### ISSUE TITLE
提示词模板格式是什么，如何避免生成结果混乱？

### ISSUE THREAD

**Issue by linonetwo** [QwenLM/Qwen1.5#304]
![图片](https://github.com/QwenLM/Qwen1.5/assets/3746270/aa4549e2-395d-460d-96a9-f29da006fc71)

我目前使用这样的模板

```js
template: '{{systemPrompt}}\n{{history}}model:{{completion}}\nuser:',
```

结果生成结果非常不好，请问 qwen1.5 gguf 需要使用什么样的提示词模板呢，文档里暂时没看到，是否有 Jinja 模板可以参考？例如

```js
template: '<|im_start|>system\n{{systemPrompt}}<|im_end|>\n{{history}}<|im_start|>model:{{completion}}<|im_end|>\nuser:',
```

**Comment by linonetwo** [comment]
use https://github.com/chujiezheng/chat_templates/blob/main/chat_templates/openchat.jinja (which is said to compatable with qwen1.5 https://github.com/chujiezheng/chat_templates/blob/main/generation_configs/qwen2-chat.json ) ???

**Comment by jklj077** [comment]
The chat template is embedded in the official GGUF files. They are also provided in tokenizer.json as the standard practice in `transformers`. For example, <https://huggingface.co/Qwen/Qwen1.5-72B-Chat/blob/main/tokenizer_config.json#L31>.

**Comment by linonetwo** [comment]
I'm using llama.cpp https://github.com/withcatai/node-llama-cpp , how to use the embedding template?

> chat template is embedded in the official GGUF files.

**Comment by jklj077** [comment]
If you're not using `llama.cpp` but `node-llama-cpp`, it is most likely a problem of `node-llama-cpp`. Please report to them.
