### ISSUE TITLE
[BUG] <Qwen tokenizer不支持sp_model加载吗？>

### ISSUE THREAD

**Issue by hwb96** [QwenLM/Qwen1.5#316]
### 当前行为 | Current Behavior

准备将本地词表合并到Qwen的词表，但是发现Qwen tokenizer无论是fast还是普通的use_fast=False，也就是[tokenization_qwen2.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/qwen2/tokenization_qwen2.py)和[tokenization_qwen2_fast.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/qwen2/tokenization_qwen2_fast.py)，均不支持“sp_model”，导入报错：
1.AttributeError: 'Qwen2Tokenizer' object has no attribute 'sp_model'
2.AttributeError: 'Qwen2TokenizerFast' object has no attribute 'sp_model'

代码：
```Python
import json
import os
from transformers import LlamaTokenizer, AutoTokenizer
from sentencepiece import sentencepiece_model_pb2 as sp_pb2_model
import sentencepiece as spm

qwen_tokenizer_dir = '/project/qwen/model/Qwen1.5-7B-Chat'
qwen_tokenizer = AutoTokenizer.from_pretrained(qwen_tokenizer_dir,use_fast=False)
qwen_spm = sp_pb2_model.ModelProto()
qwen_spm.ParseFromString(qwen_tokenizer.sp_model.serialized_model_proto())
```
运行报错：
AttributeError: 'Qwen2Tokenizer' object has no attribute 'sp_model'

改成
```Python
qwen_spm.ParseFromString(qwen_tokenizer.tokenizer.sp_model.serialized_model_proto())
```
依然运行报错：
AttributeError: 'Qwen2Tokenizer' object has no attribute 'sp_model'

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python:3.10.14
- Transformers:4.39.2
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.2
```

**Comment by hwb96** [comment]
感谢您的回复。Thank you for your response.

1. 我平时做工程比较多，对于很多底层细节不甚了解。我可以这样理解吗：尽管SentencePiece确实支持BPE，但是Qwen团队选择自行实现BPE过程，而不是依赖于SentencePiece库提供的实现方式，所以加载SentencePiece模型并不适用。如果我想了解更多细节，查看GPT2Tokenizer的构建过程对我会很有帮助。Because I usually work more on engineering, I'm not very familiar with many of the underlying details. Can I understand it this way: Although SentencePiece does support BPE, the Qwen team chose to implement the BPE process on their own, rather than relying on the implementation provided by the SentencePiece library, so loading a SentencePiece model is not applicable. If I want to learn more details, looking into the construction process of the GPT2Tokenizer would be very helpful for me.
2. 谢谢你的建议，我会尝试着使用tokenizer.add_tokens()来扩展词汇，并学习pretokenization and BPE tokenization的不同。Thank you for your suggestion. I will use tokenizer.add_tokens() to expand the vocabulary and learn about the differences between pretokenization and BPE tokenization.

**Comment by hwb96** [comment]
> 1. Please do not mix the use of Qwen1 and Qwen1.5 code due to their inherent incompatibilities. Note that any coding sections pertaining to tokenization_note for Qwen1 are also outdated for Qwen1.5.
> 2. Except for the recently introduced CodeQwen, the tokenizer in Qwen models is not built upon `sentencepiece`; rather, it employs traditional BPE at the byte-level similar to GPT models, hence loading a `sentencepiece` model is not applicable.
> 3. Qwen1.5 adhere to the `transformers` framework's practices and follows the implemenation of `GPT2Tokenizer`: the token in the `bytes` type are encoded using a byte encoder to `str`, which is what you see after the `tokenize` call,. This is soley an artefact of the `transformers` implementation.
> 4. Vocabulary expansion can take place at two stages: pretokenization and BPE tokenization. The former is easy to implement and `transformers` supports that by [`tokenizer.add_tokens()`](https://huggingface.co/docs/transformers/internal/tokenization_utils#transformers.SpecialTokensMixin.add_tokens). The added tokens has higher priority than the BPE tokenization. The latter requires continual learning of the BPE merges, the idea of which is illustrated in the tokenization_note. The `tokenizers` library can support the training of the merges.
> 5. It seems more practical for you to leverage `tokenizer.add_tokens()` for vocabulary expansion given its ease of use.

感谢您的回复。Thank you for your response.

我平时做工程比较多，对于很多底层细节不甚了解。我可以这样理解吗：尽管SentencePiece确实支持BPE，但是Qwen团队选择自行实现BPE过程，而不是依赖于SentencePiece库提供的实现方式，所以加载SentencePiece模型并不适用。如果我想了解更多细节，查看GPT2Tokenizer的构建过程对我会很有帮助。Because I usually work more on engineering, I'm not very familiar with many of the underlying details. Can I understand it this way: Although SentencePiece does support BPE, the Qwen team chose to implement the BPE process on their own, rather than relying on the implementation provided by the SentencePiece library, so loading a SentencePiece model is not applicable. If I want to learn more details, looking into the construction process of the GPT2Tokenizer would be very helpful for me.
谢谢你的建议，我会尝试着使用tokenizer.add_tokens()来扩展词汇，并学习pretokenization and BPE tokenization的不同。Thank you for your suggestion. I will use tokenizer.add_tokens() to expand the vocabulary and learn about the differences between pretokenization and BPE tokenization.

**Comment by hwb96** [comment]
> 1. Please do not mix the use of Qwen1 and Qwen1.5 code due to their inherent incompatibilities. Note that any coding sections pertaining to tokenization_note for Qwen1 are also outdated for Qwen1.5.
> 2. Except for the recently introduced CodeQwen, the tokenizer in Qwen models is not built upon `sentencepiece`; rather, it employs traditional BPE at the byte-level similar to GPT models, hence loading a `sentencepiece` model is not applicable.
> 3. Qwen1.5 adhere to the `transformers` framework's practices and follows the implemenation of `GPT2Tokenizer`: the token in the `bytes` type are encoded using a byte encoder to `str`, which is what you see after the `tokenize` call,. This is soley an artefact of the `transformers` implementation.
> 4. Vocabulary expansion can take place at two stages: pretokenization and BPE tokenization. The former is easy to implement and `transformers` supports that by [`tokenizer.add_tokens()`](https://huggingface.co/docs/transformers/internal/tokenization_utils#transformers.SpecialTokensMixin.add_tokens). The added tokens has higher priority than the BPE tokenization. The latter requires continual learning of the BPE merges, the idea of which is illustrated in the tokenization_note. The `tokenizers` library can support the training of the merges.
> 5. It seems more practical for you to leverage `tokenizer.add_tokens()` for vocabulary expansion given its ease of use.

感谢您的回复。Thank you for your response.

1. 我平时做工程比较多，对于很多底层细节不甚了解。我可以这样理解吗：尽管SentencePiece确实支持BPE，但是Qwen团队选择自行实现BPE过程，而不是依赖于SentencePiece库提供的实现方式，所以加载SentencePiece模型并不适用。如果我想了解更多细节，查看GPT2Tokenizer的构建过程对我会很有帮助。Because I usually work more on engineering, I'm not very familiar with many of the underlying details. Can I understand it this way: Although SentencePiece does support BPE, the Qwen team chose to implement the BPE process on their own, rather than relying on the implementation provided by the SentencePiece library, so loading a SentencePiece model is not applicable. If I want to learn more details, looking into the construction process of the GPT2Tokenizer would be very helpful for me.

2.谢谢你的建议，我会尝试着使用tokenizer.add_tokens()来扩展词汇，并学习pretokenization and BPE tokenization的不同。Thank you for your suggestion. I will use tokenizer.add_tokens() to expand the vocabulary and learn about the differences between pretokenization and BPE tokenization.

**Comment by hwb96** [comment]
> 1. Please do not mix the use of Qwen1 and Qwen1.5 code due to their inherent incompatibilities. Note that any coding sections pertaining to tokenization_note for Qwen1 are also outdated for Qwen1.5.
> 2. Except for the recently introduced CodeQwen, the tokenizer in Qwen models is not built upon `sentencepiece`; rather, it employs traditional BPE at the byte-level similar to GPT models, hence loading a `sentencepiece` model is not applicable.
> 3. Qwen1.5 adhere to the `transformers` framework's practices and follows the implemenation of `GPT2Tokenizer`: the token in the `bytes` type are encoded using a byte encoder to `str`, which is what you see after the `tokenize` call,. This is soley an artefact of the `transformers` implementation.
> 4. Vocabulary expansion can take place at two stages: pretokenization and BPE tokenization. The former is easy to implement and `transformers` supports that by [`tokenizer.add_tokens()`](https://huggingface.co/docs/transformers/internal/tokenization_utils#transformers.SpecialTokensMixin.add_tokens). The added tokens has higher priority than the BPE tokenization. The latter requires continual learning of the BPE merges, the idea of which is illustrated in the tokenization_note. The `tokenizers` library can support the training of the merges.
> 5. It seems more practical for you to leverage `tokenizer.add_tokens()` for vocabulary expansion given its ease of use.

感谢您的回复。Thank you for your response.

我平时做工程比较多，对于很多底层细节不甚了解。我可以这样理解吗：尽管SentencePiece确实支持BPE，但是Qwen团队选择自行实现BPE过程，而不是依赖于SentencePiece库提供的实现方式，所以加载SentencePiece模型并不适用。如果我想了解更多细节，查看GPT2Tokenizer的构建过程对我会很有帮助。Because I usually work more on engineering, I'm not very familiar with many of the underlying details. Can I understand it this way: Although SentencePiece does support BPE, the Qwen team chose to implement the BPE process on their own, rather than relying on the implementation provided by the SentencePiece library, so loading a SentencePiece model is not applicable. If I want to learn more details, looking into the construction process of the GPT2Tokenizer would be very helpful for me.

谢谢你的建议，我会尝试着使用tokenizer.add_tokens()来扩展词汇，并学习pretokenization and BPE tokenization的不同。Thank you for your suggestion. I will use tokenizer.add_tokens() to expand the vocabulary and learn about the differences between pretokenization and BPE tokenization.

**Comment by jklj077** [comment]
The core algorithm of BPE similar but the implmentation details are quite different between GPT or tiktoken (BPE at the byte-level or `tiktoken`) and sentencepiece (BPE at the char-level with byte fallback). It is mentioned in tokenization_note.

`sentencepiece` operates on Unicode code points or chars, not on UTF-8 encoded bytes. For example, `"你好"` is two chars but 6 bytes (`b"\xe4\xbd\xa0\xe5\xa5\xbd"`). If `"你好"` is a token, `sentencepiece` needs one merge `("你", "好")`, while BPE at the byte level needs 5 merges `(b"\xe4", b"\xbd"), (b"\xe4\xbd", b"\xa0"), (b"\xe5", b"\xa5"), (b"\xe5\xa5", "\xbd"), (b"\xe4\xbd\xa0", "\xe5\xa5\xbd")`.

The thing is that there are near 150K Unicode code points but there are only 256 possible bytes. To achieve full coverage of the vocabulary, it is unrealistic for sentencepiece to add all code points as tokens to the vocabulary, so it adopts the byte fallback trick: if a codepoint is not a token in the vocabulary, `sentencepiece` with byte fallback tokenizes it as bytes. For example, suppose `"佰"` (`b"\xe4\xbd\xb0"`) is not in the previous vocabulary, sentencepiece produces the sequence `("<0xE4>", "<0xBD>", "<0xB0>")`, while BPE at the byte level produces the sequence `(b"\xe4\xbd", b"\xb0")`.

They are both BPE, but they are different BPE.

**Comment by YueWen1024** [comment]
您好，我有个疑问，在Qwen2的词表tokenizer.json文件中，存储的token直接是一个字符串，而不是类似b''这种二进制形式，请问他们是经过了什么处理呢？
![image](https://github.com/user-attachments/assets/a36ddee3-60f8-4bd9-bfa1-db25fc9bc68b)

**Comment by SylvanLiu** [comment]
在Byte-level BPE tokenizer 中，tokens 是字节级的，需要通过 decode 还原成原始的字符串。

`from transformers import PreTrainedTokenizerFast

fast_tokenizer = PreTrainedTokenizerFast(tokenizer_file="/home/sylvanl/Desktop/AILab/LLaMA-Factory/saves/Qwen2-7B/full/train_2024-09-17-19-09-04/tokenizer.json")
vocab_size = fast_tokenizer.vocab_size
token_dict = {token_id: fast_tokenizer.decode([token_id]) for token_id in range(vocab_size)}
for token_id, token_content in list(token_dict.items())[-100:]:
    print(f"{token_id}: {token_content}")
`

`151543: 겙
151544: 겴
151545: 곂
151546: 롼
151547: 솊
151548: 켇
151549: 틍
151550: 퓬
151551: 퓮
151552: 퓶
151553: 퓻
151554: 臘
151555: 怒
151556: 辰
151557: ﭲ
151558: 𐭊
151559: 𐱅
151560: �
151561: 𖥨
151562: 𝑳
151563: 𝓕
151564: 𝓬
151565: 𝓹
151566: 𝓾
151567: 𝔓
151568: 𝕍
151569: 𝕡
151570: 𝕱
151571: 𝖖
151572: 𝘏
151573: 𝘐
151574: 𝘚
151575: 𝙮
151576: 𝙰
151577: 𝙸
151578: 𝙺
151579: 𝙼
151580: 𝙽
151581: 𝙿
151582: 𝚄
151583: 𝚏
151584: 🅅
151585: 🅓
151586: ƈ
151587: ࠌ
151588: ᙳ
151589: ᚌ
151590: ᛅ
151591: ᛐ
151592: ᤊ
151593: Ḋ
151594: ┽
151595: ╊
151596: ⛇
151597: ⛏
151598: ❪
151599: ❫
151600: ⟰
151601: ㄍ
151602: ㄓ
151603: ㄧ
151604: ㅖ
151605: ㉫
151606: ꦔ
151607: ﱊ
151608: ຂ
151609: ᅣ
151610: ᥔ
151611: ᥤ
151612: ↤
151613: ↷
151614: ⇞
151615: ▤
151616: ➶
151617: ㈼
151618: 嘆
151619: 𓏧
151620: ┲
151621: ‴
151622: ⒟
151623: ⒡
151624: Ⰲ
151625: Ⰽ
151626: Ⰾ
151627: Ⱀ
151628: Ⱁ
151629: Ⱏ
151630: Ⱐ
151631: Ⱑ
151632: ⼭
151633: ㊥
151634: ⒠
151635: ⽺
151636: ㇺ
151637: ㇽ
151638: 見
151639: ᕷ
151640: ⍨
151641: ⺟
151642: ⽗
`
