### ISSUE TITLE
Qwen1.5-cu121的docker环境中pydantic与deepspeed冲突

### ISSUE THREAD

**Issue by 5456es** [QwenLM/Qwen1.5#321]
我在Qwen1.5-cu121的docker中，执行“import deepspeed”时出现以下报错

> `
> pydantic.errors.PydanticUserError: If you use @root_validator with pre=False (the default) you MUST specify skip_on_failure=True. Note that @root_validator is deprecated and should be replaced with @mo
> del_validator.
> `

我在尝试了 pip install pydantic==1.9.0 后 import deepspeed正常无报错，但是有以下依赖错误（来自pip)

> `
> ERROR: vllm 0.3.1 has requirement pydantic>=2.0, but you'll have pydantic 1.9.0 which is incompatible.`

>`
> ERROR: gradio 4.21.0 has requirement pydantic>=2.0, but you'll have pydantic 1.9.0 which is incompatible.  `   

我向请教一下这个情况该如何解决，后续使用会有影响吗？

**Comment by 5456es** [comment]
我的需求是用Qwen提供的docker环境来运行Llama-factory对llama2进行微调，我在Qwen1.5-cu121的docker内又调整了一些库最终成功运行（具体是lora/single_node/multiple_gpus）以下是我导出的依赖库，希望对有类似需求的后来者有一定帮助

另：我使用的driver版本较高 535.129.03 , CUDA Version:12.2

> accelerate==0.27.2
> aiofiles==23.2.1
> aiohttp==3.8.6
> aioprometheus==23.12.0
> aiosignal==1.3.1
> altair==5.2.0
> annotated-types==0.6.0
> anyio==4.3.0
> appdirs==1.4.4
> async-timeout==4.0.3
> attrs==23.2.0
> auto-gptq==0.7.1
> beautifulsoup4==4.12.3
> bitsandbytes==0.42.0
> bs4==0.0.1
> certifi==2022.12.7
> charset-normalizer==2.1.1
> click==8.1.7
> cloudpathlib==0.16.0
> colorama==0.4.6
> coloredlogs==15.0.1
> confection==0.1.4
> contourpy==1.1.1
> cssselect==1.2.0
> cupy-cuda12x==12.1.0
> cycler==0.12.1
> datasets==2.14.6
> deepspeed==0.14.0
> dill==0.3.7
> docker-pycreds==0.4.0
> docstring-parser==0.16
> einops==0.7.0
> eval-type-backport==0.1.3
> exceptiongroup==1.2.0
> fastapi==0.110.0
> fastrlock==0.8.2
> feedfinder2==0.0.4
> feedparser==6.0.10
> ffmpy==0.3.2
> filelock==3.9.0
> fire==0.6.0
> flash-attn==2.5.6
> fonttools==4.50.0
> frozenlist==1.4.0
> fschat==0.2.36
> fsspec==2023.10.0
> ftfy==6.1.1
> gekko==1.0.7
> gitdb==4.0.11
> GitPython==3.1.40
> google==3.0.0
> gradio==4.0.0
> gradio-client==0.7.0
> h11==0.14.0
> hjson==3.1.0
> htmlmin==0.1.12
> httpcore==1.0.4
> httptools==0.6.1
> httpx==0.27.0
> huggingface-hub==0.20.3
> humanfriendly==10.0
> idna==3.4
> importlib-resources==6.3.1
> jieba3k==0.35.1
> Jinja2==3.1.2
> jsonschema==4.21.1
> jsonschema-specifications==2023.12.1
> kiwisolver==1.4.5
> langdetect==1.0.9
> lxml==4.9.3
> markdown-it-py==3.0.0
> markdown2==2.4.13
> MarkupSafe==2.1.3
> matplotlib==3.7.5
> mdurl==0.1.2
> mpi4py==3.1.5
> mpmath==1.3.0
> msgpack==1.0.8
> multidict==6.0.4
> multiprocess==0.70.15
> networkx==3.1
> newspaper3k==0.2.8
> nh3==0.2.15
> ninja==1.11.1.1
> numpy==1.24.1
> optimum==1.17.1
> orjson==3.9.15
> packaging==24.0
> pandas==2.0.3
> pathtools==0.1.2
> peft==0.10.0
> Pillow==10.1.0
> pkgutil-resolve-name==1.3.10
> prompt-toolkit==3.0.43
> protobuf==4.25.3
> psutil==5.9.8
> py-cpuinfo==9.0.0
> pyarrow==13.0.0
> pyarrow-hotfix==0.6
> pydantic==2.7.0
> pydantic-core==2.18.1
> pydub==0.25.1
> pygments==2.17.2
> pynvml==11.5.0
> pyparsing==3.1.2
> python-dateutil==2.9.0.post0
> python-dotenv==1.0.1
> python-multipart==0.0.9
> pytz==2024.1
> PyYAML==6.0.1
> quantile-python==1.1
> ray==2.9.3
> referencing==0.34.0
> regex==2023.12.25
> requests==2.28.1
> requests-file==1.5.1
> rich==13.7.1
> rouge==1.0.1
> rpds-py==0.18.0
> ruff==0.3.3
> safetensors==0.4.2
> scipy==1.10.1
> semantic-version==2.10.0
> sentencepiece==0.2.0
> sentry-sdk==1.32.0
> setproctitle==1.3.3
> sgmllib3k==1.0.0
> shellingham==1.5.4
> shortuuid==1.0.13
> shtab==1.7.1
> six==1.16.0
> smmap==5.0.1
> sniffio==1.3.1
> soupsieve==2.5
> spacy==3.7.4
> spacy-legacy==3.0.12
> srsly==2.4.8
> sse-starlette==2.1.0
> starlette==0.36.3
> svgwrite==1.4.3
> sympy==1.12
> termcolor==2.4.0
> thinc==8.2.2
> tiktoken==0.6.0
> tinysegmenter==0.3
> tldextract==5.0.1
> tokenizers==0.15.1
> tomlkit==0.12.0
> toolz==0.12.1
> torch==2.1.2+cu121
> torchaudio==2.1.2+cu121
> torchvision==0.16.2+cu121
> tqdm==4.66.1
> transformers==4.37.2
> transformers-stream-generator==0.0.4
> triton==2.1.0
> trl==0.8.1
> typer==0.9.0
> typing-extensions==4.8.0
> tyro==0.8.3
> tzdata==2024.1
> urllib3==1.26.13
> uvicorn==0.28.0
> uvloop==0.19.0
> vllm==0.3.1
> wandb==0.16.6
> watchfiles==0.21.0
> wavedrom==2.0.3.post3
> wcwidth==0.2.13
> weasel==0.3.4
> websockets==11.0.3
> xformers==0.0.23.post1
> xxhash==3.4.1
> yarl==1.9.2
> zipp==3.18.1
>

**Comment by haiasd** [comment]
I tested `import deepspeed` in the container, and it seems there are no errors.
