### ISSUE TITLE
Qwen1.5-72B-Chat-GPTQ-Int4支持流水线并行吗？有没有demo

### ISSUE THREAD

**Issue by aso233** [QwenLM/Qwen1.5#322]

**Comment by jklj077** [comment]
If you're referring to the pipeline parallelism commonly employed during training processes, the current finetuning code doesn't accommodate that functionality. However, if you're talking about the basic model parallelism where model parameters are distributed across multiple devices and computations are executed sequentially on those devices, the provided code examples pertaining to `transformers` enable that by default.

**Comment by aso233** [comment]
我指的是流水线并行，因为我的单个GPU无法容纳72B，我想知道Qwen1.5-72B-Chat-GPTQ-Int4支持流水线并行吗？如果支持的话是否能够提供一下微调脚本？

**Comment by aso233** [comment]
@jklj077 有72B流水线并行的微调demo吗

**Comment by jklj077** [comment]
I don't think it is supported by transformers or its ecosystem. You may need to use other frameworks, e.g., Megatron.
