### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by cqray1990** [QwenLM/Qwen1.5#324]
data fotmat is as fllows:
{"type": "QAml", "messages": [{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "世界上最早的报纸诞生于"}, {"role": "assistant", "content": "中国。北宋末年(公元11,12世纪)出现的印刷报纸,不仅是中国新闻史上最早的印刷报纸,也是世界新闻史上最早的印刷报纸.中国新闻事业历史的悠久,内容的丰富,是任何西方国家都难以比肩的.<e>中国古代的报纸产生于中国的封建社会时期,是封建地主阶级及其政治代表占统治地位的封建自然经济通过新闻手段的反映.在漫长的封建社会时期,中国古代的报纸,不论是官方的邸报,还是民办的小报和京报,都必然要和当时的封建统治者保持一定的联系,受他们的制约.官方的邸报固然是封建统治阶级的喉舌和御用的宣传工具,民办的小报和京报也只能在封建统治阶级的控制下活动,不能越雷池一步.封建统治者绝不允许可以自由报道一切消息和自由发表一切意见的报纸存在.中国古代的报纸在为当时的读者提供朝野政治和社会信息方面确实起过一定的作用,但始终没有摆脱统治阶级的掌握.中国古代报纸的历史,基本上是一部封建统治阶级掌握传播媒介,控制舆论工具,限制言论出版自由的历史.<e>中国古代的邸报有1200年左右的历史.小报有近千年的历史.民间报房出版的邸报,京报有近400年的历史.它们从诞生到结束,持续的时间都不算短,但发展不快,形式内容的变化不大."}], "source": "unknown"}
{"type": "QAml", "messages": [{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "世界上最早的报纸在哪个国家?"}, {"role": "assistant", "content": "中国。1271年－中国出现免费日报和面向大众的宣传册<e>14世纪<e>1314年－由于足球运动经常出现过激的暴力行为，因此在英国被禁止<e>15世纪<e>145o年－一些新闻简报开始在欧洲流行<e>1453年－欧洲出现第一本印刷书籍－－古登堡印刷了拉丁文版本的圣经<e>1477年－英国出现第一张广告传单<e>16世纪<e>1566年－威尼斯出现世界上最早的报纸之一－－《notiziescritte》"}], "source": "unknown"}

but when training , raise errors

texts = []                  
for i, msg in enumerate(mes
    texts.append(          
        tokenizer.apply_cha
            msg,           
            chat_template=T
            tokenize=True, 
            add_generation_
            padding=True,  
            max_length=max_
            truncation=True
        )                  
    )                      

   data_dict = preprocess(messages, tokenizer, max_len)
  File "/Qwen1.5/examples/sft/finetune.py", line 174, in preprocess
    input_ids = torch.tensor(texts, dtype=torch.int)
ValueError: expected sequence of length 328 at dim 1 (got 172)

**Comment by ShadowTinker** [comment]
It seems like a padding error of the tokenizer. The following modifications might be a solution:

1. Changing the following code

https://github.com/QwenLM/Qwen1.5/blob/1ae7e4069ad788b9fdc29859c2f789234af250de/examples/sft/finetune.py#L139-L166

To

```python
def preprocess(
    messages,
    tokenizer: transformers.PreTrainedTokenizer,
    max_len: int,
) -> Dict:
    """Preprocesses the data for supervised fine-tuning."""
    texts = tokenizer.apply_chat_template(
        messages,
        chat_template=TEMPLATE,
        tokenize=True,
        add_generation_prompt=False,
        padding=True,
        max_length=max_len,
        truncation=True,
    )
    input_ids = torch.tensor(texts, dtype=torch.int)
    target_ids = input_ids.clone()
    target_ids[target_ids == tokenizer.pad_token_id] = IGNORE_TOKEN_ID
    attention_mask = input_ids.ne(tokenizer.pad_token_id)

    return dict(
        input_ids=input_ids, target_ids=target_ids, attention_mask=attention_mask
    )
```

2. Set `--lazy_preprocess=False` in `finetune.sh`
