### ISSUE TITLE
qwen1.5的模型结构和llama2有什么区别

### ISSUE THREAD

**Issue by wuyaoxuehun** [QwenLM/Qwen1.5#325]
qwen1.5的模型结构和llama2有什么区别，除了qkv多了一个bias？

**Comment by shiqingzhangCSU** [comment]
词表不一样，还有slide window attention。

**Comment by jklj077** [comment]
The major differences include the choices of hyperparameters, the existence of QKV bias, and the mixing of slide window attention and full attention (the last is not realized in Qwen1.5).
