### ISSUE TITLE
使用accelerate进行多卡推理时报错

### ISSUE THREAD

**Issue by liujfeng** [QwenLM/Qwen1.5#327]
为解决device_map="auto"无法实现权重匀分到不同的卡上（会导致推理长prompt时报错oom），因此使用accelerate库来实现层切分。经分析，qwen 1.5使用accelerate库后会等第二轮迭代时，计算到cuda 1的层时，更新kv cache就会报错拼接不同device上的tensor 。已验证qwen1实现的差异不存在类似问题。请教一下qwen1.5使用accelerate进行层切分实现pp并行是否支持？是否有其他推荐方案？
 初始化过程如下：

```python
config = AutoConfig.from_pretrained(args.model_dir,trust_remote_code=True)
        with init_empty_weights():
            engine = AutoModelForCausalLM.from_config(config, torch_dtype=torch.float16,trust_remote_code=True)
        max_memory = get_balanced_memory(
            engine,
            max_memory=None,
            no_split_module_classes=engine._no_split_modules,
            dtype='float16',
            low_zero=False,
        )
        device_map = infer_auto_device_map(
            engine,
            max_memory=max_memory,
            no_split_module_classes=engine._no_split_modules,
            dtype='float16'
        )
        engine = load_checkpoint_and_dispatch(engine, checkpoint=args.model_dir, device_map=device_map)
```

报错如下图所示。
![temp](https://github.com/QwenLM/Qwen1.5/assets/32841977/49ffea03-94f3-4cff-8002-e18c05fef5e2)

**Comment by jklj077** [comment]
The `Qwen2ForCausalLM` class is a standard implementation of `PreTrainedModel` fully compatible with `accelerate`. It seems that there might be a misunderstanding in your model parameter distribution method. Notably, some necessary `accelerate` hooks might be missing. The unused variable `model._skip_keys_device_placement` raises concerns. To address this, consider incorporating `skip_keys=model._skip_keys_device_placement` as an argument when invoking `load_checkpoint_and_dispatch`.
