### ISSUE TITLE
tokenier编码过程后逐个token进行解码时空格字符存在乱码的情况

### ISSUE THREAD

**Issue by STHSF** [QwenLM/Qwen1.5#329]
当输入的字符中存在空格时，解码会出现空格，请问应该如何解决？
![image](https://github.com/QwenLM/Qwen1.5/assets/8037442/2219dc97-5022-4704-b9ce-77825efef7c4)

**Comment by jklj077** [comment]
The tokenization of Qwen or any other generative models should be idempotent. If there is space in the input, there is space in the output.

In addition, `tokenizer.decode` should be applied to token sequences not to individual tokens, as tokens are actually originally at the `byte` level and not all of them can be decoded to valid unicode strings.

**Comment by STHSF** [comment]
> The tokenization of Qwen or any other generative models should be idempotent. If there is space in the input, there is space in the output.
> 
> In addition, `tokenizer.decode` should be applied to token sequences not to individual tokens, as tokens are actually originally at the `byte` level and not all of them can be decoded to valid unicode strings.

THX
