### ISSUE TITLE
qwen tokenizer 冗余：从tiktoken词表合并sentencepiece词表带来的问题

### ISSUE THREAD

**Issue by flower-with-safe** [QwenLM/Qwen1.5#336]
之前的issue https://github.com/QwenLM/Qwen/issues/164
有提到：qwen的词表是通过gpt4 的cl100k_base合并自己通过sentencepiece训练的得到的词表合并得到的。
@jklj077 在https://github.com/QwenLM/Qwen1.5/issues/316
中也曾回复到tiktoken的原理如下：
sentencepiece operates on Unicode code points or chars, not on UTF-8 encoded bytes. For example, "你好" is two chars but 6 bytes (b"\xe4\xbd\xa0\xe5\xa5\xbd"). If "你好" is a token, sentencepiece needs one merge ("你", "好"), while BPE at the byte level needs 5 merges (b"\xe4", b"\xbd"), (b"\xe4\xbd", b"\xa0"), (b"\xe5", b"\xa5"), (b"\xe5\xa5", "\xbd"), (b"\xe4\xbd\xa0", "\xe5\xa5\xbd").
也就是说，对于sentencepiece的单个token"你"，如果想添加到tiktoken的词表，有个前提条件，应该是b"\xe4\xbd"本身就在tiktoken的词表中，否则第一步合并就无法进行。"你"这个token即使被添加到词表中，再去切这个token，也会被切碎。
验证：
`cnt = 0
qwen_tok = AutoTokenizer.from_pretrained("Qwen1.5-72B-Chat")
for i in range(len(qwen_tok)):
    if len(qwen_tok.tokenize(qwen_tok.decode(i))) != 1:
        cnt += 1
print(cnt)`
可以发现qwen的词表中，有1840个冗余token。

**Comment by jklj077** [comment]
To accurately assess the tokenizer's behavior, it's crucial to comprehend its internal workings thoroughly. The suggestion to avoid relying solely on `tokenizer.tokenize` followed by `tokenizer.decode` for validation stems from the fact that not all tokens in the tokenizer map directly to valid Unicode strings (`str`). Instead, these tokens exist original as byte sequences as indicated in the preivous issue.

The appropriate method to inspect these tokens involves working directly with their byte sequences (`bytes`) and understanding how they're translated into the `str` token interface of tokenizers in `transformers`. Tokens can be accessed via `tokenizer.decoder[id]`. For insight into the (Byte Pair Encoding) application on a given token, the `tokenizer.bpe` function (available in slow tokenizers) is instrumental; it applies BPE and yields a space-separated string of subunits.

A corrected approach to investigate would be:

```python
for i, token in tokenizer.decoder.items():
    subunits = tokenizer.bpe(token).split()
    if lensubunits != 1:
        print(i, token, subunits)
```

To illustrate with an example from your previous code snippet, consider the token labeled as "redundant":

```json
{
  "id": 2226,
  "decoded": "о�",
  "decoded|tokenized": ["Ð¾", "ï¿½"]
}
```

In this case, the actual byte sequence for the token is `b"\xd0\xbe\xd0"` and the token is stored as `"Ð¾Ð"`, which decodes to an incomplete or incorrect visual representation when naively treated as UTF-8 encoded Unicode string. The merge path is `("Ð", "¾" )` -> `("Ð¾", "Ð")`. This underscores the importance of examining the token's lifecycle from its raw byte form through the encoding and decoding processes to grasp its correct interpretation within the tokenizer's context.

**Comment by flower-with-safe** [comment]
我的疑问是，如果一个token，比如qwen中的tokenid 151134，对应的token是"璉"。如果在任意文本中出现的"璉"字，都无法被切分到tokenid151134，那么151134这个token id存在的意义是什么？

**Comment by jklj077** [comment]
You have still missed the point of BPE at the byte level. 

- 151135 represents the **byte sequence** `b"\xef\xa6\x94"`.
- The Chinese **character** `"璉"` corresponds to two **Unicode codepoints**, one is U+7489 and the other is U+F994. If encoded using UTF-8, the byte sequence of the former is `b"\xe7\x92\x89"`, while the latter is `b"\xef\xa6\x94"`.
- BPE at the byte level works on byte sequences not on characters. The point is that you are comparing different things.

**Comment by zixuxu000** [comment]
> 我的疑问是，如果一个token，比如qwen中的tokenid 151135，对应的token是"璉"。如果在任意文本中出现的"璉"字，都无法被切分到tokenid151135，那么151135这个token id存在的意义是什么？

我也感觉挺奇怪的，如果训练预料经过deocde后，不会出现151135这个id，那模型也一定不会输出这个id，这个id根本不会被用到

**Comment by jklj077** [comment]
@flower-with-safe It's related to complications in Unicode Normalization Forms. In the released code of Qwen2Tokenizer, the NFC form is always used, which is not necessarily the case in getting the byte pairs or in pretraining.

**Comment by jklj077** [comment]
@zixuxu000 there are some contexts in the tokenization_note document in QwenLM/Qwen. the conceptual part stays true. but that difference is not related to what happened here.
