### ISSUE TITLE
AttributeError 'Qwen2Tokenizer object bas no attribute 'legacy'

### ISSUE THREAD

**Issue by wangxin52791** [QwenLM/Qwen1.5#337]
<img width="984" alt="c32c163b49e995cc946a3113b43d49b" src="https://github.com/QwenLM/Qwen1.5/assets/75259281/2ad6f268-89ee-45be-af42-0f1455adc88f">

**Comment by jklj077** [comment]
As the error suggests, `Qwen2Tokenizer` has no attribute `legacy`. It is a attribute normally for `sentencepiece`-based tokenizers. Please kindly report to the KarmaVLM maintainers.
