### ISSUE TITLE
qwen1.5-72b支持输入和输出的tokens是多大？

### ISSUE THREAD

**Issue by TChengZ** [QwenLM/Qwen1.5#338]
如题，qwen1.5-72b支持输入和输出的tokens是多大？

**Comment by WangJianQ-cmd** [comment]
模型的配置文件上有吧，32k

**Comment by TChengZ** [comment]
> 模型的配置文件上有吧，32k

这个是输入加输出的总token？

**Comment by jklj077** [comment]
The Qwen model constitutes a generative language model featuring only a decoder component, such that from the standpoint of its architectural design, there exists no intrinsic distinction between input and output sequences. In essence, it generates tokens progressively without a preordained division between the two. Hence, the model boasts a single sequence length capacity of up to 32,768 tokens, wherein the user can arbitrarily assign varying lengths to serve either as input or output.
