### ISSUE TITLE
运行API服务时提示： Tokenizer class Qwen2Tokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by boboyunz** [QwenLM/Qwen1.5#34]
用 openai_api.py 运行API服务的时候报错
模型选择的是：Qwen1.5-14B-Chat-GPTQ-Int8
python3 openai_api.py --checkpoint-path /root/Qwen1.5-14B-Chat-GPTQ-Int8 --server-port 18000

Traceback (most recent call last):
  File "openai_api.py", line 574, in <module>
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 724, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class Qwen2Tokenizer does not exist or is not currently imported.

提示 Qwen2Tokenizer 不存在，请问如何解决，谢谢

**Comment by thomas-yanxin** [comment]
升级transformers>=4.37.0 ：`pip install transformer -U`

**Comment by zzqangel** [comment]
pip install transformers -U

**Comment by smellingtiger** [comment]
transformers==4.38..2也出现了这个问题  无法解决

**Comment by GYiyouth** [comment]
+1，我也有这个问题

**Comment by smellingtiger** [comment]
可能是transformers的版本问题，你升级到4.37.2以上版本看看还会有这个情况吗？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月8日(周五) 上午8:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen1.5] 运行API服务时提示： Tokenizer class Qwen2Tokenizer does not exist or is not currently imported. (Issue #34)




 
+1，我也有这个问题
 
&mdash;

**Comment by Remondor** [comment]
pip install transformers==4.38.0解决了这个问题  启动的时候建议4.39.0

**Comment by JustinLin610** [comment]
This is just sth about transformers version. Check your environment and make sure you can run the loading of tokenizer

**Comment by huangyunxin** [comment]
升级transformers后启动成功了，但是对话报错AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat'，有大佬解决了吗

**Comment by linpan** [comment]
4.39.3

**Comment by zixiaotan21** [comment]
同样遇到这个问题，我升级transformers为4.39.3，也没有解决，我是在使用langchain-chatchat,LLM模型调用Qwen-1.5-72B遇到的，python版本是3.10.8, 自己在这方面比较小白，想请教一下各位大佬解决了吗~

**Comment by neineit** [comment]
用python3.8 ， transformer 4.40  可以解决

**Comment by zixiaotan21** [comment]
好的谢谢大佬！我试试看~

**Comment by ZhangCheng518** [comment]
不管怎么升级都起不来，不知道为啥

**Comment by ZhangCheng518** [comment]
> 好的谢谢大佬！我试试看~

你解决这个问题了吗

**Comment by zixiaotan21** [comment]
> > 好的谢谢大佬！我试试看~
> 
> 你解决这个问题了吗

我解决了，但我一开始在命令行pip install transformer版本,确实没有成功。

后来我在pycharm里打开/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py这个文件，有个小窗,还是哪里.会显示让你install transformer版本的，我点了install 后面就能正常运行了。

**Comment by seanxuu** [comment]
> 升级transformers>=4.37.0 ：`pip install transformer -U`

typo fix `pip install transformers -U`
