### ISSUE TITLE
Qwen/CodeQwen1.5-7B-Chat "model_max_length": 1000000000000000019884624838656,"  ?

### ISSUE THREAD

**Issue by momomobinx** [QwenLM/Qwen1.5#342]
![image](https://github.com/QwenLM/Qwen1.5/assets/21970770/1de48b6d-c42b-480b-9eea-ab3285f0ede9)

**Comment by momomobinx** [comment]
> please illustrate the question in detail.

![image](https://github.com/QwenLM/Qwen1.5/assets/21970770/b0ddb097-db90-4bbe-9488-b054d367cfc4)
Is this normal?

**Comment by jklj077** [comment]
`model_max_length` is an attribute for tokenizers in `transformers`. It is intended for models with learned positional embeddings which has a fixed maximum sequence length. For models using relative positional embeddings, this attriubte is commonly set to a very large integer (e.g., <https://huggingface.co/mistralai/Mistral-7B-v0.1/blob/main/tokenizer_config.json>). Think of it as the theoretical maximum length. It has nothing to do with the sequence length that a trained model can actually support.
