### ISSUE TITLE
Qwen/Qwen1.5-110B-Chat-AWQ can't run successfully, until I replace the 110B's **tokenizer_config.json** with 70B's

### ISSUE THREAD

**Issue by xuzhiang** [QwenLM/Qwen1.5#354]
I deploy the **Qwen/Qwen1.5-110B-Chat-AWQ** use vllm0.4.0 + cu121 in my A100 with OpenAI format.
`python -m vllm.entrypoints.openai.api_server --model xxx`

the model generation not stop until model-max-len.
<img width="384" alt="image" src="https://github.com/QwenLM/Qwen1.5/assets/22386891/58016f12-f430-405d-b30a-f59577d65d29">

Compare the **tokenizer_config.json** in 110B with 70B, find some difference(left: 70B, right: 110B):
![image](https://github.com/QwenLM/Qwen1.5/assets/22386891/50ad8db8-a230-4974-9a5e-d22900badb67)

Replace the 110B's **tokenizer_config.json** with 70B's. the model can run successfully.

**Comment by jklj077** [comment]
Thanks for the report! The file has been updated.

**Comment by JustinLin610** [comment]
updated with the tokenizer_config. yeah u r right, vllm service needs the eos token. try it and see if it is ok for you.
