### ISSUE TITLE
Qwen1.5 110b AWQ终止符问题

### ISSUE THREAD

**Issue by SongXiaoMao** [QwenLM/Qwen1.5#357]
![QQ图片20240428194424](https://github.com/QwenLM/Qwen1.5/assets/55074934/b39c9613-cf21-4024-b390-b7c703adbdc6)
vllm跑的API服务 在72b和32b下都没有问题 使用110bAWQ的API后面多了一个终止符呢？使用gradio可以配置一下其他的UI很多都没有这个功能啊

**Comment by SongXiaoMao** [comment]
图片是沉浸式翻译插件使用vllm+Qwen1.5 110b AWQ的API结果

**Comment by jklj077** [comment]
Qwen1.5-110B-Chat-AWQ repo has been updated. try using the latest tokenizer_config.json. see also <https://github.com/QwenLM/Qwen1.5/issues/354>.

**Comment by SongXiaoMao** [comment]
> Qwen1.5-110B-Chat-AWQ repo has been updated. try using the latest tokenizer_config.json. see also #354.

已经更新配置文件解决了这个问题 感谢
