### ISSUE TITLE
Qwen1.5 LoRA微调后GPTQ量化成int4后，vllm的—tensor- parallel-size不能大于1

### ISSUE THREAD

**Issue by ChenchenJT** [QwenLM/Qwen1.5#360]
未微调前，使用vllm部署qwen1.5-14b-chat-gptq-int4可以使用—tensor-parallel-size=2或者—tensor-parallel-size=4。
使用llama- factory微调qwen1.5-14b-chat后，并使用gptq量化成int4后，使用—tensor-parallel-size大于1时会报“ ValueError: The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.”

**Comment by jklj077** [comment]
It is a historical issue for the 14B models due to its intermediate size. The 14B-Chat-GPTQ model has been updated recently to bypass the issue by padding the parameters with zeros.

**Comment by ChenchenJT** [comment]
@jklj077 Thanks
