### ISSUE TITLE
Qwen1.5-110b-AWQ回复消息偶尔会有英文或其他语言

### ISSUE THREAD

**Issue by SongXiaoMao** [QwenLM/Qwen1.5#361]
![微信截图_20240429153257](https://github.com/QwenLM/Qwen1.5/assets/55074934/2c6c04b0-2986-4702-9cff-677e0a0e5ec1)
清空消息再提问也许就不会出现了，虽然不是经常出现，但是频率还是有点多。请问可以通过配置文件解决么？

**Comment by jklj077** [comment]
Similar to <https://github.com/QwenLM/Qwen1.5/issues/302>. Please direct any related discussions to that issue.
