### ISSUE TITLE
Question about SFT with fastchat: expected sequence of length 133 at dim 1 (got 126)

### ISSUE THREAD

**Issue by mars-ch** [QwenLM/Qwen1.5#362]
I encountered this problem when I referred to the tutorial to fine-tune the chat model for 7B using fastchat's script. The code already uses padding and truncation and I'm not sure what the problem is so I'm seeking your help. Thanks

    """Preprocesses the data for supervised fine-tuning."""

    texts = []
    for i, msg in enumerate(messages):
        texts.append(
            tokenizer.apply_chat_template(
                msg,
                chat_template=TEMPLATE,
                tokenize=True,
                add_generation_prompt=False,
                padding=True,
                max_length=max_len,
                truncation=True,
            )
        )

**Comment by mars-ch** [comment]
This issue works for me.
[https://github.com/QwenLM/Qwen1.5/issues/324](url)

**Comment by jklj077** [comment]
Please try changing `padding=True` to `padding='max_length'`.
