### ISSUE TITLE
求huggingface通用finetune的脚本工程？

### ISSUE THREAD

**Issue by eigen2017** [QwenLM/Qwen1.5#363]
为什么建议上那么重的框架，swift、llama-xx。。？

微调出来的adapter_model.safetensors所在文件夹，根本huggingface load不进去。
推理加速如vllm、flm也没法做。

或者说我是不是把adapter_model.safetensors改个名，替换到原基座文件夹中即可呢？

**Comment by jklj077** [comment]
Please provide steps to reproduce.

**Comment by eigen2017** [comment]
swift可以export还原到基座样式，规避此问题。
