### ISSUE TITLE
如何生成图片

### ISSUE THREAD

**Issue by Bobyuan1015** [QwenLM/Qwen1.5#366]
前几天 跑7B-chat模型发现可以生成图片，今天跑  就提示是语言模型无法生成图片
![image](https://github.com/QwenLM/Qwen1.5/assets/25303765/cf99d206-b043-4c2e-a1d5-9be436dc4546)

**Comment by jklj077** [comment]
At present, Qwen models cannot generate images. It may memorize some image links though.
