### ISSUE TITLE
Qwen1.5-chat 72B int4 4卡(V100) 推理过程中token数到10k会报错OOM

### ISSUE THREAD

**Issue by EthanD4869** [QwenLM/Qwen1.5#367]
![image](https://github.com/QwenLM/Qwen1.5/assets/115398481/b05487ab-8c04-42cf-8f8b-8e97a85c635d)
![image](https://github.com/QwenLM/Qwen1.5/assets/115398481/50701de4-628c-435c-b05c-215934a88a90)

**Comment by jklj077** [comment]
I think it just went out of GPU memory. According to <https://qwen.readthedocs.io/en/latest/benchmark/hf_infer.html>, Qwen1.5-72B-Chat-GPTQ-Int4 need 97.38 (or 2 x 80GB GPU) to 146.17GB (or 3 x 80GB GPU) GPU memory for 8192 to 16284 tokens.
