### ISSUE TITLE
模型配置文件和tokenizer配置文件中的bos_token_id不一致

### ISSUE THREAD

**Issue by hzhaoy** [QwenLM/Qwen1.5#369]
模型配置文件（例如Qwen1.5-7B-Chat中的[config.json](https://huggingface.co/Qwen/Qwen1.5-7B-Chat/blob/main/config.json)）中，bos_token_id为151643：`"bos_token_id": 151643`
![image](https://github.com/QwenLM/Qwen1.5/assets/61868295/6b7e80a0-77c8-4843-b733-0af8b5ad5b12)

tokenizer配置文件（例如Qwen1.5-7B-Chat中的[tokenizer_config.json](https://huggingface.co/Qwen/Qwen1.5-72B-Chat/blob/main/tokenizer_config.json)）中，id(151643)对应的是"<|endoftext|>"，"<|im_start|>"对应的id为151644：
![image](https://github.com/QwenLM/Qwen1.5/assets/61868295/7ed9e641-92f5-48a3-aa03-39ec33cd714b)
另外这里的"<|im_start|>"是否可以理解为bos_token，如果是这样的话，为何在tokenizer配置文件中bos_token设置为null，有点不太理解，盼各位大神解惑，谢谢！

**Comment by JustinLin610** [comment]
no. let me explain this.

during pretraining, unlike llama, we do not have the concept of bos and eos. what we only have is the eod, which refers to `<|endoftext|>`. this is the separator for documents. however, to adapt our model to the llama usage, we use the same eod token for bos and eos. you can just simply regard the bos as some useless stuff.

but for `<|im_start|>` and `<|im_end|>`, they are used for posttraining only and they indicate the start and the end of each turn. this is following the practice of chatml format by openai (learn about it by searching chatml online). for chat, we mostly use `<|im_end|>` for the stopping criteria.
