### ISSUE TITLE
can someone share a notebook for finetuning the qwen1.5-0.5b model with an alapaca type dataset ?

### ISSUE THREAD

**Issue by hunt-47** [QwenLM/Qwen1.5#370]
i used llama-factory for fine tuning the model but the size of the model.safetensor file are changing according to  different finetuning methods. i need the model.safetensor file size to be exactly 1.24gb. i actually need the finetuned model to be quantized with gguf format for running it locally with ollama. can some one please help??

**Comment by jklj077** [comment]
Hi, 1.24GB and 890MiB should be both valid (due to tied word embeddings). May I know the file sizes you were getting?

**Comment by hunt-47** [comment]
1.72 while full fine-tuning and 982 while lora
