### ISSUE TITLE
Qwen1.5工具调用能力

### ISSUE THREAD

**Issue by rufeng-h** [QwenLM/Qwen1.5#376]
qwen-agent项目中，工具调用的prompt有如下两种格式
1. ReAct格式
2. 特殊格式
  ```py
  FN_NAME = '✿FUNCTION✿'
  FN_ARGS = '✿ARGS✿'
  FN_RESULT = '✿RESULT✿'
  FN_EXIT = '✿RETURN✿'
  ```
工具描述分别附加在user_message和system_message，实际使用中（都是单轮对话，工具描述相同）React格式的prompt工具调用准确度较高，但响应速度较慢。
请问你们对这两种格式都进行了训练吗？两种格式的工具调用准确度表现如何？

**Comment by jklj077** [comment]
Closed as duplicate in <https://github.com/QwenLM/Qwen-Agent/issues/151>
