### ISSUE TITLE
请问在使用ollama部署的qwen模型,支持function call 和 tools的调用吗

### ISSUE THREAD

**Issue by fenghua0621** [QwenLM/Qwen1.5#378]
请问在使用ollama部署的qwen模型,支持function call 和 tools的调用吗,因为我是java环境目前使用spring-ai能够正常调用对话的接口,如题请问如何能支持 function call 和 tools的调用,以及DashScope能否支持本地模型的调用
![image](https://github.com/QwenLM/Qwen1.5/assets/42227273/737552a8-44d0-487c-bb32-68695088ab6e)

**Comment by jklj077** [comment]
Hi, 
1. As explained in the README, Ollama does not support function calling. Currently, I would advise you to try Qwen-Agent, which provides a thin layer upon the OpenAI compatible API for function call support.

**Comment by jklj077** [comment]
P.S.: DashScope is a commercial service and I think you can simply open a ticket and request assistance.

**Comment by LeoXu1996** [comment]
您好，我使用spring-ai采取openai的方式调用本地模型，总是返回422，请问您遇到过吗？

**Comment by Vinke2** [comment]
> Hello,
> 
> 1. As per the README, Ollama currently doesn't offer support for function calling. In this case, I recommend exploring Qwen-Agent as an alternative solution. Qwen-Agent provides a lightweight integration that allows for function calling compatibility with its API.
> 2. To clarify, DashScope serves as an API service and is not intended for building APIs itself. While it does not directly support the use of local models, it does provide access to open-source models through its platform.

ollama现在支持函数调用了,qwen2什么时候跟进

**Comment by jklj077** [comment]
https://github.com/ollama/ollama/issues/6007
