### ISSUE TITLE
AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat_stream'

### ISSUE THREAD

**Issue by wrl1224** [QwenLM/Qwen1.5#38]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

尝试使用Qwen1.5-7B-Chat-GPTQ-Int8模型进行聊天，遇到
(欢迎使用 Qwen-Chat 模型，输入内容即可进行对话，:h 显示命令帮助。)

Note: This demo is governed by the original license of Qwen.
We strongly advise users not to knowingly generate or allow others to knowingly generate harmful content, including hate speech, violence, pornography, deception, etc.
(注：本演示受Qwen的许可协议限制。我们强烈建议，用户不应传播及不应允许他人传播以下内容，包括但不限于仇恨言论、暴力、色情、欺诈相关的有害信息。)

User> 自我介绍一下？
Traceback (most recent call last):
  File "D:\work\AI\HK_Integration\Qwen\cli_demo.py", line 210, in <module>
    main()
  File "D:\work\AI\HK_Integration\Qwen\cli_demo.py", line 198, in main
    for response in model.chat_stream(tokenizer, query, history=history, generation_config=config):
  File "D:\software\Anaconda3\envs\HK_Integration_env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat_stream'

### 期望行为 | Expected Behavior

.

### 复现方法 | Steps To Reproduce

具备所有依赖条件，运行cli_demo.py

### 运行环境 | Environment

```Markdown
- OS:windows10
- Python:3.8
- Transformers:4.37.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

### 备注 | Anything else?

.

**Comment by connermo** [comment]
+1

**Comment by hffei** [comment]
+1

**Comment by seamoon224** [comment]
+1

**Comment by seamoon224** [comment]
问题应该是在于chat_stream方法做了改动，在原来第一版的qwen的modeling_qwen.py的QWenLMHeadModel类中，有chat_stream方法，但qwen-1.5B还没有开放modeling_qwen.py文件...

**Comment by Panda-ka** [comment]
> 问题应该是在于chat_stream方法做了改动，在原来第一版的qwen的modeling_qwen.py的QWenLMHeadModel类中，有chat_stream方法，但qwen-1.5B还没有开放modeling_qwen.py文件...

请问目前有什么解决方案吗？

**Comment by zhangfan-algo** [comment]
我也遇到 怎么办呢

**Comment by dliting** [comment]
+1

**Comment by jklj077** [comment]
Do not interchange Qwen(1.0) and Qwen1.5 codes or model weights, as they are fundamentally incompatible. For implementing streaming responses with transformers, consult the official documentation at: <https://qwen.readthedocs.io/en/latest/inference/chat.html#streaming-mode>.

请勿混用Qwen(1.0)与Qwen1.5的代码或模型权重，因为它们之间根本不兼容。若需使用transformers实现流式响应，请参阅官方文档：<https://qwen.readthedocs.io/zh-cn/latest/inference/chat.html#streaming-mode>。

**Comment by lululiu2323** [comment]
请问解决方案是什么呢？我也遇到了同样的问题

**Comment by dreamTrainer** [comment]
我也遇到这个问题， 其实就是要用qwen1.5 repo 下面demo的client.py来运行qwen1.5 , qwen1.5和qwen不一样推理代码
