### ISSUE TITLE
swift微调qwen1.5-32b，然后用autoawq量化，用vllm部署有时会出现感叹号

### ISSUE THREAD

**Issue by CNXDZS** [QwenLM/Qwen1.5#381]
我看之前issue，int4量化用vllm部署会偶尔出现感叹号问题，但是awq应该不会？

**Comment by jklj077** [comment]
The generation of an infinite sequence of exclamation marks seems to correlate with the `RuntimeError: probability tensor contains either inf, nan or element < 0`. This issue often arises from numerical instability when using fp16 precision, which is commonly utilized in efficient kernels for quantization techniques such as GPTQ and AWQ.

Before proceeding with quantization, we kindly advise you to ensure that your model functions correctly without quantization. If it operates satisfactorily beforehand, consider increasing the size or diversity of your calibration dataset during the quantization process. A more extensive and varied dataset can help improve the quantization's accuracy and potentially alleviate this issue.

**Comment by CNXDZS** [comment]
> The generation of an infinite sequence of exclamation marks seems to correlate with the `RuntimeError: probability tensor contains either inf, nan or element < 0`. This issue often arises from numerical instability when using fp16 precision, which is commonly utilized in efficient kernels for quantization techniques such as GPTQ and AWQ.
> 
> Before proceeding with quantization, we kindly advise you to ensure that your model functions correctly without quantization. If it operates satisfactorily beforehand, consider increasing the size or diversity of your calibration dataset during the quantization process. A more extensive and varied dataset can help improve the quantization's accuracy and potentially alleviate this issue.

Thanks for you reply! I will adjust my calibration dataset and tyr again :)

**Comment by CNXDZS** [comment]
> 这个问题我用无量化版本的qwen1.5-32B-Chat +vllm 0.4.x 版本也遇到了。vllm 0.3.3 还没遇到。不过vllm0.3.3不支持qwen1.5 的 lora 部署

我用alpaca数据做校准数据试了下awq量化，vllm(0.4.1.post1)部署目前没出现感叹号。之前用官方qwen1.5-32B-Chat-int4+vllm部署会有感叹号的问题。不量化版本没试过，因为实际部署环境不允许。。多谢回复！

**Comment by kratorado** [comment]
应该多半是vllm的问题，因为我用更早的qwen1.5-72b 也遇到过感叹号的情况。而且从0.4.x开始vllm的质量就开始不行了，modelscope这个环境变量失效了，也没有修复
