### ISSUE TITLE
多机多卡训练配置问题

### ISSUE THREAD

**Issue by summerrain321** [QwenLM/Qwen1.5#386]
运行命令：bash examples/sft/finetune.sh，微调72B模型
在阿里云上，分布式训练（DLC）设置 节点总数：4，型号：A800，X GPU 8
报错位置：finetune.py的model = AutoModelForCausalLM.from_pretrained
报错日志：Loading checkpoint shards:   3%开始报错：torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 7 (pid: 83) of binary: /usr/bin/python3

请问examples/sft/finetune.sh是否支持多机多卡训练？

另外尝试微调7B模型，虽然可以微调成功，但是看日志，只有在节点1上训练，另外3个节点没有参与训练。多机多卡需要如何配置？

**Comment by jklj077** [comment]
The example finetuning script does support running on multiple hosts. The related configuration is as follows:

https://github.com/QwenLM/Qwen1.5/blob/1ae7e4069ad788b9fdc29859c2f789234af250de/examples/sft/finetune.sh#L11-L24

Aliyun PAI-DLC should provide those environment variables but the names may not match. Please refer to the documentation of DLC at <https://help.aliyun.com/zh/pai/user-guide/general-environment-variables>.

The mapping appears to be:
```
GPUS_PER_NODE=1
NNODES=$WORLD_SIZE
NODE_RANK=$RANK
MASTER_ADDRESS=$MASTER_ADDRESS
MASTER_PORT=$MASTER_PORT
```
