### ISSUE TITLE
Qwen的代码开源了吗？

### ISSUE THREAD

**Issue by WzjCoder** [QwenLM/Qwen1.5#393]
请问Qwen的代码开源了吗？

**Comment by WzjCoder** [comment]
Thank you for your reply! Where can I find the source code for the model? I don't think I saw it in the project.

**Comment by jklj077** [comment]
- For transformers, it is at <https://github.com/huggingface/transformers/tree/main/src/transformers/models/qwen2>.
- For vllm, it is at <https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/qwen2.py>.
- For llama.cpp, see code related to the following PR: <https://www.github.com/ggerganov/llama.cpp/pull/5037/>.

**Comment by WzjCoder** [comment]
thanks!
