### ISSUE TITLE
How to enable flash attention 2?

### ISSUE THREAD

**Issue by LinB203** [QwenLM/Qwen1.5#40]
Wonderful work!
I wonder that whether you train model with flash attention 2 or not? And how to enable flash attention 2? 
Have you test flash attention 2 will make model performance degradation?

**Comment by insist93** [comment]
+1

**Comment by hzhwcmhf** [comment]
You can enable flash attention 2 by adding ``attn_implementation`` option, like

```
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", attn_implementation="flash_attention_2", torch_dtype=“auto")
```

We did not observe significant performance differences after enabling flash attention

**Comment by insist93** [comment]
thank you ， I tested the eager，flash attention2，sdpa and found that flash attention2 has the best effect, which can speed up 20-25%, and the effect of sdpa and eager is similar

**Comment by jklj077** [comment]
sdpa requires pytorch>=2.1.1; otherwise, it will fall back to egar/manual.

**Comment by ShadowTeamCN** [comment]
I'm using H800 and  parameter 

> attn_implementation="flash_attention_2",

has very significantly speed up
