### ISSUE TITLE
Ollama库中，不同的标签后缀含义是什么？

### ISSUE THREAD

**Issue by RuikangSun** [QwenLM/Qwen1.5#403]
![图片](https://github.com/QwenLM/Qwen1.5/assets/20597187/46ce4e52-743c-4f18-ac6e-db2d081313d6)

如图所示，Ollama下的Qwen库拥有类似于“qwen:14b-text-v1.5-q5_K_S”的标签。我在文档中并未找到关于标签的定义。前半段比较容易理解，但后半段K、S、M、L等字母具有何种含义？不同的场景选择不同标签的最佳实践是什么？
谢谢！

**Comment by jklj077** [comment]
Those are specifications of the quantized models from llama.cpp. You can think of those as names of the recipes/configuration on how the model is actually quantized ("quantization mix").

At present, the format is like `{IQ,Q}_{1,2,3,4,5,6,8}_{0,1,K}_{,XXS,XS,S,M,L,NL}`. Not all combination is valid.

- `{IQ,Q}`: IQ means i-quants with importance matrix, which can improve accuracy for quants of smaller bits. For 1,2,3-bit quants, you will want ones with IQ.
- `{1,2,3,4,5,6,8}`: The nominal bit depth. The average bits per weight (bpw) may be higher than this.
- `{0,1,K}`: The quantization type. 0 and 1 are legacy quants. k means the [k-quants](https://www.github.com/ggerganov/llama.cpp/pull/1684) and the bpw is higher than the nominal bit. k-quants should be prefered now. If omitted, it should be considered as K.
- `{,XXS,XS,S,M,L,NL}`: The variant specification. If it exists, it means not all weights use the same quantization types (mainly for accuray reasons) and the bpw will be higher. XXS is extra extra small, L is large, etc. NL is a special one, probably meaning non-linear, and only applies to 4-bit quants.

For example:
- Q8_0 means type 0 quants with 8-bit.
- Q4_K_M means k-quants with 4-bit and medium size. This is often a balanced one and [used in the example in llama.cpp](https://github.com/ggerganov/llama.cpp#prepare-and-quantize).
- IQ2_XXS means i-quants with 2-bit and extra extra small size.
- [IQ4_NL](https://www.github.com/ggerganov/llama.cpp/pull/5590) means that generally you don't want to use this.
