### ISSUE TITLE
为什么同样的脚本（Qwen1.5/examples/web_demo.py）去执行Qwen1.5-32B-Chat-GPTQ-Int4的推理时，4090 24G 比 V100 32G 回答速度快了5倍，这是什么原因，是显卡性能的问题，还是代码还有哪个配置没有打开，导致V100的计算能力没有发挥出来？

### ISSUE THREAD

**Issue by lbl1120** [QwenLM/Qwen1.5#405]
为什么同样的脚本（Qwen1.5/examples/web_demo.py）去执行Qwen1.5-32B-Chat-GPTQ-Int4的推理时，4090 24G 比 V100 32G 回答速度快了5倍，这是什么原因，是显卡性能的问题，还是代码还有哪个配置没有打开，导致V100的计算能力没有发挥出来？
![屏幕截图 2024-05-13 212724](https://github.com/QwenLM/Qwen1.5/assets/152936427/4298b8a4-4498-4939-bb2e-27a0d7d5286c)

**Comment by jklj077** [comment]
Hi, lbl1120!

There are several factors that can indicate the actual performance, including theoretical throughput (xx FLOPs), memory space (xx GB), memory bandwith (xx GB/s), and compute capability (the sm_xx). Comparing RTX 4090 and V100, V100 has no advantage at all and I believe it is expected to run slower using V100 GPUs.

**Comment by liaoweiguo** [comment]
代差摆那儿
