### ISSUE TITLE
FlashAttention only support fp16 and bf16 data type

### ISSUE THREAD

**Issue by umbraclet16** [QwenLM/Qwen1.5#406]
lora finetune时为了解决显存不足的问题在预训练模型的config.json中设置了_attn.implementation为flash_attention_2，进行模型推理时报错：
RuntimeError: FlashAttention only support fp16 and bf16 data type
但AutoModelForCausalLM加载qwen2模型并不支持添加bf16/fp16参数。
请问如何解决？
![IMG_20240514_104456.jpg](https://github.com/QwenLM/Qwen1.5/assets/13113857/91f4d2b1-b923-44c4-82f6-00ab9007034f)

**Comment by jklj077** [comment]
Hi, umbraclet16! 

You should be able to pass `torch_dtype="auto"` to `from_pretrained` and it will use bfloat16 by default. Please refer to the README. It is also possible to pass `torch.bfloat16` or `torch.float16`. If you did not pass this parameter, `transformers` defaults to the default `torch` dtype which is `torch.float32`. The behaviour is explained [here](https://huggingface.co/docs/transformers/main_classes/model#transformers.PreTrainedModel.from_pretrained.torch_dtype).

**Comment by umbraclet16** [comment]
> Hi, umbraclet16! 
> 
> You should be able to pass `torch_dtype="auto"` to `from_pretrained` and it will use bfloat16 by default. Please refer to the README. It is also possible to pass `torch.bfloat16` or `torch.float16`. If you did not pass this parameter, `transformers` defaults to the default `torch` dtype which is `torch.float32`. The behaviour is explained [here](https://huggingface.co/docs/transformers/main_classes/model#transformers.PreTrainedModel.from_pretrained.torch_dtype).

THX!
