### ISSUE TITLE
use qwen1.5 with vllm default prompt template?

### ISSUE THREAD

**Issue by 2533245542** [QwenLM/Qwen1.5#41]
Hi I am using qwen1.5 72b with vllm with this on 4 A100 80G

`CUDA_VISIBLE_DEVICES=0,1,2,3 python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen1.5-72B-Chat --enforce-eager --tensor-parallel-size 4 --gpu-memory-utilization 1.0 --max-model-len 4096`

Do I need to specify a template? Currently vllm tells me that it is using 

```
INFO 02-12 14:59:44 serving_chat.py:260] Using default chat template:
INFO 02-12 14:59:44 serving_chat.py:260] {% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system
INFO 02-12 14:59:44 serving_chat.py:260] You are a helpful assistant<|im_end|>
INFO 02-12 14:59:44 serving_chat.py:260] ' }}{% endif %}{{'<|im_start|>' + message['role'] + '
INFO 02-12 14:59:44 serving_chat.py:260] ' + message['content']}}{% if (loop.last and add_generation_prompt) or not loop.last %}{{ '<|im_end|>' + '
INFO 02-12 14:59:44 serving_chat.py:260] '}}{% endif %}{% endfor %}{% if add_generation_prompt and messages[-1]['role'] != 'assistant' %}{{ '<|im_start|>assistant
INFO 02-12 14:59:44 serving_chat.py:260] ' }}{% endif %}
```

**Comment by wsp317** [comment]
vllm will call the tokenizer's `apply_chat_template` method, details see below link
https://github.com/vllm-project/vllm/blob/e433c115bce2bf27f7b1abdde7029566007d9eee/vllm/entrypoints/openai/serving_chat.py#L56
