### ISSUE TITLE
Readme inconsistent with small model licences

### ISSUE THREAD

**Issue by ozppupbg** [QwenLM/Qwen1.5#411]
Hello,

the Readme states:
> https://github.com/QwenLM/Qwen1.5/blob/e294ff7b23711ecdebaf9ebf8b8fcfb54f68d31b/README.md?plain=1#L265-L266

However, the referenced licenses in the model directories for these models:
https://huggingface.co/Qwen/Qwen1.5-0.5B/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-0.5B-Chat/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-1.8B/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-1.8B-Chat/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-4B/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-4B-Chat/blob/main/LICENSE
contains:
> Tongyi Qianwen RESEARCH LICENSE AGREEMENT
> Tongyi Qianwen Release Date: November 30, 2023

Which states, that a commercial use requires to request a license:
https://huggingface.co/Qwen/Qwen1.5-0.5B/blob/8f445e3628f3500ee69f24e1303c9f10f5342a39/LICENSE#L19-L21

All the larger models have a different license without this provision:
https://huggingface.co/Qwen/Qwen1.5-7B/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-7B-Chat/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-MoE-A2.7B/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-MoE-A2.7B-Chat/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-14B/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-14B-Chat/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-32B/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-32B-Chat/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-72B/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-72B-Chat/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-110B/blob/main/LICENSE
https://huggingface.co/Qwen/Qwen1.5-110B-Chat/blob/main/LICENSE
> Tongyi Qianwen LICENSE AGREEMENT
> Tongyi Qianwen Release Date: August 3, 2023

Is this intentional?
And how does the Research License Agreement relate to the statement in the Readme?

Thank you!

Regards

**Comment by JustinLin610** [comment]
yes, this is an issue with small models. for the research license, we do not directly grant commercial usages to users. we might figure out a better way for this in the near future. sorry about that
