### ISSUE TITLE
why padding_side right?

### ISSUE THREAD

**Issue by smallflyingpig** [QwenLM/Qwen1.5#416]
In the finetune script, padding_side is set as "right": https://github.com/QwenLM/Qwen1.5/blob/e294ff7b23711ecdebaf9ebf8b8fcfb54f68d31b/examples/sft/finetune.py#L324
I think the padding size is "left"

**Comment by jklj077** [comment]
It is finetuning, left or right does not matter.

**Comment by prismformore** [comment]
@jklj077 Can you elaborate on why it doesn't matter here? Thanks a lot!
