### ISSUE TITLE
vllm After calling LLM.generate, there is no output

### ISSUE THREAD

**Issue by shuaiFLYINTHESKY** [QwenLM/Qwen1.5#425]
I deployed the CodeQwen1.5-7B-Chat model using vllm, fire, gradio frameworks, but I encountered normal input but no output from the model. 
I have tried to modify parameters such as seq_length, but I still get no output. 
I suspect that the input text is too long, but the example in the screenshot has a significantly smaller number of input tokens than seq_length. 
This problem has been bothering me for a long time and I haven't been able to find a solution. I would like to ask you whether you have encountered this kind of problem, and please guide some solutions or solutions. thanks very much

1.Problem phenomenon:

<img width="2932" alt="image" src="https://github.com/QwenLM/Qwen1.5/assets/98887892/a847119b-24b6-4b58-8849-3377046381db">

2.Environmental dependencies are as follows:

<img width="724" alt="image" src="https://github.com/QwenLM/Qwen1.5/assets/98887892/0b67fc34-9a9f-4499-8df7-73bf45a1ba47">

3.Here's my code:
```
#######################################################
# qwen model

import fire
import torch
import transformers
import gradio as gr
from vllm import LLM, SamplingParams


def main(base_model="./Models/CodeQwen1.5-7B-Chat", n_gpus=1, port=8080):

    llm = LLM(model=base_model, tensor_parallel_size=n_gpus, gpu_memory_utilization=0.9, enforce_eager=False)

    def evaluate_vllm(instruction, temperature=0, max_new_tokens=2048):
        problem_prompt = (
            "Below is an instruction that describes a task. "
            "Write a response that appropriately completes the request.\n\n"
            "### Instruction:\n{instruction}\n\n### Response:"
        )
        prompt = problem_prompt.format(instruction=instruction)

        problem_instruction = [prompt]
        # stop_tokens = ['</s>']  # Training use this
        stop_tokens = ["<|endogtext|>"]  # Inference use this
        sampling_params = SamplingParams(temperature=temperature, top_p=1, max_tokens=max_new_tokens, stop=stop_tokens)
        completions = llm.generate(problem_instruction, sampling_params)
        for output in completions:
            prompt = output.prompt
            print("==========================question=============================")
            print(prompt)
            generated_text = output.outputs[0].text
            print("===========================answer==============================")
            print(generated_text)
            print("=========================answer end============================")
            return generated_text

    with gr.Interface(
            fn=evaluate_vllm,
            inputs=[
                gr.components.Textbox(
                    lines=3,
                    label="Instruction",
                    placeholder="Anything you want to ask CodeQwen?",
                ),
                gr.components.Slider(minimum=0, maximum=1, value=0, label="Temperature"),
                gr.components.Slider(
                    minimum=1, maximum=2048, step=1, value=1024, label="Max tokens"
                ),
            ],
            outputs=[gr.components.Textbox(lines=30, label="Output")],
            title="BA-CoderQwen"
    ) as interface:
        with gr.Accordion(label="Disclaimer!"):
            gr.Markdown(
                """
                \n
                This project does not accept any legal liability for the content of the model output, nor does it assume 
                responsibility for any losses incurred due to the use of associated resources and output results.
                """
            )

    interface.queue().launch(share=True, server_name="0.0.0.0", server_port=port, max_threads=128, show_api=False)


if __name__ == "__main__":
    fire.Fire(main)`

###########################################################################################
#  api server

from gradio_client import Client

# init flask app
app = Flask(__name__)

# AI model parameter
temperature = 0
max_token = 16 * 1024
model_endpoint = "http://0.0.0.0:8080/"


@app.route("/generate_unit_test", methods=["POST"])
def generate_unit_test():
    data = request.json
    function_code = data.get("function_code")
    language = data.get("language")
    prompt_ut = data.get("prompt")
    import_list = data.get("importList")

    if import_list is None:
        prompt = f"""{prompt_ut}:
                ```{language}
                {function_code}
                ```
                """
    else:
        prompt = f"""{prompt_ut}:
                ```{language}
                {function_code}
                ```
                {import_list}
                """

    client = Client(model_endpoint)
    result = client.predict(instruction=prompt, temperature=temperature, max_new_tokens=max_token,
                            api_name="/predict")
    print(result)
    return result

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8848)

**Comment by jklj077** [comment]
Hi!

It appears that you are using `LLM.generate` directly and this method requires the input texts to be formatted. For Qwen chat models (including CodeQwen1.5-7B-Chat), the format should be ChatML and custom templates like the one you have defined in `problem_prompt` just may not work. Please refer to the README on how to use the tokenizer to apply chat template and you can get the tokenizer by `LLM.get_tokenizer()`.

Here is an example:
```python
prompt = llm.get_tokenizer().apply_chat_template(
    [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": instruction},
    ], 
    tokenize=False,
    add_generation_prompt=True,
)
```

In addition, CodeQwen1.5 has it own repo at <https://github.com/QwenLM/CodeQwen1.5>. Check it out!

**Comment by shuaiFLYINTHESKY** [comment]
> 你好！
> 
> 看起来您正在`LLM.generate`直接使用，并且此方法需要格式化输入文本。对于 Qwen 聊天模型（包括 CodeQwen1.5-7B-Chat），格式应为 ChatML，而您在`problem_prompt`just 中定义的自定义模板可能不起作用。请参阅 README 了解如何使用 tokenizer 应用聊天模板，您可以通过 获取 tokenizer `LLM.get_tokenizer()`。
> 
> 以下是一个例子：
> 
> ```python
> prompt = llm.get_tokenizer().apply_chat_template(
>     [
>         {"role": "system", "content": "You are a helpful assistant."},
>         {"role": "user", "content": instruction},
>     ], 
>     tokenize=False,
>     add_generation_prompt=True,
> )
> ```
> 
> 此外，CodeQwen1.5 在https://github.com/QwenLM/CodeQwen1.5有自己的 repo 。快去看看吧！

Thanks for your reply!
I have modified the code according to your guidance, and it has worked normally, thank you very much.

Also, I noticed that in the simple example of vllm deployment in README, tokenizer was not invoked. 
https://qwen.readthedocs.io/en/latest/deployment/vllm.html, this link is right.
<img width="1095" alt="image" src="https://github.com/QwenLM/Qwen1.5/assets/98887892/c8a5f121-337a-4e02-b2ad-d35d93540b4a">

**Comment by jklj077** [comment]
Hi, 

README shows an example of using vLLM via the OpenAI-compatible API. It is totally differnet from using the LLM class from vLLM and apply chat template is not needed for the "v1/chat/completions" endpoint.

**Comment by shuaiFLYINTHESKY** [comment]
> Hi,
> 
> README shows an example of using vLLM via the OpenAI-compatible API. It is totally differnet from using the LLM class from vLLM and apply chat template is not needed for the "v1/chat/completions" endpoint.

I see. Thanks again for your guidance.
