### ISSUE TITLE
多轮对话训练数据格式问题

### ISSUE THREAD

**Issue by yangxin60-tal** [QwenLM/Qwen1.5#427]
请问多轮对话的训练数据格式怎么组织

**Comment by jklj077** [comment]
Hi! 

If you are using the `examples/sft/finetune.py`, the data is in a format similar to what one would pass to OpenAI API. The `messages` is a list and support multi-turn naturally. For example,
```json
{
    "type": "chatml",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "What is your name?"
        },
        {
            "role": "assistant",
            "content": "My name is Qwen."
        },
        {
            "role": "user",
            "content": "Tell me something about large language models."
        },
        {
            "role": "assistant",
            "content": "Large language models are a type of language model that is trained on a large corpus of text data. They are capable of generating human-like text and are used in a variety of natural language processing tasks..."
        }
    ],
    "source": "self-made"
}
```

(Note: the example is formatted for ease of reference; The actual training data should be of the jsonline format, where each line is a json string.)

**Comment by yangxin60-tal** [comment]
thanks for your response !!!
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, May 23, 2024 11:25 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [QwenLM/Qwen1.5] 多轮对话训练数据格式问题 (Issue #427)

&nbsp;



 
Hi!
 
If you are using the examples/sft/finetune.py, the data is in a format similar to what one would pass to OpenAI API. The messages is a list and support multi-turn naturally. For example,
 {     "type": "chatml",     "messages": [         {             "role": "system",             "content": "You are a helpful assistant."         },         {             "role": "user",             "content": "What is your name?"         },         {             "role": "assistant",             "content": "My name is Qwen."         },         {             "role": "user",             "content": "Tell me something about large language models."         },         {             "role": "assistant",             "content": "Large language models are a type of language model that is trained on a large corpus of text data. They are capable of generating human-like text and are used in a variety of natural language processing tasks..."         }     ],     "source": "self-made" }
 
(Note: the example is formatted for ease of reference; The actual training data should be of the jsonline format, where each line is a json string.)
