### ISSUE TITLE
Bad result in Qwen1.5-0.5B-Chat-GGUF

### ISSUE THREAD

**Issue by cx2333-gt** [QwenLM/Qwen1.5#43]
![image](https://github.com/QwenLM/Qwen1.5/assets/99069487/71a3dbcc-7f28-4b96-94c6-dfc763dd94e1)
![image](https://github.com/QwenLM/Qwen1.5/assets/99069487/b1fd9311-0dfa-4f37-bcca-8378566f20fb)

same setting in transformer
![image](https://github.com/QwenLM/Qwen1.5/assets/99069487/e0a3d4c1-5ea1-4dc7-90d3-977020e14823)

**Comment by anaivebird** [comment]
请问是如何解决的呢

**Comment by cx2333-gt** [comment]
> 请问是如何解决的呢 @cx2333-gt

用ollama吧
