### ISSUE TITLE
【求助】关于算法备案的问题

### ISSUE THREAD

**Issue by bh4ffu** [QwenLM/Qwen1.5#430]
关于算法备案，需要提供【互联网信息服务算法安全自评估报告】，请教以下两个问题：
1、开源的大模型私有化部署需要做算法备案，官方是否支持备案，是否存在法律或者道义上的问题？
2、算法备案需要提供算法的技术细节，有哪些渠道可以获取到？

thanks!

**Comment by jklj077** [comment]
1. We respectfully direct your attention to the pertinent provisions enshrined within the corresponding Licensing Agreements—specifically, the Tongyi Qianwen License Agreement and the Tongyi Qianwen Research License Agreement. It is advisable that you engage with your legal counsel for a comprehensive interpretation and application of these terms.
2. With regard to the particulars of Qwen1.5, we regret to inform you that we do not possess the requisite documentation at hand. However, we recommend an in-depth review of "The Qwen Technical Report," which can be accessed via the following link: <https://arxiv.org/abs/2309.16609>. This resource may provide you with the foundational insights necessary for your inquiry.
