### ISSUE TITLE
【您好，请求帮助】魔搭下载的qwen1_5-14b-chat-q2_k.gguf 使用llama.cpp中的./server部署运行后，对话或者postman接口访问服务偶尔不返回生成结果。

### ISSUE THREAD

**Issue by hanshishang** [QwenLM/Qwen1.5#432]
**【问题】**使用llama.cpp提供的对话页面生成结果偶尔不返回，使用postman接口访问也有如下问题，在魔搭尝试下载了7b、14b不同的gguf版本均有此问题：
 对话模式现象:
![llamacpp](https://github.com/QwenLM/Qwen1.5/assets/16880909/5e7bbb1d-67f8-45c0-b502-d1de5495cc6d)
postman访问现象:
![postman](https://github.com/QwenLM/Qwen1.5/assets/16880909/b0f2c0e5-dd94-400c-a224-971ea1d7c943)

一、服务端日志如下：
--------------有生成有返回
{"tid":"140260074186560","timestamp":1716513763,"level":"INFO","function":"launch_slot_with_task","line":1040,"msg":"slot is processing task","id_slot":0,"id_task":689}
{"tid":"140260074186560","timestamp":1716513763,"level":"INFO","function":"update_slots","line":2090,"msg":"kv cache rm [p0, end)","id_slot":0,"id_task":689,"p0":63}
{"tid":"140260074186560","timestamp":1716513769,"level":"INFO","function":"print_timings","line":322,"msg":"prompt eval time     =    1525.36 ms /    18 tokens (   84.74 ms per token,    11.80 tokens per second)","id_slot":0,"id_task":689,"t_prompt_processing":1525.355,"n_prompt_tokens_processed":18,"t_token":84.74194444444444,"n_tokens_second":11.800531679510673}
{"tid":"140260074186560","timestamp":1716513769,"level":"INFO","function":"print_timings","line":338,"msg":"generation eval time =    4632.41 ms /    11 runs   (  421.13 ms per token,     2.37 tokens per second)","id_slot":0,"id_task":689,"t_token_generation":4632.409,"n_decoded":11,"t_token":421.1280909090909,"n_tokens_second":2.3745744384833034}
{"tid":"140260074186560","timestamp":1716513769,"level":"INFO","function":"print_timings","line":348,"msg":"          total time =    6157.76 ms","id_slot":0,"id_task":689,"t_prompt_processing":1525.355,"t_token_generation":4632.409,"t_total":6157.763999999999}
{"tid":"140260074186560","timestamp":1716513769,"level":"INFO","function":"update_slots","line":1788,"msg":"slot released","id_slot":0,"id_task":689,"n_ctx":9024,"n_past":91,"n_system_tokens":0,"n_cache_tokens":91,"truncated":false}
{"tid":"140260074186560","timestamp":1716513769,"level":"INFO","function":"update_slots","line":1806,"msg":"all slots are idle"}
{"tid":"140245491812096","timestamp":1716513769,"level":"INFO","function":"log_server_request","line":2882,"msg":"request","remote_addr":"25.38.108.34","remote_port":55035,"status":200,"method":"POST","path":"/completion","params":{}}
{"tid":"140260074186560","timestamp":1716513769,"level":"INFO","function":"update_slots","line":1806,"msg":"all slots are idle"}

------------无生成返回结果
{"tid":"140260074186560","timestamp":1716513788,"level":"INFO","function":"launch_slot_with_task","line":1040,"msg":"slot is processing task","id_slot":0,"id_task":702}
{"tid":"140260074186560","timestamp":1716513788,"level":"INFO","function":"update_slots","line":2090,"msg":"kv cache rm [p0, end)","id_slot":0,"id_task":702,"p0":91}
{"tid":"140260074186560","timestamp":1716513789,"level":"INFO","function":"print_timings","line":322,"msg":"prompt eval time     =    1458.66 ms /    17 tokens (   85.80 ms per token,    11.65 tokens per second)","id_slot":0,"id_task":702,"t_prompt_processing":1458.661,"n_prompt_tokens_processed":17,"t_token":85.80358823529411,"n_tokens_second":11.654524252036627}
{"tid":"140260074186560","timestamp":1716513789,"level":"INFO","function":"print_timings","line":338,"msg":"generation eval time =       0.03 ms /     1 runs   (    0.03 ms per token, 32258.06 tokens per second)","id_slot":0,"id_task":702,"t_token_generation":0.031,"n_decoded":1,"t_token":0.031,"n_tokens_second":32258.064516129034}
{"tid":"140260074186560","timestamp":1716513789,"level":"INFO","function":"print_timings","line":348,"msg":"          total time =    1458.69 ms","id_slot":0,"id_task":702,"t_prompt_processing":1458.661,"t_token_generation":0.031,"t_total":1458.692}
{"tid":"140260074186560","timestamp":1716513789,"level":"INFO","function":"update_slots","line":1788,"msg":"slot released","id_slot":0,"id_task":702,"n_ctx":9024,"n_past":108,"n_system_tokens":0,"n_cache_tokens":108,"truncated":false}
{"tid":"140260074186560","timestamp":1716513789,"level":"INFO","function":"update_slots","line":1806,"msg":"all slots are idle"}
{"tid":"140245483419392","timestamp":1716513789,"level":"INFO","function":"log_server_request","line":2882,"msg":"request","remote_addr":"25.38.108.34","remote_port":55052,"status":200,"method":"POST","path":"/completion","params":{}}
{"tid":"140260074186560","timestamp":1716513789,"level":"INFO","function":"update_slots","line":1806,"msg":"all slots are idle"}

二、使用llama.cpp启动方式如下：
       MODEL="${MODEL:-./models/Qwen/qwen1_5-14b-chat-q2_k.gguf}"
        PROMPT_TEMPLATE=${PROMPT_TEMPLATE:-./prompts/chat-with-qwen.txt}
        # Adjust to the number of CPU cores you want to use.
        N_THREAD="${N_THREAD:-32}"
        # Note: you can also override the generation options by specifying them on the command line:
        GEN_OPTIONS="${GEN_OPTIONS:---ctx_size 9000 --batch-size 2048}"
        # shellcheck disable=SC2086 # Intended splitting of GEN_OPTIONS
        nohup ./server $GEN_OPTIONS \
                --host xx.xx.xxx.xxx \
                --port 18081 \
                --model "$MODEL" \
                --alias qwen14b_q2 \
                --threads "$N_THREAD" \
                --grp-attn-n 1 \
                --rope-freq-scale 1.0 \
                "$@" &
启动后日志：
llama_model_loader: loaded meta data with 21 key-value pairs and 483 tensors from ./models/Qwen/qwen1_5-14b-chat-q2_k.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.name str              = Qwen1.5-14B-Chat-AWQ-fp16
llama_model_loader: - kv   2:                          qwen2.block_count u32              = 40
llama_model_loader: - kv   3:                       qwen2.context_length u32              = 32768
llama_model_loader: - kv   4:                     qwen2.embedding_length u32              = 5120
llama_model_loader: - kv   5:                  qwen2.feed_forward_length u32              = 13696
llama_model_loader: - kv   6:                 qwen2.attention.head_count u32              = 40
llama_model_loader: - kv   7:              qwen2.attention.head_count_kv u32              = 40
llama_model_loader: - kv   8:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv   9:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  10:                qwen2.use_parallel_residual bool             = true
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  13:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  14:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  15:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  16:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  17:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  18:                    tokenizer.chat_template str              = {% for message in messages %}{{'<|im_...
llama_model_loader: - kv  19:               general.quantization_version u32              = 2
llama_model_loader: - kv  20:                          general.file_type u32              = 10
llama_model_loader: - type  f32:  201 tensors
llama_model_loader: - type q4_1:   40 tensors
llama_model_loader: - type q2_K:  161 tensors
llama_model_loader: - type q3_K:   80 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: missing pre-tokenizer type, using: 'default'
llm_load_vocab:
llm_load_vocab: ************************************
llm_load_vocab: GENERATION QUALITY WILL BE DEGRADED!
llm_load_vocab: CONSIDER REGENERATING THE MODEL
llm_load_vocab: ************************************
llm_load_vocab:
llm_load_vocab: special tokens definition check successful ( 421/152064 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = qwen2
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 152064
llm_load_print_meta: n_merges         = 151387
llm_load_print_meta: n_vocab          = 152064
llm_load_print_meta: n_merges         = 151387
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 5120
llm_load_print_meta: n_head           = 40
llm_load_print_meta: n_head_kv        = 40
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 5120
llm_load_print_meta: n_embd_v_gqa     = 5120
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 13696
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 13B
llm_load_print_meta: model ftype      = Q2_K - Medium
llm_load_print_meta: model params     = 14.17 B
llm_load_print_meta: model size       = 5.66 GiB (3.43 BPW)
llm_load_print_meta: general.name     = Qwen1.5-14B-Chat-AWQ-fp16
llm_load_print_meta: BOS token        = 151643 '<|endoftext|>'
llm_load_print_meta: EOS token        = 151645 '<|im_end|>'
llm_load_print_meta: PAD token        = 151643 '<|endoftext|>'
llm_load_print_meta: LF token         = 148848 'ÄĬ'
llm_load_print_meta: EOT token        = 151645 '<|im_end|>'
llm_load_tensors: ggml ctx size =    0.23 MiB
llm_load_tensors:        CPU buffer size =  5799.61 MiB
........................................................................................
llama_new_context_with_model: n_ctx      = 9024
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =  7050.00 MiB
llama_new_context_with_model: KV self size  = 7050.00 MiB, K (f16): 3525.00 MiB, V (f16): 3525.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     1.16 MiB
llama_new_context_with_model:        CPU compute buffer size =   762.63 MiB
llama_new_context_with_model: graph nodes  = 1406
llama_new_context_with_model: graph splits = 1
{"tid":"140121444804416","timestamp":1716516396,"level":"INFO","function":"init","line":709,"msg":"initializing slots","n_slots":1}
{"tid":"140121444804416","timestamp":1716516396,"level":"INFO","function":"init","line":721,"msg":"new slot","id_slot":0,"n_ctx_slot":9024}
{"tid":"140121444804416","timestamp":1716516396,"level":"INFO","function":"main","line":3028,"msg":"model loaded"}
{"tid":"140121444804416","timestamp":1716516396,"level":"INFO","function":"init","line":721,"msg":"new slot","id_slot":0,"n_ctx_slot":9024}
{"tid":"140121444804416","timestamp":1716516396,"level":"INFO","function":"main","line":3028,"msg":"model loaded"}
{"tid":"140121444804416","timestamp":1716516396,"level":"INFO","function":"main","line":3053,"msg":"chat template","chat_example":"<|im_start|>system\nYou are a helpful assistant<|im_end|>\n<|im_start|>user\nHello<|im_end|>\n<|im_start|>assistant\nHi there<|im_end|>\n<|im_start|>user\nHow are you?<|im_end|>\n<|im_start|>assistant\n","built_in":true}
{"tid":"140121444804416","timestamp":1716516396,"level":"INFO","function":"main","line":3781,"msg":"HTTP server listening","n_threads_http":"31","hostname":"xxx.xx.xx.xx","port":"18081"}
{"tid":"140121444804416","timestamp":1716516396,"level":"INFO","function":"update_slots","line":1806,"msg":"all slots are idle"}

**Comment by jklj077** [comment]
Hi, 

It seems like there are multiple factors at play here. Let's tackle this step by step:

1. **Test the `main` Executable**: Begin by running the `main` executable following the examples provided  [here](https://qwen.readthedocs.io/en/latest/run_locally/llama.cpp.html#running-qwen-gguf-files). 
   If everything goes well, it might suggest an issue with the `server` configuration. However, should you still experience glitches, exploring different versions of the quantized models could be beneficial.

2. **Experiment with the "/v1/chat/completions" endpoint**: Test out the "/v1/chat/completions" endpoint of the `server` and refer to these [examples](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md) for guidance. 
   If this works as expected, the issue could be specific to the "/completion" endpoint. Should this not resolve the matter, kindly redirect your concerns to the llama.cpp community for specialized support.
