### ISSUE TITLE
[question] any plans for larger MoE model?

### ISSUE THREAD

**Issue by handoku** [QwenLM/Qwen1.5#436]
Firstly, thanks for all your works on chinese LLM.

And I want to know, in addition to [Qwen1.5-MoE-A2.7B](https://huggingface.co/Qwen/Qwen1.5-MoE-A2.7B), do you plan to release more other size MoE models?

The current A2.7B model may not be good enough to satisfy practical needs.

**Comment by jklj077** [comment]
Yes
