### ISSUE TITLE
如何Merge原始模型和使用lora微调出来的adapter_model

### ISSUE THREAD

**Issue by ZhenHengDong** [QwenLM/Qwen1.5#437]
使用Qwen1.5-14B-chat，使用finetune.sh脚本，用lora微调，微调出来的结果存放在output_qwen中，请问如何将base模型和lora模型merge。

**Comment by jklj077** [comment]
Hi, if you were using examples/sft/finetune.py, it uses `peft` to do the heavy lifting. It is a simple-to-use package from Hugging Face. You can also find its documentation quite easily from the web, and here is the one I found: <https://huggingface.co/docs/peft/developer_guides/lora#merge-adapters>. There are also similar ones in the issue area, and it is recommend to always search first.
