### ISSUE TITLE
关于Qwen1.5-72B-chat模型的推理问题请教

### ISSUE THREAD

**Issue by Cyich** [QwenLM/Qwen1.5#442]
您好，请问单机多卡，8张V100，使用官方提供的HuggingFace推理脚本（没有vllm，没有flash-attention），推理Qwen1.5-72B-chat模型。我的输入组成是：prompt_template（灵积上计算token数量约1500 tokens）+3000~3500字符串长度的内容。输出max_new_tokens限制在1024个token。

加载完模型之后，在报错之前的正常运行过程中，基本上只有以下几行日志打印，我看了下其他issue，我理解应该是没什么影响的吧？
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
2024-05-27 13:08:25.381744: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

随后就是运行一段时间后的报错，OOM，
请问，的确是显存不够吗？为什么我经常OOM报错呢？某次报错贴出如下（基本上都是这个OOM报错，多次报错可能就是报错那一行的memory数值有点区别，基本上是一样的问题）：
1031	Traceback (most recent call last):
  1032	  File "/qwen_72B_expr/72B_inference_official_way_for_doc_ee.py", line 112, in <module>
  1033	    answers = batch_predict_qwen_1_5_72b_model(batch_inputs)
  1034	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1035	  File "/qwen_72B_expr/72B_inference_official_way_for_doc_ee.py", line 58, in batch_predict_qwen_1_5_72b_model
  1036	    generated_ids = model.generate(
  1037	                    ^^^^^^^^^^^^^^^
  1038	  File "/usr/local/python3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
  1039	    return func(*args, **kwargs)
  1040	           ^^^^^^^^^^^^^^^^^^^^^
  1041	  File "/usr/local/python3/lib/python3.11/site-packages/transformers/generation/utils.py", line 1758, in generate
  1042	    result = self._sample(
  1043	             ^^^^^^^^^^^^^
  1044	  File "/usr/local/python3/lib/python3.11/site-packages/transformers/generation/utils.py", line 2397, in _sample
  1045	    outputs = self(
  1046	              ^^^^^
  1047	  File "/usr/local/python3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
  1048	    return forward_call(*args, **kwargs)
  1049	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1050	  File "/usr/local/python3/lib/python3.11/site-packages/accelerate/hooks.py", line 166, in new_forward
  1051	    output = module._old_forward(*args, **kwargs)
  1052	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1053	  File "/usr/local/python3/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1149, in forward
  1054	    outputs = self.model(
  1055	              ^^^^^^^^^^^
  1056	  File "/usr/local/python3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
  1057	    return forward_call(*args, **kwargs)
  1058	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1059	  File "/usr/local/python3/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1034, in forward
  1060	    layer_outputs = decoder_layer(
1061	                    ^^^^^^^^^^^^^^
  1062	  File "/usr/local/python3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
  1063	    return forward_call(*args, **kwargs)
  1064	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1065	  File "/usr/local/python3/lib/python3.11/site-packages/accelerate/hooks.py", line 166, in new_forward
  1066	    output = module._old_forward(*args, **kwargs)
  1067	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1068	  File "/usr/local/python3/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 748, in forward
  1069	    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  1070	                                                          ^^^^^^^^^^^^^^^
  1071	  File "/usr/local/python3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
  1072	    return forward_call(*args, **kwargs)
  1073	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1074	  File "/usr/local/python3/lib/python3.11/site-packages/accelerate/hooks.py", line 166, in new_forward
  1075	    output = module._old_forward(*args, **kwargs)
  1076	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1077	  File "/usr/local/python3/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 294, in forward
  1078	    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
  1079	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1080	  File "/usr/local/python3/lib/python3.11/site-packages/torch/nn/functional.py", line 1845, in softmax
  1081	    ret = input.softmax(dim, dtype=dtype)
  1082	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  1083	torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.96 GiB (GPU 1; 31.75 GiB total capacity; 24.34 GiB already allocated; 3.48 GiB free; 27.10 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

而且有时候运行了好几个小时，才OOM，比如某次推理：开始时间2024-05-27 18:05:52，结束时间2024-05-27 20:34:54。跑了4个多小时才OOM。显存占用情况如下图所示，基本上一直稳定在这个快占满的比例，
![image](https://github.com/QwenLM/Qwen1.5/assets/48990457/6154b245-828c-4074-85af-cb3d6a9d6b97)

请您帮忙解决一下这个问题，谢谢！另外关于我这个实验条件下，跑这个72B模型的推理，有什么比较好的建议，现在推理也比较慢，另外，我希望能够把输入上下文的字符串长度部分放大到5000，输出大小放大到1024个token，希望得到指导，谢谢您！

**Comment by Cyich** [comment]
另外，我也看到你们公开的benchmark推理，https://qwen.readthedocs.io/en/latest/benchmark/hf_infer.html，但是由于我无法使用flash-attention，所以我认为和你们的实验设置上存在不同，所以无法完全参考你们的实验数据。但是8张V100和4张A100的显存应该差不多大，都是320G左右，我理解是不是应该和你们的实验数据相差不那么大？比如显存占用你们的数据是230+G，input_length是14336（单位是token？），以及Speed。目前由于我一直存在OOM的问题，还没有看到Speed数值，但是看上去我的input_length可能没你们的14336大，但是显存占用却全满了，从我上面给出的显存占用图来看，应该不止230+G？请问这是为什么呢，希望得到您的解答和建议，谢谢！

![image](https://github.com/QwenLM/Qwen1.5/assets/48990457/21734d42-a215-41b7-98a3-43de04417443)

**Comment by Cyich** [comment]
顺便提一下，我的总数据量是10000，由于我有时候运行了好几个小时才OOM（此时我也不知道推理了多少数据了，一开始没加tqdm进度显示），因此我正在尝试使用100条数据进行推理，目前看推理了大概有40多分钟到50分钟了，仍然没有运行结束。请问这个推理速度是正常的吗？本次实验的输入字符串长度由3000降到了2000，输出也由1024改成了512。本次的显存占用情况如下图：

![image](https://github.com/QwenLM/Qwen1.5/assets/48990457/2d751243-5268-447f-98db-9b5f594980b2)

**Comment by jklj077** [comment]
The multi-gpu inference support of `transformers` via `accelerate` is not very efficient or in other terms, very inefficient. It is not recommended except for demonstration purposes (single-gpu inference of transformers is fine). 

For your use case, our general advice is to use a dedicated inference framework, e.g. vllm, as said in the README. If you must use `transformers`, for long sequences, you will need to use flash attention v2. Please follow this [comment](https://github.com/QwenLM/Qwen1.5/issues/56#issuecomment-2123859366) and it should work on V100s.

**Comment by Cyich** [comment]
谢谢！

单gpu使用transformers方式推理是比较推荐的吗？这个的前提应该是单gpu能跑得动某个尺寸的模型吧。

的确，我应该去尝试一下使用vllm，和你提供的另一个flash attention v2的指导。

再次感谢！
