### ISSUE TITLE
为什么词表中文是乱码的？

### ISSUE THREAD

**Issue by gg22mm** [QwenLM/Qwen1.5#445]
为什么词表中文是乱码的？
![10f84488dc1a6991e0011acccab21ef](https://github.com/QwenLM/Qwen1.5/assets/6648329/9a7cac66-0051-4ede-917f-edb0e987bd83)
![1716865120841](https://github.com/QwenLM/Qwen1.5/assets/6648329/00ae15f3-2270-42e7-98fe-7204db4171c6)

**Comment by jklj077** [comment]
I would recommend you to read [the original gpt2 tokenizer code](https://github.com/openai/gpt-2/blob/master/src/encoder.py) if you are very new to the topic and would like to learn about the inner workings.

For oridinary users, simply follow the README and use `tokenizer(...)` and `tokenizer.decode(...)`.

There are also similar issues in the issue area, and searching for them first is a good practice.
