### ISSUE TITLE
使用  examples/sft目录下的脚本微调模型后，如何与原模型进行融合

### ISSUE THREAD

**Issue by xuelikanmeihua** [QwenLM/Qwen1.5#451]

**Comment by xuelikanmeihua** [comment]
解决方案在哪里呢

**Comment by jklj077** [comment]
- https://github.com/QwenLM/Qwen1.5/issues/437
- https://github.com/QwenLM/Qwen1.5/issues/188

Please search the issues first. It is right there. If you have met other problems, please feel free to open a new issue, and describe your issues in details there.
