### ISSUE TITLE
qwen moe 推理速度非常慢

### ISSUE THREAD

**Issue by nieallen** [QwenLM/Qwen1.5#453]
模型使用Qwen1.5-MoE-A2.7B-Chat，单a100，输入长度1500，输出长度40，时延12秒，而qwen1.5-7b只需要3秒不到。
代码用的qwen官方提供的加载推理

**Comment by jklj077** [comment]
Hi, please refer to the introduction at <https://qwenlm.github.io/blog/qwen-moe/#costs-and-efficiency>. Notably, the comparison was conducted using `vllm`.

**Comment by nieallen** [comment]
> Hi, please refer to the introduction at https://qwenlm.github.io/blog/qwen-moe/#costs-and-efficiency. Notably, the comparison was conducted using `vllm`.

Yes! Using vllm can accelerate inference speed, the improvement is by a factor of 1.75

**Comment by nieallen** [comment]
I test on the A10 and observed that, compared to the Qwen1.5-7B model, the Qwen-moe no improvement in inference speed. The average latency between the two remained consistent. Is this reasonable?
