### ISSUE TITLE
使用vllm.entrypoints.openai.api_server启动模型时，调用API输出结果不正确

### ISSUE THREAD

**Issue by LeonG7** [QwenLM/Qwen1.5#46]
vLLM
We advise you to use vLLM>=0.3.0 to build OpenAI-compatible API service. Start the server with a chat model, e.g. Qwen1.5-7B-Chat:

```
python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen1.5-7B-Chat
```
Then use the chat API as demonstrated below:
```
curl http://localhost:8000/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
    "model": "Qwen/Qwen1.5-7B-Chat",
    "messages": [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "你是谁？"}
    ]
    }'
  ```
输出结果结尾有很多'\n\n\n'

在调用接口时增加参数`"add_generation_prompt":True`解决该问题。

**Comment by cyc00518** [comment]
@LeonG7 
您好, 謝謝您的分享
我也遇到相同的問題, 
想請教您"add_generation_prompt":True
這個參數我可以在哪邊找到他的說明呢?

**Comment by JustinLin610** [comment]
Actually "add_generation_prompt" is by default True

**Comment by ticoAg** [comment]
> vLLM We advise you to use vLLM>=0.3.0 to build OpenAI-compatible API service. Start the server with a chat model, e.g. Qwen1.5-7B-Chat:
> 
> ```
> python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen1.5-7B-Chat
> ```
> 
> Then use the chat API as demonstrated below:
> 
> ```
> curl http://localhost:8000/v1/chat/completions \
>     -H "Content-Type: application/json" \
>     -d '{
>     "model": "Qwen/Qwen1.5-7B-Chat",
>     "messages": [
>     {"role": "system", "content": "You are a helpful assistant."},
>     {"role": "user", "content": "你是谁？"}
>     ]
>     }'
> ```
> 
> 输出结果结尾有很多'\n\n\n'
> 
> 在调用接口时增加参数`"add_generation_prompt":True`解决该问题。

我的测试中未生效,测试10条只有两条结尾没有'\n\n'

**Comment by ticoAg** [comment]
使用vllm.entrypoints.openai.api_server提供服务
tokenizer.apply_chat_template messages后传入openai.Completion.create
或者直接使用openai.ChatCompletion.create 都是这样的

**Comment by junjzhang** [comment]
遇到了同样的问题，暂时把`\n\n\n`作为stop word

**Comment by junjzhang** [comment]
重新试了下，之前的case是修改了system message，现在使用默认system message，把之前的system message放到user message里，没有出现这个问题了。

**Comment by kimlee1874** [comment]
同样的问题，不过部署chat模型时不会出现，微调之后的模型推理时会有大量的\n，并且会把预训练语料也吐出来，尚不清楚是什么原因引入的。

**Comment by LeonG7** [comment]
> > vLLM We advise you to use vLLM>=0.3.0 to build OpenAI-compatible API service. Start the server with a chat model, e.g. Qwen1.5-7B-Chat:
> > ```
> > python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen1.5-7B-Chat
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then use the chat API as demonstrated below:
> > ```
> > curl http://localhost:8000/v1/chat/completions \
> >     -H "Content-Type: application/json" \
> >     -d '{
> >     "model": "Qwen/Qwen1.5-7B-Chat",
> >     "messages": [
> >     {"role": "system", "content": "You are a helpful assistant."},
> >     {"role": "user", "content": "你是谁？"}
> >     ]
> >     }'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 输出结果结尾有很多'\n\n\n'
> > 在调用接口时增加参数`"add_generation_prompt":True`解决该问题。
> 
> 我的测试中未生效,测试10条只有两条结尾没有'\n\n'

嗯我测试了其他的query，问题依然存在，下面的讨论中提到了修改system信息，我测试一下了这种方式

```
"messages": [
    {"role": "system", "content": "你是一个可以提供帮助的智能助手"},
    {
      "role": "user",
      "content": "上海市的好吃的介绍一下"
    }
```
设置了一个中文的系统提示，好像可以解决输出多个换行符的问题，你可以测试一下

**Comment by ticoAg** [comment]
测试case的原因,直接`messages = [{"role": "user", "content": "上海市的好吃的介绍一下"}]`或者换其他的content也没有那个情况,感觉可能是`你是谁`,`你是什么模型`这类相关的训练数据影响的

**Comment by cyc00518** [comment]
這樣就不能設置`system_prompt`了, 
似乎是vllm的問題?

**Comment by junjzhang** [comment]
> 這樣就不能設置`system_prompt`了, 似乎是vllm的問題?

 我比较认同@ticoAg的观点，我测试了下，发现如果在system prompt里出现了"你是xxx"这类表述会出现这个问题，但换成“请你扮演xxxx“就会好很多，都可以尝试一下。

**Comment by junjzhang** [comment]
使用sglang部署一样会遇到这个问题，统一ticoAg的观点，和system message关系很大。

**Comment by zouhuigang** [comment]
那怎么解决？

**Comment by ticoAg** [comment]
实测0.5B-Chat使用示例代码transformers推理无此问题

**Comment by junjzhang** [comment]
我解决了，在请求时使用 skip_special_tokens=False

**Comment by cyc00518** [comment]
@junjzhang 
不好意思, 方便請教一下
我是用openai的方式去請求, 但`skip_special_tokens`應該是tokenizer的參數, 
您是怎麼使用的呢?

```
from openai import OpenAI
# Set OpenAI's API key and API base to use vLLM's API server.

openai_api_key = "EMPTY"
openai_api_base = "http://localhost:8000/v1"
client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)

chat_response = client.chat.completions.create(
    model='Qwen-1.5-72B-Chat-Int4',
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Tell me a joke."},
    ],  
    stop=['<|im_end|>','<|im_start|>'],
    skip_special_tokens=False
)
print("Chat response:", chat_response)
```

![image](https://github.com/QwenLM/Qwen1.5/assets/96753147/e8841a50-c11b-4e61-9df1-3d7fe1839238)

**Comment by zouhuigang** [comment]
@junjzhang 感谢大佬

**Comment by ticoAg** [comment]
https://github.com/vllm-project/vllm/issues/2947#issuecomment-1959569041

**Comment by ticoAg** [comment]
https://github.com/vllm-project/vllm/issues/2947#issuecomment-1959569041

**Comment by kimlee1874** [comment]
> [vllm-project/vllm#2947 (comment)](https://github.com/vllm-project/vllm/issues/2947#issuecomment-1959569041)
> 
> 结论: `python -m vllm.entrypoints.openai.api_server`部署的,请求带上这俩参数
> 
> ```json
> {
>     "skip_special_tokens": false,
>     "stop": ["<|im_end|>"]
> }
> ```
> 
> FastChat vllm部署的 SamplingParams [vllm_worker-L118](https://github.com/lm-sys/FastChat/blob/ed6735d84a198325e1f6a155976987bc75e1f14a/fastchat/serve/vllm_worker.py#L118) 指定`skip_special_tokens=False`

这样感觉也有问题，推理的输出都很短，而且不包含'\n'了，感觉效果和在stop里添加'\n'类似。

**Comment by junjzhang** [comment]
> > [vllm-project/vllm#2947 (comment)](https://github.com/vllm-project/vllm/issues/2947#issuecomment-1959569041)
> > 结论: `python -m vllm.entrypoints.openai.api_server`部署的,请求带上这俩参数
> > ```json
> > {
> >     "skip_special_tokens": false,
> >     "stop": ["<|im_end|>"]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > FastChat vllm部署的 SamplingParams [vllm_worker-L118](https://github.com/lm-sys/FastChat/blob/ed6735d84a198325e1f6a155976987bc75e1f14a/fastchat/serve/vllm_worker.py#L118) 指定`skip_special_tokens=False`
> 
> 这样感觉也有问题，推理的输出都很短，而且不包含'\n'了，感觉效果和在stop里添加'\n'类似。

理论上和stop里加`\n`是不一样的，这里的问题是vllm在决定是否stop的时候使用reponse decode得到的str，而qwen的stop token是后添加的特殊token，如果skip_special_tokens decode得到的就不会包含stop token，所以要skip_special token: false。
推理输出短你可以尝试调整下别的采样参数，例如top_p，top_k, repetition_penalty什么的。

**Comment by kimlee1874** [comment]
> > > [vllm-project/vllm#2947 (comment)](https://github.com/vllm-project/vllm/issues/2947#issuecomment-1959569041)
> > > 结论: `python -m vllm.entrypoints.openai.api_server`部署的,请求带上这俩参数
> > > ```json
> > > {
> > >     "skip_special_tokens": false,
> > >     "stop": ["<|im_end|>"]
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > FastChat vllm部署的 SamplingParams [vllm_worker-L118](https://github.com/lm-sys/FastChat/blob/ed6735d84a198325e1f6a155976987bc75e1f14a/fastchat/serve/vllm_worker.py#L118) 指定`skip_special_tokens=False`
> > 
> > 
> > 这样感觉也有问题，推理的输出都很短，而且不包含'\n'了，感觉效果和在stop里添加'\n'类似。
> 
> 理论上和stop里加`\n`是不一样的，这里的问题是vllm在决定是否stop的时候使用reponse decode得到的str，而qwen的stop token是后添加的特殊token，如果skip_special_tokens decode得到的就不会包含stop token，所以要skip_special token: false。 推理输出短你可以尝试调整下别的采样参数，例如top_p，top_k, repetition_penalty什么的。

理论上确实应该是不同的，造成这种现象应该是参数没传进去导致的。我换了一种方式在部署的时候把skip_special_tokens的默认值直接修改为False，然后在stop中把special token添加进来，这样子推理就正常了。

**Comment by junjzhang** [comment]
> > > > [vllm-project/vllm#2947 (comment)](https://github.com/vllm-project/vllm/issues/2947#issuecomment-1959569041)
> > > > 结论: `python -m vllm.entrypoints.openai.api_server`部署的,请求带上这俩参数
> > > > ```json
> > > > {
> > > >     "skip_special_tokens": false,
> > > >     "stop": ["<|im_end|>"]
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > FastChat vllm部署的 SamplingParams [vllm_worker-L118](https://github.com/lm-sys/FastChat/blob/ed6735d84a198325e1f6a155976987bc75e1f14a/fastchat/serve/vllm_worker.py#L118) 指定`skip_special_tokens=False`
> > > 
> > > 
> > > 这样感觉也有问题，推理的输出都很短，而且不包含'\n'了，感觉效果和在stop里添加'\n'类似。
> > 
> > 
> > 理论上和stop里加`\n`是不一样的，这里的问题是vllm在决定是否stop的时候使用reponse decode得到的str，而qwen的stop token是后添加的特殊token，如果skip_special_tokens decode得到的就不会包含stop token，所以要skip_special token: false。 推理输出短你可以尝试调整下别的采样参数，例如top_p，top_k, repetition_penalty什么的。
> 
> 理论上确实应该是不同的，造成这种现象应该是参数没传进去导致的。我换了一种方式在部署的时候把skip_special_tokens的默认值直接修改为False，然后在stop中把special token添加进来，这样子推理就正常了。

对，在request时除非你直接自己发送请求，如果使用类似openai的三方库，valid的参数会因为各家实现使用有所不同。

**Comment by ticoAg** [comment]
测试了下, `sglang.launch_server`也需要传以下参数输出内容正常
```json
{
    "skip_special_tokens": false,
    "stop": [
        "<|im_end|>"
    ],
}
```

**Comment by allenhaozi** [comment]
set 
```json
{
  "skip_special_tokens": false,
  "max_tokens": 128,
  "model": "qwen1.5-72b-chat-int4",
  "n": 1,
  "prompt": "你好",
  "stop":  ["<|im_end|>", "<|endoftext|>","<|im_start|>"],
  "stream": false,
  "suffix": null,
  "temperature": 1,
  "top_p": 1,
  "user": "user-1234"
}
```
encounter the following error occasionally
```
Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7f2fdac304c0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f2fd8348eb0>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7f2fdac304c0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f2fd8348eb0>)>
Traceback (most recent call last):
  File "/workspace/vllm/engine/async_llm_engine.py", line 29, in _raise_exception_on_finish
    task.result()
  File "/workspace/vllm/engine/async_llm_engine.py", line 411, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/workspace/vllm/engine/async_llm_engine.py", line 390, in engine_step
    request_outputs = await self.engine.step_async()
  File "/workspace/vllm/engine/async_llm_engine.py", line 203, in step_async
    return self._process_model_outputs(output, scheduler_outputs)
  File "/workspace/vllm/engine/llm_engine.py", line 754, in _process_model_outputs
    self._process_sequence_group_outputs(seq_group, outputs)
  File "/workspace/vllm/engine/llm_engine.py", line 624, in _process_sequence_group_outputs
    self._decode_sequence(seq, seq_group.sampling_params)
  File "/workspace/vllm/engine/llm_engine.py", line 930, in _decode_sequence
    read_offset) = detokenize_incrementally(
  File "/workspace/vllm/transformers_utils/tokenizer.py", line 221, in detokenize_incrementally
    new_text = tokenizer.convert_tokens_to_string(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

The above exception was the direct cause of the following exception:


```

**Comment by allenhaozi** [comment]
request
```
{
  "max_tokens": 128,
  "model": "qwen1.5-72b-chat-int4",
  "n": 1,
  "prompt": "你好",
  "stop": null,
  "stream": false,
  "suffix": null,
  "temperature": 1,
  "top_p": 1,
  "user": "user-1234"
}
```
response
```
{
  "id": "cmpl-091f2b4d7a4f44e3abaa569f187db65e",
  "object": "text_completion",
  "created": 3652144,
  "model": "qwen1.5-72b-chat-int4",
  "choices": [
    {
      "index": 0,
      "text": "gun拼音gun的拼音是：\n\n“gun”在拼音中对应的汉字是“棍”，拼音是：“gùn”\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n。",
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 1,
    "total_tokens": 106,
    "completion_tokens": 105
  }
}
```

**Comment by morning-hao** [comment]
> @junjzhang 不好意思, 方便請教一下 我是用openai的方式去請求, 但`skip_special_tokens`應該是tokenizer的參數, 您是怎麼使用的呢?
> 
> ```
> from openai import OpenAI
> # Set OpenAI's API key and API base to use vLLM's API server.
> 
> openai_api_key = "EMPTY"
> openai_api_base = "http://localhost:8000/v1"
> client = OpenAI(
>     api_key=openai_api_key,
>     base_url=openai_api_base,
> )
> 
> chat_response = client.chat.completions.create(
>     model='Qwen-1.5-72B-Chat-Int4',
>     messages=[
>         {"role": "system", "content": "You are a helpful assistant."},
>         {"role": "user", "content": "Tell me a joke."},
>     ],  
>     stop=['<|im_end|>','<|im_start|>'],
>     skip_special_tokens=False
> )
> print("Chat response:", chat_response)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/96753147/306945150-e8841a50-c11b-4e61-9df1-3d7fe1839238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDM3OTIsIm5iZiI6MTcwOTcwMzQ5MiwicGF0aCI6Ii85Njc1MzE0Ny8zMDY5NDUxNTAtZTg4NDFhNTAtYzExYi00ZTYxLTlkZjEtM2Q3ZmUxODM5MjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA1MzgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MmEyNDQwMTZiZDc5MmQ3ODYwYTUxODY3N2M0MjFkN2FjNDg5NjgxMWNlN2M3ZDQyMjliYTljODI3YmQxZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lHNrTOmKR4UzFfIn4OGqGsjdHfD0xLAwyQWl8Sok7BI)

可以直接在安装目录修改这个参数,，这是0.3.3版本的vllm

找文件
```    1  pip show vllm
    2  cd /usr/local/lib/python3.10/dist-packages
    3  ls
    4  cd ./vllm/
    5  ls
    6  cd ./engine/llm_engine.py 
    7  vim ./engine/llm_engine.py
```

改参数
```
    def _decode_sequence(self, seq: Sequence, prms: SamplingParams) -> None:
        """Decodes the new token for a sequence."""
        (new_tokens, new_output_text, prefix_offset,
         read_offset) = detokenize_incrementally(
             self.get_tokenizer_for_seq(seq),
             all_input_ids=seq.get_token_ids(),
             prev_tokens=seq.tokens,
             prefix_offset=seq.prefix_offset,
             read_offset=seq.read_offset,
             # 这里直接改成False
             # skip_special_tokens=prms.skip_special_tokens,
             skip_special_tokens=False,
             spaces_between_special_tokens=prms.spaces_between_special_tokens,
         )
```

然后在启动请求
```
python -m vllm.entrypoints.openai.api_server     --model  xxx
```

**Comment by changshivek** [comment]
> > @junjzhang 不好意思, 方便請教一下 我是用openai的方式去請求, 但`skip_special_tokens`應該是tokenizer的參數, 您是怎麼使用的呢?
> > ```
> > from openai import OpenAI
> > # Set OpenAI's API key and API base to use vLLM's API server.
> > 
> > openai_api_key = "EMPTY"
> > openai_api_base = "http://localhost:8000/v1"
> > client = OpenAI(
> >     api_key=openai_api_key,
> >     base_url=openai_api_base,
> > )
> > 
> > chat_response = client.chat.completions.create(
> >     model='Qwen-1.5-72B-Chat-Int4',
> >     messages=[
> >         {"role": "system", "content": "You are a helpful assistant."},
> >         {"role": "user", "content": "Tell me a joke."},
> >     ],  
> >     stop=['<|im_end|>','<|im_start|>'],
> >     skip_special_tokens=False
> > )
> > print("Chat response:", chat_response)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/96753147/306945150-e8841a50-c11b-4e61-9df1-3d7fe1839238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDM3OTIsIm5iZiI6MTcwOTcwMzQ5MiwicGF0aCI6Ii85Njc1MzE0Ny8zMDY5NDUxNTAtZTg4NDFhNTAtYzExYi00ZTYxLTlkZjEtM2Q3ZmUxODM5MjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA1MzgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MmEyNDQwMTZiZDc5MmQ3ODYwYTUxODY3N2M0MjFkN2FjNDg5NjgxMWNlN2M3ZDQyMjliYTljODI3YmQxZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lHNrTOmKR4UzFfIn4OGqGsjdHfD0xLAwyQWl8Sok7BI)
> 
> 可以直接在安装目录修改这个参数,，这是0.3.3版本的vllm
> 
> 找文件
> 
> ```
>     2  cd /usr/local/lib/python3.10/dist-packages
>     3  ls
>     4  cd ./vllm/
>     5  ls
>     6  cd ./engine/llm_engine.py 
>     7  vim ./engine/llm_engine.py
> ```
> 
> 改参数
> 
> ```
>     def _decode_sequence(self, seq: Sequence, prms: SamplingParams) -> None:
>         """Decodes the new token for a sequence."""
>         (new_tokens, new_output_text, prefix_offset,
>          read_offset) = detokenize_incrementally(
>              self.get_tokenizer_for_seq(seq),
>              all_input_ids=seq.get_token_ids(),
>              prev_tokens=seq.tokens,
>              prefix_offset=seq.prefix_offset,
>              read_offset=seq.read_offset,
>              # 这里直接改成False
>              # skip_special_tokens=prms.skip_special_tokens,
>              skip_special_tokens=False,
>              spaces_between_special_tokens=prms.spaces_between_special_tokens,
>          )
> ```
> 
> 然后在启动请求
> 
> ```
> python -m vllm.entrypoints.openai.api_server     --model  xxx
> ```

openai的包实际上提供了传额外配置参数的接口，可以在model_kwargs里传，以我在langchain中调用vllm部署的模型设定为例，如下：
```
chat = ChatOpenAI(
    openai_api_key="EMPTY",
    openai_api_base=inference_server_url,
    model_name=model_name,
    temperature=0.8, 
    max_tokens=1000,
    model_kwargs={"stop": ["<|endoftext|>", "<|im_end|>"], "extra_body": {"skip_special_tokens": False}}  
)
```
这样不用改变openai库代码就可以使用。
具体实现参考openai代码库的 /your-python-site-packages/openai/resources/completions.py 第499行
![image](https://github.com/QwenLM/Qwen1.5/assets/23412353/3c7084b1-1bfd-450d-a38d-6ff59722ef74)

**Comment by allenhaozi** [comment]
> request
> 
> ```
> {
>   "max_tokens": 128,
>   "model": "qwen1.5-72b-chat-int4",
>   "n": 1,
>   "prompt": "你好",
>   "stop": null,
>   "stream": false,
>   "suffix": null,
>   "temperature": 1,
>   "top_p": 1,
>   "user": "user-1234"
> }
> ```
> 
> response
> 
> ```
> {
>   "id": "cmpl-091f2b4d7a4f44e3abaa569f187db65e",
>   "object": "text_completion",
>   "created": 3652144,
>   "model": "qwen1.5-72b-chat-int4",
>   "choices": [
>     {
>       "index": 0,
>       "text": "gun拼音gun的拼音是：\n\n“gun”在拼音中对应的汉字是“棍”，拼音是：“gùn”\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n。",
>       "logprobs": null,
>       "finish_reason": "stop"
>     }
>   ],
>   "usage": {
>     "prompt_tokens": 1,
>     "total_tokens": 106,
>     "completion_tokens": 105
>   }
> }
> ```

In my case, this problem was solved with the latest vllm
Added logic for `eos_token_id`

https://github.com/vllm-project/vllm/blob/main/vllm/engine/llm_engine.py#L276
```python
        # Create the sequences.
        block_size = self.cache_config.block_size
        seq_id = next(self.seq_counter)
        eos_token_id = self.tokenizer.get_lora_tokenizer(
            lora_request).eos_token_id
        seq = Sequence(seq_id, prompt, prompt_token_ids, block_size,
                       eos_token_id, lora_request)
```

**Comment by JustinLin610** [comment]
Sry for the late response. By updating our chat models, I mean the config files, the problem can be solved. Yeah it is about stop token, and it is hard to setup these things with vLLM openai service. We update the eos_token in `tokenizer_config.json` to `<|im_end|>` and the problem should be solved.

**Comment by JustinLin610** [comment]
I'll close this one. If you still find problems with the latest config lmk

**Comment by HuXinjing** [comment]
> Sry for the late response. By updating our chat models, I mean the config files, the problem can be solved. Yeah it is about stop token, and it is hard to setup these things with vLLM openai service. We update the eos_token in `tokenizer_config.json` to `<|im_end|>` and the problem should be solved.

你好，这个怎么更新？我看已经是<|im_end|>了
