### ISSUE TITLE
是否存在保留的特殊token

### ISSUE THREAD

**Issue by Jerry-hyl** [QwenLM/Qwen1.5#461]
请问qwen1.5模型是否有类似llama3中的<|reserved_special_token_0|>这种保留的特殊token呢？在文件中没有找到。如果没有的话，我应该如何使用这些预留的特殊token呢？

**Comment by jklj077** [comment]
Hi, the short answer is that there are not. But since they are not trained in any way and do not carry meaning, you can just use tokenizer.add_special_tokens and then model.resize_token_embeddings and finally train the model.
