### ISSUE TITLE
用llama-factory full微调, 然后vllm启动, 在用API调用,发现推理停不下来

### ISSUE THREAD

**Issue by chuanzhubin** [QwenLM/Qwen1.5#47]
url = "/v1/chat/completions"

data = {
        # "model": "/gpdata/ideal/download/llama-factory/qwen1.5-0.5B-Chat",
        "model": "qwen",
        # "model": "/gpdata/ideal/moneymarket/Qwen-7B-Chat/",
        # "model": "/gpdata/ideal/moneymarket/ChatGLM3-6B-32k/",
        "messages": openai_bot.messages_base + [
            {
                "role": "user",
                "content": prompt
            }
        ],
        "temperature": 0,
        "top_p": 1,
        "max_length": 100,
        "stream": False,
        # "stop": ["<|im_start|>", "<|im_end|>"],
        # "stop": ["151645","151643"]
        "add_generation_prompt": True,
    }

微调训练参数:
CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage sft \
    --do_train True \
    --model_name_or_path /gpdata/ideal/download/qwen1.5-0.5B-Chat \
    --finetuning_type full \
    --template qwen \
    --dataset_dir data \
    --dataset moneymarket \
    --cutoff_len 1024 \
    --learning_rate 5e-05 \
    --num_train_epochs 3.0 \
    --max_samples 100000 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --max_grad_norm 1.0 \
    --logging_steps 5 \
    --save_steps 100 \
    --warmup_steps 0 \
    --lora_rank 8 \
    --lora_dropout 0.1 \
    --lora_target q_proj,v_proj \
    --output_dir saves/Qwen1.5-0.5B-Chat/full/train_2024-02-18-16-37-04 \
    --fp16 True \
    --val_size 0.1 \
    --evaluation_strategy steps \
    --eval_steps 100 \
    --load_best_model_at_end True \
    --plot_loss True

**Comment by chuanzhubin** [comment]
vllm启动命令:
python -m vllm.entrypoints.openai.api_server --trust-remote-code --dtype="half" --gpu-memory-utilization 0.25 $@ --served-model-name qwen --model /gpdata/ideal/download/llama-factory/saves/Qwen1.5-0.5B-Chat/full/train_2024-02-18-16-37-04

**Comment by chuanzhubin** [comment]
没微调的, 原版用vllm加载能正常推理.
微调后用llama-factory加载, 在web界面上推理也是能正常结束的, 
只有微调后用vllm加载才会出现推理停不下来, 也无法返回正确的结果, 不知道问题出在哪?

**Comment by wangz1200** [comment]
同样的问题，请问解决了吗？

**Comment by chuanzhubin** [comment]
还没有解决.  可以先用pytorch推理.  vllm不行

**Comment by xinzaifeixiang1992** [comment]
我是基于llama-factory用qlora微调qwen1.5-72b-chat后，微调时指定了template为qwen.
微调合并后的模型可以正常直接基于官方qwen1.5进行推理，如果基于vllm进行推理，基于A800-80g*4块。部署时指定了--max-model-len 3000, --gpu-memory-utilization 0.9，会报oom的错误。
根据qwen1.5官方进行awq量化后，就会出现跟大家一样的问题，推理停不下来，而且一直重复。

**Comment by xinzaifeixiang1992** [comment]
> 没微调的, 原版用vllm加载能正常推理. 微调后用llama-factory加载, 在web界面上推理也是能正常结束的, 只有微调后用vllm加载才会出现推理停不下来, 也无法返回正确的结果, 不知道问题出在哪?

检查下微调后保存的tokenizer_config.json文件中，将"eos_token"设置为 "<|im_end|>"，再试一下。

**Comment by chuanzhubin** [comment]
> 同样的问题，请问解决了吗？

在swift社区找到了答案.  https://github.com/modelscope/swift/issues/507
swift微调, 加--save_safetensors false  参数即可解决

**Comment by hxujal** [comment]
> > 同样的问题，请问解决了吗？
> 
> 在swift社区找到了答案. [modelscope/swift#507](https://github.com/modelscope/swift/issues/507) swift微调, 加--save_safetensors false 参数即可解决

在哪里加--save_safetensors false

**Comment by chuanzhubin** [comment]
换swift微调，他有这个参数发自我的荣耀手机-------- 原始邮件 --------发件人： hua zhang ***@***.***>日期： 2024年5月10日周五 10:26收件人： "QwenLM/Qwen1.5" ***@***.***>抄送： Ben ***@***.***>, Author ***@***.***>主    题： Re: [QwenLM/Qwen1.5] 用llama-factory full微调, 然后vllm启动, 在用API调用,发现推理停不下来 (Issue #47)


同样的问题，请问解决了吗？

在swift社区找到了答案. modelscope/swift#507 swift微调, 加--save_safetensors false 参数即可解决

在哪里加--save_safetensors false
