### ISSUE TITLE
请问量化是如何完成的？

### ISSUE THREAD

**Issue by QwertyJack** [QwenLM/Qwen1.5#471]
首先感谢千问团队优秀的工作！

代码库中找到了量化相关的文档，比如[gptq](https://github.com/QwenLM/Qwen1.5/blob/main/docs/source/quantization/gptq.rst)，但是开源出来的量化版本（譬如 [Qwen1.5-72B-Chat-GPTQ-Int4](https://huggingface.co/Qwen/Qwen1.5-72B-Chat-GPTQ-Int4)）貌似使用的 exllama 方式量化的。

问题1：请问如何制作 exllama 格式 gptq 量化模型？
问题2：请问开源出来的量化版本使用的什么数据集进行的校准？

谢谢~

**Comment by jklj077** [comment]
Previously, we have provided GPTQ and AWQ quants and we have not provide quants in the EXL2 format. For Q1, you should refer to the official exllama repo. (To be clear, the exllama and the exllama v2 kernel in `auto_gptq` is not the same as the EXL2 quants in `exllamav2`.)

For Q2, the calibration dataset is based on inhouse data for post-training.

**Comment by QwertyJack** [comment]
Any idea why Qwen1.5-32B-Chat-GPTQ-Int4 does not work with vllm?
