### ISSUE TITLE
VLLM还不支持Qwen1.5是吗？

### ISSUE THREAD

**Issue by Jankin66** [QwenLM/Qwen1.5#49]
### 实现PR | Implementation PR

VLLM还不支持Qwen2ForCausalLM是吗？

### 摘要 | Summary

VLLM还不支持Qwen2ForCausalLM是吗？

### 基本示例 | Basic Example

VLLM还不支持Qwen2ForCausalLM是吗？

### 缺陷 | Drawbacks

VLLM还不支持Qwen2ForCausalLM是吗？

**Comment by 1920853199** [comment]
你解决了吗

**Comment by Jankin66** [comment]
已收到您的信件！

**Comment by Jankin66** [comment]
> 你解决了吗

没有诶

**Comment by JustinLin610** [comment]
It did support. Use `vllm>=0.3.0`, and check qwen.readthedocs.io

**Comment by Jankin66** [comment]
已收到您的信件！
