### ISSUE TITLE
webui可以提供一个支持qwenv1.5的版本么？

### ISSUE THREAD

**Issue by moseshu** [QwenLM/Qwen1.5#51]
现在的webui不支持qwen v1.5版本，能提供一个支持v1.5的版本么？

**Comment by JustinLin610** [comment]
check qwen.readthedocs.io. You can directly use text-generation-webui

**Comment by wangfeng35** [comment]
> check qwen.readthedocs.io. You can directly use text-generation-webui
用20240225版本的TGW测试了下https://huggingface.co/Qwen/Qwen1.5-4B-Chat的四种量化版本GPTQ-INT4,awq,gguf和Qwen1.5-4B-Chat-4.0bpw-h6-exl2，结果如下：
- 只有GPTQ-Int4 是可以正常加载且使用的；
- AWQ版本不支持，提示qwen2 not support yet；
- GGUF可以导入，设置n_ctx 8192，rope_freq_base 1000000，compress_pos_emb 4 可以导入，但是回复明显不正常，无法正常使用；
- 4.0bpw-h6-exl2 版本，ExLlamav2&ExLlamav2_HF加载器，设置 max_seq_len 8192 compress_pos_emb 4能导入，但是无法正常回答

上面无法正常工作的版本如果有特殊设置还请告知，谢谢！

**Comment by JustinLin610** [comment]
Also, now we have our own webui similar to Qwen1's. AWQ not supported problem, you need to update your AutoAWQ. GGUF behaviors are strange in TGW. No idea why now.
