### ISSUE TITLE
有同学部署qwen1.5可以正常聊天吗

### ISSUE THREAD

**Issue by ticoAg** [QwenLM/Qwen1.5#52]
使用`FastChat`部署的api/web，chat/completion 都会提前结束，看起来像是未生成完，`apply_chat_template`后使用completion也会

使用`vllm.entrypoints.openai.api_server`会生成很多`\n`，尝试了issue里的方法还没有发现work的,直接把`\n`作为stop有点顾此失彼,不过`qwen/Qwen1.5-14B-Chat`没有这个情况，`qwen/Qwen1.5-14B-Chat-GPTQ-Int4`偶尔有, `qwen/Qwen1.5-72B-Chat-GPTQ-Int4`严重,`4B-Chat`和GPTQ-Int4严重
```python
messages = [{"role": "user", "content": "你是什么模型？"}]
response = openai.ChatCompletion.create(
    model=model_id,
    messages=messages,
    top_k=50,
    top_p=0.7,
    repetition_penalty=1,
    temperature=0.7,
    max_tokens=512,
    stream=True
)
```

**Comment by junjzhang** [comment]
14B-chat没有这个问题吗？我的14B-chat改了system message问题就很大

**Comment by alphaply** [comment]
你好，我建议使用https://github.com/oobabooga/text-generation-webui

**Comment by MOLIZHU2023** [comment]
> 你好，我建议使用https://github.com/oobabooga/text-generation-webui

你好。我正在使用这个部署，好像可以正常使用，就想请问一下需要在里面设置什么可以更好地使用Qwen1,5吗？

**Comment by sanixa** [comment]
When deploying the Qwen 1.5 model with FastChat, everything can be completed smoothly, but there is an issue of incomplete output during usage. This is because there is an error in the output of a certain line of code. The content of token_ids is inconsistent with the text content, and the content of token_ids is the correct output.

code: https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/vllm_worker.py#L128
One example of "**request_output.outputs**" is `[CompletionOutput(index=0, text='Tom886', token_ids=[24732, 23, 23, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 151645], cumulative_logprob=0.0, logprobs=None, finish_reason=stop)]`

The temporary solution is to modify line 128 to `text_outputs = [self.tokenizer.decode(output.token_ids[:-1]) for output in request_output.outputs]`

**Comment by ticoAg** [comment]
tks, I'll have a try.

**Comment by ticoAg** [comment]
> When deploying the Qwen 1.5 model with FastChat, everything can be completed smoothly, but there is an issue of incomplete output during usage. This is because there is an error in the output of a certain line of code. The content of token_ids is inconsistent with the text content, and the content of token_ids is the correct output.
> 
> code: https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/vllm_worker.py#L128 One example of "**request_output.outputs**" is `[CompletionOutput(index=0, text='Tom886', token_ids=[24732, 23, 23, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 151645], cumulative_logprob=0.0, logprobs=None, finish_reason=stop)]`
> 
> The temporary solution is to modify line 128 to `text_outputs = [self.tokenizer.decode(output.token_ids[:-1]) for output in request_output.outputs]`
> 
> package: fastchat==0.2.36, vllm==0.3.1

right, while `request_output.outputs[0].finish_reason == 'stop'` the `request_output.outputs[0].text` is not equal to `request_output.outputs[0].token_ids`

**Comment by ticoAg** [comment]
Qwen-1_8B-Chat:
![image](https://github.com/QwenLM/Qwen1.5/assets/73207855/e7653b00-2542-4745-a03f-ef900b1ca349)
Qwen1.5-1.8B-Chat:
![image](https://github.com/QwenLM/Qwen1.5/assets/73207855/755d05e1-3671-4efb-a56c-efdcbcf2def9)

**Comment by wangfeng35** [comment]
> 你好，我建议使用https://github.com/oobabooga/text-generation-webui

用20240225版本的TGW测试了下https://huggingface.co/Qwen/Qwen1.5-4B-Chat 的四种量化版本GPTQ-INT4,awq,gguf和Qwen1.5-4B-Chat-4.0bpw-h6-exl2，结果如下：

- 只有GPTQ-Int4 是可以正常加载且使用的；
- AWQ版本不支持，提示qwen2 not support yet；
- GGUF可以导入，设置n_ctx 8192，rope_freq_base 1000000，compress_pos_emb 4 可以导入，但是回复明显不正常，无法正常使用；
- 4.0bpw-h6-exl2 版本，ExLlamav2&ExLlamav2_HF加载器，设置 max_seq_len 8192 compress_pos_emb 4能导入，但是无法正常回答

上面无法正常工作的版本如果有特殊设置还请告知，谢谢！

**Comment by QuantJia** [comment]
> 使用`FastChat`部署的api/web，chat/completion 都会提前结束，看起来像是未生成完，`apply_chat_template`后使用completion也会
> 
> 使用`vllm.entrypoints.openai.api_server`会生成很多`\n`，尝试了issue里的方法还没有发现work的,直接把`\n`作为stop有点顾此失彼,不过`qwen/Qwen1.5-14B-Chat`没有这个情况，`qwen/Qwen1.5-14B-Chat-GPTQ-Int4`偶尔有, `qwen/Qwen1.5-72B-Chat-GPTQ-Int4`严重,`4B-Chat`和GPTQ-Int4严重
> 
> ```python
> messages = [{"role": "user", "content": "你是什么模型？"}]
> response = openai.ChatCompletion.create(
>     model=model_id,
>     messages=messages,
>     top_k=50,
>     top_p=0.7,
>     repetition_penalty=1,
>     temperature=0.7,
>     max_tokens=512,
>     stream=True
> )
> ```

可以 stream 输出么?
