### ISSUE TITLE
支持function call吗

### ISSUE THREAD

**Issue by xianzhisheng** [QwenLM/Qwen1.5#55]
1.5版本的模型支持functon call吗，我用之前qwen的例子试了一下，好像不行。我用的是llama_cpp部署的gguf，是姿势不对吗

**Comment by JianxinMa** [comment]
模型是支持的。有例子吗，我们看下是代码问题还是模型效果问题。

**Comment by xianzhisheng** [comment]
这是代码
```
from openai import OpenAI
functions = [{
        'name': 'get_current_weather',
        'description': 'Get the current weather in a given location.',
        'parameters': {
            'type': 'object',
            'properties': {
                'location': {
                    'type': 'string',
                    'description':
                    'The city and state, e.g. San Francisco, CA',
                },
                'unit': {
                    'type': 'string',
                    'enum': ['celsius', 'fahrenheit']
                },
            },
            'required': ['location'],
        },
    }]
def get_answer(query):
    client = OpenAI(
        api_key='sk',
        base_url='http://localhost:8088/v1/',
    )

    response =client.chat.completions.create(
            model='qwen1_5-1_8b',
            messages=[{'role':'user','content':query}], 
            functions=functions
            #stream=True
            )

    return response

while True:
    query = input('user:')
    response = get_answer(query)
    print(response)
    print(f'bot:{response.choices[0].message.content}')
   
```

这是输出

```
user:查一下北京的天气
ChatCompletion(id='chatcmpl-1BpGD3r2XOxJMf604jj9BEvwBS3A5U8z', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='北京的天气查询如下：\n\n日期：2023年1月1日\n\n当前天气：\n北京市，晴\n气温：-4℃至8℃\n风速：微风\n\n未来预报：\n预计今天白天到夜 间，北京市将维持晴朗天气，气温逐渐下降。预计明天白天最高气温为6℃，最低气温为-5℃，请注意保暖。\n\n具体天气情况可能会受到多种因素影响，如气压、湿度、风向等，建议您关注最新的气象信息或使用专业的天气预报软件获取更准确的天气预报数据。同时，由于北京地处北方地区，冬季气候较为寒冷，出门时应携带适当 的防寒衣物和保暖用品，以确保身体安全和舒适度。', role='assistant', function_call=None, tool_calls=None))], created=1708330424, model='qwen1_5-1_8b', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=152, prompt_tokens=13, total_tokens=165))
bot:北京的天气查询如下：

日期：2023年1月1日

当前天气：
北京市，晴
气温：-4℃至8℃
风速：微风

未来预报：
预计今天白天到夜间，北京市将维持晴朗天气，气温逐渐下降。预计明天白天最高气温为6℃，最低气温为-5℃，请注意保暖。

具体天气情况可能会受到多种因素影响，如气压、湿度、风向等，建议您关注最新的气象信息或使用专业的天气预报软件获取更准确的天气预报数据。同时，由于北京 地处北方地区，冬季气候较为寒冷，出门时应携带适当的防寒衣物和保暖用品，以确保身体安全和舒适度。
user:上海天气如何
ChatCompletion(id='chatcmpl-tMK5PGB5peYSrEZAHcVdwKxMwOpagQ0B', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='上海的天气情况因季节和地理位置而异，以下是一般情况下上海的天气状况：\n\n1. 春季（3月至5月）：春季是上海气候较为温和的时期，平均气 温在20-28℃之间。此时，雨水较多，但不会持续太久，一般在一周左右。白天阳光明媚，夜晚较凉爽，适宜户外活动和旅游。\n\n2. 夏季（6月至8月）：夏季是上海 最热的季节，平均气温在30-35℃之间。白天高温炎热，夜晚稍有凉爽，但仍然需要注意防晒和防暑降温。此时，雨水较多，有时会出现雷阵雨或暴雨天气，需要做好防范措施。\n\n3. 秋季（9月至11月）：秋季是上海的多雨季节，平均气温在20-25℃之间。白天晴朗，夜晚较凉爽，适宜户外活动和旅游。此时，雨水较多，有时会出现台风或寒潮天气，需要做好防风保暖措施。\n\n4. 冬季（12月至次年2月）：冬季是上海最冷的季节，平均气温在0-5℃之间。白天寒冷，夜晚较暖和，但仍然需要注意保暖和防冻。此时，雨水较少，有时会出现霜冻或雪天气，需要做好防寒保暖措施。\n\n总的来说，上海的四季气候较为温和，雨量适中，适合各种户外活动和旅游。 但在不同季节，需要注意防晒、防暑降温、防风保暖等事项，以确保安全和舒适。建议在出行前查询最新的天气预报信息，以便做出相应的准备。', role='assistant', function_call=None, tool_calls=None))], created=1708330549, model='qwen1_5-1_8b', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=346, prompt_tokens=11, total_tokens=357))
bot:上海的天气情况因季节和地理位置而异，以下是一般情况下上海的天气状况：

1. 春季（3月至5月）：春季是上海气候较为温和的时期，平均气温在20-28℃之间。此时，雨水较多，但不会持续太久，一般在一周左右。白天阳光明媚，夜晚较凉爽 ，适宜户外活动和旅游。

2. 夏季（6月至8月）：夏季是上海最热的季节，平均气温在30-35℃之间。白天高温炎热，夜晚稍有凉爽，但仍然需要注意防晒和防暑降温。此时，雨水较多，有时会 出现雷阵雨或暴雨天气，需要做好防范措施。

3. 秋季（9月至11月）：秋季是上海的多雨季节，平均气温在20-25℃之间。白天晴朗，夜晚较凉爽，适宜户外活动和旅游。此时，雨水较多，有时会出现台风或寒潮天气，需要做好防风保暖措施。

4. 冬季（12月至次年2月）：冬季是上海最冷的季节，平均气温在0-5℃之间。白天寒冷，夜晚较暖和，但仍然需要注意保暖和防冻。此时，雨水较少，有时会出现霜冻或雪天气，需要做好防寒保暖措施。

总的来说，上海的四季气候较为温和，雨量适中，适合各种户外活动和旅游。但在不同季节，需要注意防晒、防暑降温、防风保暖等事项，以确保安全和舒适。建议在 出行前查询最新的天气预报信息，以便做出相应的准备。```

**Comment by JianxinMa** [comment]
qwen1.5目前提供的openai兼容接口还没有实现function calling的工程支持。

如 Qwen1.5的README 所说：

- Neither vLLM nor SGLang currently offer built-in support for function calling. If you require tool use capabilities, please refer to [Qwen-Agent](https://github.com/QwenLM/Qwen-Agent), which provides a wrapper around these APIs to support function calling.

**Comment by SDcodehub** [comment]
@xianzhisheng can you provide chat template for this?

**Comment by JianxinMa** [comment]
> @xianzhisheng can you provide chat template for this?

Function calling is implemented through prompt engineering. Simply replacing the chat template won't do. Please see this example: https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling.py and delve into its implementation if you're interested.

**Comment by mru4913** [comment]
> 这是代码
> 
> ```
> from openai import OpenAI
> functions = [{
>         'name': 'get_current_weather',
>         'description': 'Get the current weather in a given location.',
>         'parameters': {
>             'type': 'object',
>             'properties': {
>                 'location': {
>                     'type': 'string',
>                     'description':
>                     'The city and state, e.g. San Francisco, CA',
>                 },
>                 'unit': {
>                     'type': 'string',
>                     'enum': ['celsius', 'fahrenheit']
>                 },
>             },
>             'required': ['location'],
>         },
>     }]
> def get_answer(query,functions ):
>     client = OpenAI(
>         api_key='sk',
>         base_url='http://localhost:8088/v1/',
>     )
> 
>     response =client.chat.completions.create(
>             model='qwen1_5-1_8b',
>             messages=[{'role':'user','content':query}], 
>             functions=functions
>             #stream=True
>             )
> 
>     return response
> 
> while True:
>     query = input('user:')
>     response = get_answer(query,functions )
>     print(response)
>     print(f'bot:{response.choices[0].message.content}')
>    
> ```
> 
> 这是输出
> 
> ```
> user:查一下北京的天气
> ChatCompletion(id='chatcmpl-1BpGD3r2XOxJMf604jj9BEvwBS3A5U8z', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='北京的天气查询如下：\n\n日期：2023年1月1日\n\n当前天气：\n北京市，晴\n气温：-4℃至8℃\n风速：微风\n\n未来预报：\n预计今天白天到夜 间，北京市将维持晴朗天气，气温逐渐下降。预计明天白天最高气温为6℃，最低气温为-5℃，请注意保暖。\n\n具体天气情况可能会受到多种因素影响，如气压、湿度、风向等，建议您关注最新的气象信息或使用专业的天气预报软件获取更准确的天气预报数据。同时，由于北京地处北方地区，冬季气候较为寒冷，出门时应携带适当 的防寒衣物和保暖用品，以确保身体安全和舒适度。', role='assistant', function_call=None, tool_calls=None))], created=1708330424, model='qwen1_5-1_8b', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=152, prompt_tokens=13, total_tokens=165))
> bot:北京的天气查询如下：
> 
> 日期：2023年1月1日
> 
> 当前天气：
> 北京市，晴
> 气温：-4℃至8℃
> 风速：微风
> 
> 未来预报：
> 预计今天白天到夜间，北京市将维持晴朗天气，气温逐渐下降。预计明天白天最高气温为6℃，最低气温为-5℃，请注意保暖。
> 
> 具体天气情况可能会受到多种因素影响，如气压、湿度、风向等，建议您关注最新的气象信息或使用专业的天气预报软件获取更准确的天气预报数据。同时，由于北京 地处北方地区，冬季气候较为寒冷，出门时应携带适当的防寒衣物和保暖用品，以确保身体安全和舒适度。
> user:上海天气如何
> ChatCompletion(id='chatcmpl-tMK5PGB5peYSrEZAHcVdwKxMwOpagQ0B', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='上海的天气情况因季节和地理位置而异，以下是一般情况下上海的天气状况：\n\n1. 春季（3月至5月）：春季是上海气候较为温和的时期，平均气 温在20-28℃之间。此时，雨水较多，但不会持续太久，一般在一周左右。白天阳光明媚，夜晚较凉爽，适宜户外活动和旅游。\n\n2. 夏季（6月至8月）：夏季是上海 最热的季节，平均气温在30-35℃之间。白天高温炎热，夜晚稍有凉爽，但仍然需要注意防晒和防暑降温。此时，雨水较多，有时会出现雷阵雨或暴雨天气，需要做好防范措施。\n\n3. 秋季（9月至11月）：秋季是上海的多雨季节，平均气温在20-25℃之间。白天晴朗，夜晚较凉爽，适宜户外活动和旅游。此时，雨水较多，有时会出现台风或寒潮天气，需要做好防风保暖措施。\n\n4. 冬季（12月至次年2月）：冬季是上海最冷的季节，平均气温在0-5℃之间。白天寒冷，夜晚较暖和，但仍然需要注意保暖和防冻。此时，雨水较少，有时会出现霜冻或雪天气，需要做好防寒保暖措施。\n\n总的来说，上海的四季气候较为温和，雨量适中，适合各种户外活动和旅游。 但在不同季节，需要注意防晒、防暑降温、防风保暖等事项，以确保安全和舒适。建议在出行前查询最新的天气预报信息，以便做出相应的准备。', role='assistant', function_call=None, tool_calls=None))], created=1708330549, model='qwen1_5-1_8b', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=346, prompt_tokens=11, total_tokens=357))
> bot:上海的天气情况因季节和地理位置而异，以下是一般情况下上海的天气状况：
> 
> 1. 春季（3月至5月）：春季是上海气候较为温和的时期，平均气温在20-28℃之间。此时，雨水较多，但不会持续太久，一般在一周左右。白天阳光明媚，夜晚较凉爽 ，适宜户外活动和旅游。
> 
> 2. 夏季（6月至8月）：夏季是上海最热的季节，平均气温在30-35℃之间。白天高温炎热，夜晚稍有凉爽，但仍然需要注意防晒和防暑降温。此时，雨水较多，有时会 出现雷阵雨或暴雨天气，需要做好防范措施。
> 
> 3. 秋季（9月至11月）：秋季是上海的多雨季节，平均气温在20-25℃之间。白天晴朗，夜晚较凉爽，适宜户外活动和旅游。此时，雨水较多，有时会出现台风或寒潮天气，需要做好防风保暖措施。
> 
> 4. 冬季（12月至次年2月）：冬季是上海最冷的季节，平均气温在0-5℃之间。白天寒冷，夜晚较暖和，但仍然需要注意保暖和防冻。此时，雨水较少，有时会出现霜冻或雪天气，需要做好防寒保暖措施。
> 
> 总的来说，上海的四季气候较为温和，雨量适中，适合各种户外活动和旅游。但在不同季节，需要注意防晒、防暑降温、防风保暖等事项，以确保安全和舒适。建议在 出行前查询最新的天气预报信息，以便做出相应的准备。```
> ```

你这个使用时openai脚本启动的部署还是vllm？

**Comment by MarchLiu** [comment]
能否提供一下json示例？我尝试了几种结构组合都没有触发函数调用

```sh
curl -X POST --location "http://localhost:11434/api/chat" \
    -H "Content-Type: application/json" \
    -d '{
          "model": "qwen2:72b",
          "messages": [
            {
              "role": "user",
              "content": "how to list functions for you used them"
            }
          ],
          "stream": false,
          "functions": [
            {
              "name":"get_current_weather",
              "description": "Get the current weather for a location",
              "parameters": {
                "type": "object",
                "properties": {
                  "location": {
                    "type": "string",
                    "description": "The location to get the weather for, e.g. San Francisco, CA"
                  },
                  "format": {
                    "type": "string",
                    "description": "The format to return the weather in, e.g. 'celsius' or 'fahrenheit'",
                    "enum": [
                      "celsius",
                      "fahrenheit"
                    ]
                  }
                },
                "required": [
                  "location",
                  "format"
                ]
              }
            }
          ]
        }'
```
得到的是：
```json
{
  "model": "qwen2:72b",
  "created_at": "2024-07-28T15:06:26.545469Z",
  "message": {
    "role": "assistant",
    "content": "To list the functions that I've previously used or referenced, there isn't a direct way since our interaction is based on text and not code. However, if you're referring to listing functions in a programming environment, here's how it can be done in some popular languages:\n\n1. **Python**:\n   Python doesn't have a built-in way to list all the functions globally, but you can use `globals()` or `dir()` to get an idea of what's available within the current scope.\n\n   ```python\n   print(globals())\n   ```\n\n2. **JavaScript (in Node.js)**:\n   JavaScript similarly does not provide a direct method to list all global functions, but you can inspect the global object (`window` in browsers or `global` in Node.js).\n\n   ```javascript\n   console.log(Object.getOwnPropertyNames(global));\n   ```\n\n3. **Java**:\n   Java doesn't have a built-in function to list all methods in a class. However, you could use reflection for this purpose:\n\n   ```java\n   import java.lang.reflect.Method;\n\n   public class ListFunctions {\n       public static void main(String[] args) {\n           Method[] methods = SomeClass.class.getDeclaredMethods();\n           for (Method method : methods) {\n               System.out.println(method.getName());\n           }\n       }\n   }\n   ```\n\n4. **C#**:\n   Similar to Java, C# can use reflection to list the methods of a class:\n\n   ```csharp\n   using System;\n   using System.Reflection;\n\n   public class ListFunctions {\n       static void Main() {\n           Type type = typeof(YourClass);\n           MethodInfo[] methodInfos = type.GetMethods();\n           foreach (var info in methodInfos) {\n               Console.WriteLine(info.Name);\n           }\n       }\n   }\n   ```\n\n5. **Ruby**:\n   Ruby's `ObjectSpace` class can be used to list all global objects including methods:\n\n   ```ruby\n   require 'ostruct'\n   ObjectSpace.each_object do |object|\n     puts object if object.is_a?(Method)\n   end\n   ```\n\nRemember, these are not exact equivalents and have limitations. The examples provided mainly help you understand how to approach listing functions or methods within a specific language's context.\n\nIf you meant something else by \"list functions for you used them,\" please provide more details so I can assist you further!"
  },
  "done_reason": "stop",
  "done": true,
  "total_duration": 61058302625,
  "load_duration": 30621625,
  "prompt_eval_count": 16,
  "prompt_eval_duration": 1457504000,
  "eval_count": 482,
  "eval_duration": 59568674000
}
```

**Comment by JianxinMa** [comment]
> 能否提供一下json示例？我尝试了几种结构组合都没有触发函数调用
> 
> ```shell
> curl -X POST --location "http://localhost:11434/api/chat" \
>     -H "Content-Type: application/json" \
>     -d '{
>           "model": "qwen2:72b",
>           "messages": [
>             {
>               "role": "user",
>               "content": "What is the weather today in Paris?"
>             }
>           ],
>           "stream": false,
>           "functions": [
>             {
>               "name":"get_current_weather",
>               "description": "Get the current weather for a location",
>               "parameters": {
>                 "type": "object",
>                 "properties": {
>                   "location": {
>                     "type": "string",
>                     "description": "The location to get the weather for, e.g. San Francisco, CA"
>                   },
>                   "format": {
>                     "type": "string",
>                     "description": "The format to return the weather in, e.g. 'celsius' or 'fahrenheit'",
>                     "enum": [
>                       "celsius",
>                       "fahrenheit"
>                     ]
>                   }
>                 },
>                 "required": [
>                   "location",
>                   "format"
>                 ]
>               }
>             }
>           ]
>         }'
> ```
> 
> 得到的是：
> 
> ```json
> {
>   "model": "qwen2:72b",
>   "created_at": "2024-07-28T15:08:09.338279Z",
>   "message": {
>     "role": "assistant",
>     "content": "I'm sorry, but as an AI assistant I don't have real-time data access to current weather conditions. However, you can check a reliable weather website or app for the most up-to-date information about the weather in Paris today. Some popular options include the Weather Channel, AccuWeather, and BBC Weather. Alternatively, you could try searching for \"current weather in Paris\" on your preferred search engine."
>   },
>   "done_reason": "stop",
>   "done": true,
>   "total_duration": 12078121333,
>   "load_duration": 23651417,
>   "prompt_eval_count": 16,
>   "prompt_eval_duration": 2112329000,
>   "eval_count": 83,
>   "eval_duration": 9941045000
> }
> ```

ollama的tool call实现目前还没有支持上qwen2，需要开发。
