### ISSUE TITLE
Qwen1.5-1.8B-Chat转换成gguf报错

### ISSUE THREAD

**Issue by anaivebird** [QwenLM/Qwen1.5#57]
需求是在cpu上对Qwen1.5-1.8B-Chat进行推理，打算使用llama.cpp，首先要转换为gguf，步骤如下：
C:\Users\THINK\Downloads\llama.cpp-master>python convert.py C:\Users\THINK\Downloads\Qwen1.5-1.8B-Chat

Loading model file C:\Users\THINK\Downloads\Qwen1.5-1.8B-Chat\model.safetensors
params = Params(n_vocab=151936, n_embd=2048, n_layer=24, n_ctx=32768, n_ff=5504, n_head=16, n_head_kv=16, n_experts=None, n_experts_used=None, f_norm_eps=1e-06, rope_scaling_type=None, f_rope_freq_base=1000000.0, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=None, path_model=WindowsPath('C:/Users/THINK/Downloads/Qwen1.5-1.8B-Chat'))
Found vocab files: {'tokenizer.model': None, 'vocab.json': WindowsPath('C:/Users/THINK/Downloads/Qwen1.5-1.8B-Chat/vocab.json'), 'tokenizer.json': WindowsPath('C:/Users/THINK/Downloads/Qwen1.5-1.8B-Chat/tokenizer.json')}
Loading vocab file 'C:\Users\THINK\Downloads\Qwen1.5-1.8B-Chat\vocab.json', type 'spm'
Traceback (most recent call last):
  File "C:\Users\THINK\Downloads\llama.cpp-master\convert.py", line 1483, in <module>
    main()
  File "C:\Users\THINK\Downloads\llama.cpp-master\convert.py", line 1451, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type, model_parent_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THINK\Downloads\llama.cpp-master\convert.py", line 1336, in load_vocab
    vocab = SentencePieceVocab(
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THINK\Downloads\llama.cpp-master\convert.py", line 394, in __init__
    self.sentencepiece_tokenizer = SentencePieceProcessor(str(fname_tokenizer))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THINK\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentencepiece\__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "C:\Users\THINK\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentencepiece\__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\THINK\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentencepiece\__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal: D:\a\sentencepiece\sentencepiece\src\sentencepiece_processor.cc(1102) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by anaivebird** [comment]
是否要convert.py --vocab-type hfft？能否提供转换命令

**Comment by anaivebird** [comment]
convert.py --vocab-type hfft之后报错如下：
Writing /root/jiwei/llm_rh/hxw/qwen/Qwen1.5-1.8B-Chat/ggml-model-f16.gguf, format 1
Traceback (most recent call last):
  File "/data/jiwei/llm_rh/hxw/qwen/llama.cpp/convert.py", line 1485, in <module>
    main()
  File "/data/jiwei/llm_rh/hxw/qwen/llama.cpp/convert.py", line 1479, in main
    OutputFile.write_all(outfile, ftype, params, model, vocab, special_vocab,
  File "/data/jiwei/llm_rh/hxw/qwen/llama.cpp/convert.py", line 1117, in write_all
    check_vocab_size(params, vocab, pad_vocab=pad_vocab)
  File "/data/jiwei/llm_rh/hxw/qwen/llama.cpp/convert.py", line 963, in check_vocab_size
    raise Exception(msg)
Exception: Vocab size mismatch (model has 151936, but /root/jiwei/llm_rh/hxw/qwen/Qwen1.5-1.8B-Chat has 151646). Add the --pad-vocab option and try again.

**Comment by riverzhou** [comment]
转换程序是这个 convert-hf-to-gguf.py

**Comment by anaivebird** [comment]
convert-hf-to-gguf.py可以转换不报错，但是推理结果异常

**Comment by riverzhou** [comment]
> convert-hf-to-gguf.py可以转换不报错，但是推理结果异常

这个要 @simonJJJ 查一下原因，我用 llama.cpp 也推理一直不正常。

**Comment by JustinLin610** [comment]
check qwen.readthedocs.io. Things should work fine with `convert-hf-to-gguf.py`. You can report the problematic cases and see if I can reproduce them. 

And why not directly use our provided GGUF? https://huggingface.co/Qwen/Qwen1.5-1.8B-Chat-GGUF

**Comment by anaivebird** [comment]
> check qwen.readthedocs.io. Things should work fine with `convert-hf-to-gguf.py`. You can report the problematic cases and see if I can reproduce them.
> 
> And why not directly use our provided GGUF? https://huggingface.co/Qwen/Qwen1.5-1.8B-Chat-GGUF

I need use my finetuned qwen1.5-1.8B model and I found qwen1 works with convert script but qwen1.5-1.8B has wrong inference result, you could reproduce it with official qwen1.5-1.8B checkpoint

**Comment by riverzhou** [comment]
> check qwen.readthedocs.io. Things should work fine with `convert-hf-to-gguf.py`. You can report the problematic cases and see if I can reproduce them.
> 
> And why not directly use our provided GGUF? https://huggingface.co/Qwen/Qwen1.5-1.8B-Chat-GGUF

做了仔细的反复测试：
1，用官方转好的GGUF, llama.cpp的推理是正常的(一定要加 -cml 参数)，效果和vllm推理的结果基本一致。
2，如果是自己转(convert-hf-to-gguf.py)，那么推理生成的内容会短很多，大约只有1/3左右的样子(gguf文件看上去主要的不同在于tokenizer.chat_template)。

**Comment by sorasoras** [comment]
Same, I need to use finetuned qwen1.5 on llama.cpp
I guess convert-hf-to-gguf.py does not treat tokenizer correctly just like last time with qwen1.
 fixing convert-hf-to-gguf.py on the llama.cpp repo is needed.


> check qwen.readthedocs.io. Things should work fine with `convert-hf-to-gguf.py`. You can report the problematic cases and see if I can reproduce them.
> 
> And why not directly use our provided GGUF? https://huggingface.co/Qwen/Qwen1.5-1.8B-Chat-GGUF

No, model convert with convert-hf-to-gguf.py gguf would bug out if longer prompt is input.
transformer work fine through.

**Comment by JustinLin610** [comment]
now this script should work? we just use the official script now to build the gguf files
