### ISSUE TITLE
[BUG] Qwen1.5-1.8B-Chat转换成gguf报错

### ISSUE THREAD

**Issue by anaivebird** [QwenLM/Qwen1.5#59]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

需求是在cpu上对Qwen1.5-1.8B-Chat进行推理，打算使用llama.cpp，首先要转换为gguf，步骤如下：
C:\Users\THINK\Downloads\llama.cpp-master>python convert.py C:\Users\THINK\Downloads\Qwen1.5-1.8B-Chat

Loading model file C:\Users\THINK\Downloads\Qwen1.5-1.8B-Chat\model.safetensors
params = Params(n_vocab=151936, n_embd=2048, n_layer=24, n_ctx=32768, n_ff=5504, n_head=16, n_head_kv=16, n_experts=None, n_experts_used=None, f_norm_eps=1e-06, rope_scaling_type=None, f_rope_freq_base=1000000.0, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=None, path_model=WindowsPath('C:/Users/THINK/Downloads/Qwen1.5-1.8B-Chat'))
Found vocab files: {'tokenizer.model': None, 'vocab.json': WindowsPath('C:/Users/THINK/Downloads/Qwen1.5-1.8B-Chat/vocab.json'), 'tokenizer.json': WindowsPath('C:/Users/THINK/Downloads/Qwen1.5-1.8B-Chat/tokenizer.json')}
Loading vocab file 'C:\Users\THINK\Downloads\Qwen1.5-1.8B-Chat\vocab.json', type 'spm'
Traceback (most recent call last):
File "C:\Users\THINK\Downloads\llama.cpp-master\convert.py", line 1483, in
main()
File "C:\Users\THINK\Downloads\llama.cpp-master\convert.py", line 1451, in main
vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type, model_parent_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\THINK\Downloads\llama.cpp-master\convert.py", line 1336, in load_vocab
vocab = SentencePieceVocab(
^^^^^^^^^^^^^^^^^^^
File "C:\Users\THINK\Downloads\llama.cpp-master\convert.py", line 394, in init
self.sentencepiece_tokenizer = SentencePieceProcessor(str(fname_tokenizer))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\THINK\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentencepiece_init_.py", line 447, in Init
self.Load(model_file=model_file, model_proto=model_proto)
File "C:\Users\THINK\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentencepiece_init_.py", line 905, in Load
return self.LoadFromFile(model_file)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\THINK\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentencepiece_init_.py", line 310, in LoadFromFile
return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal: D:\a\sentencepiece\sentencepiece\src\sentencepiece_processor.cc(1102) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

### 复现方法 | Steps To Reproduce

git clone https://github.com/ggerganov/llama.cpp
python convert.py C:\Users\THINK\Downloads\Qwen1.5-1.8B-Chat

**Comment by riverzhou** [comment]
用错了转换程序，是这个 convert-hf-to-gguf.py

**Comment by anaivebird** [comment]
用convert-hf-to-gguf.py可以转换不报错，但是推理结果也异常

**Comment by riverzhou** [comment]
> 用convert-hf-to-gguf.py可以转换不报错，但是推理结果也异常

这个要 @simonJJJ 查一下原因，我用 llama.cpp 也推理一直不正常。

**Comment by JustinLin610** [comment]
https://qwen.readthedocs.io/en/latest/run_locally/llama.cpp.html
https://qwen.readthedocs.io/en/latest/quantization/gguf.html

**Comment by 64933988** [comment]
> 用convert-hf-to-gguf.py可以转换不报错，但是推理结果也异常

me too
