### ISSUE TITLE
[BUG] Qwen1.5-72B-Chat gguf 乱回答

### ISSUE THREAD

**Issue by zhengxingmao** [QwenLM/Qwen1.5#60]
![image](https://github.com/QwenLM/Qwen1.5/assets/40750002/b943901c-fbad-4e5e-a1ea-d9bee1fd3bdd)
llama.cpp version_20240219
转换函数：
python3 convert-hf-to-gguf.py 
量化：
Q4_K_M

**Comment by anaivebird** [comment]
同样问题，不量化也是一样

**Comment by riverzhou** [comment]
感觉是 llama.cpp 对千问的支持有问题，14B的版本推理也不正常。

**Comment by JustinLin610** [comment]
Check qwen.readthedocs.io 

And advise you to use ours https://huggingface.co/Qwen/Qwen1.5-14B-Chat-GGUF

**Comment by riverzhou** [comment]
> Check qwen.readthedocs.io
> 
> And advise you to use ours https://huggingface.co/Qwen/Qwen1.5-14B-Chat-GGUF

用llamap.cpp 推理 Qwen1.5-14B-Chat，生成的内容长度要远小于用 vllm 推理的结果，大约只有 1/2 ~ 1/3的样子。

**Comment by zhengxingmao** [comment]
不知道是不是和这个变更有关，https://huggingface.co/Qwen/Qwen1.5-72B-Chat/commit/bc11a298a0c6a5cd737064db62c6ad20ec6331be
我目前使用官网提供的GGUF运行看是正常的。
