### ISSUE TITLE
速度比qwen变慢了很多

### ISSUE THREAD

**Issue by 1920853199** [QwenLM/Qwen1.5#64]
Qwen1.5-72b-chat 推理速度 比 Qwen-72b-chat 慢很多，大家有这种情况吗

**Comment by hljjjmssyh** [comment]
是不是用的float32?

**Comment by JustinLin610** [comment]
torch_dtype='auto'. Check the latest readme

**Comment by bingwork** [comment]
same to me, still no output.

**Comment by JeckerWen** [comment]
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", torch_dtype=torch.bfloat16, use_cache=True) 显示设置为torch_dtype=torch.bfloat16推理速度会快40%左右，显存也会降很多。 不过推理速度依旧很慢

**Comment by Rssevenyu** [comment]
> model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", torch_dtype=torch.bfloat16, use_cache=True) 显示设置为torch_dtype=torch.bfloat16推理速度会快40%左右，显存也会降很多。 不过推理速度依旧很慢

请问，这条语句在哪里修改？
