### ISSUE TITLE
Auto-GPTQ qwen2 not support yet

### ISSUE THREAD

**Issue by su-zelong** [QwenLM/Qwen1.5#65]
请问我可以正常使用Auto-GPTQ量化 qwen-14b-chat 但是换到qwen-1.5-14bchat就会报错 qwen2 not support yet 是什么原因？Transformers已经更新到 4.37.2

**Comment by hzhwcmhf** [comment]
请升级autogptq到0.7.0

**Comment by su-zelong** [comment]
> 请升级autogptq到0.7.0

非常感谢

**Comment by Fred199683** [comment]
请问你后续量化成功了吗？我这边升级到0.7.0后量化的avg loss为nan，该怎么办呢？

**Comment by huang-zihan** [comment]
我也遇到这个问题，发现是因为attention weight计算溢出导致的。
可以修改transformers/src/transformers/models/qwen2/modeling_qwen2.py：
找到
`attn_weights = torch.matmul(query_states, key_states.transpose(2, 3)) / math.sqrt(self.head_dim)`
在后面添加
`if attn_weights.dtype == torch.float16:
            max_dtype = torch.finfo(attn_weights.dtype).max
            clamp_value = torch.where(torch.isinf(attn_weights).any(), max_dtype - 1000, max_dtype)
            attn_weights = torch.clamp(attn_weights, min=-clamp_value, max=clamp_value)`

**Comment by Alex-Songs** [comment]
@huang-zihan 请问我是微调Qwen2，用的bf16，训练一段时间后loss=nan，这个有什么方法解决吗？

**Comment by huang-zihan** [comment]
@su-zelong 你可以打印attn_weights看是否发生溢出。如果溢出就是相同的问题，可以尝试上面提的方法，或者对下面这条式子的分子分母同时等比例缩小k也能解决。
attn_weights = torch.matmul(query_states, key_states.transpose(2, 3)*k) / (math.sqrt(self.head_dim)*k)
