### ISSUE TITLE
chat 模型不再提供chat方法了么？

### ISSUE THREAD

**Issue by deathxlent** [QwenLM/Qwen1.5#7]
AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat'

原来为了方便和通用其他模型，用的chat方法，然而qwen1.5提示没有chat方法了？

**Comment by sccsbc** [comment]
chat_stream也没有了，之前为qwen写的代码都跑不了

**Comment by lhtpluto** [comment]
两眼一抹黑，完全无法使用聊天了

**Comment by XavierSpycy** [comment]
chat方法公布之前或许可以试试这个：

```python
import copy

from transformers import AutoTokenizer, AutoModelForCausalLM

DEVICE = "cuda"

def model_chat(model_name_or_path, prompt, history=None):
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, 
                                                 # Uncomment the line below if you trust the remote code
                                                 #trust_remote_code=True, 
                                                 device_map="auto",
                                                 )
    tokenizer = AutoTokenizer.from_pretrained(
        model_name_or_path, 
        # Uncomment the line below if you trust the remote code
        #trust_remote_code=True,
        )
    
    # Assume other models have chat method
    if "Qwen1.5" not in model_name_or_path:
        return model.chat(tokenizer, prompt, history=history)
    else:
        if history is None:
            history = []
        else:
            history = copy.deepcopy(history)
                
        messages = history_to_messages(history)
        messages.append({'role': 'user', 'content': prompt})
        text = model.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        model_inputs = tokenizer([text], return_tensors="pt").to(DEVICE)
        generated_ids = model.generate(model_inputs.input_ids, max_new_tokens=512, pad_token_id=tokenizer.eos_token_id)
        generated_ids = [output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)]
        response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
        history.append((prompt, response))
        return response, history

# Helper function(s)
# You can find it in Qwen1.5 chat demo
def history_to_messages(history):
    messages = [{'role': 'system', 'content': 'You are a helpful assistant.'}]
    for h in history:
        messages.append({'role': 'user', 'content': h[0]})
        messages.append({'role': 'assistant', 'content': h[1]})
    return messages
```

**Comment by Pierre-Wong** [comment]
修改了的webdemo，还是流式输出，不过感觉速度慢了很多：


# Copyright (c) Alibaba Cloud.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

"""A simple web interactive chat demo based on gradio."""
import os
from argparse import ArgumentParser

import gradio as gr
import mdtex2html

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
from transformers import TextIteratorStreamer
from threading import Thread


DEFAULT_CKPT_PATH = '/home/Qwen1.5-72B-Chat'


def _get_args():
    parser = ArgumentParser()
    parser.add_argument("-c", "--checkpoint-path", type=str, default=DEFAULT_CKPT_PATH,
                        help="Checkpoint name or path, default to %(default)r")
    parser.add_argument("--cpu-only", action="store_true", help="Run demo with CPU only")

    parser.add_argument("--share", action="store_true", default=True,
                        help="Create a publicly shareable link for the interface.")
    parser.add_argument("--inbrowser", action="store_true", default=False,
                        help="Automatically launch the interface in a new tab on the default browser.")
    parser.add_argument("--server-port", type=int, default=80,
                        help="Demo server port.")
    parser.add_argument("--server-name", type=str, default="0.0.0.0",
                        help="Demo server name.")

    args = parser.parse_args()
    return args


def _load_model_tokenizer(args):
    tokenizer = AutoTokenizer.from_pretrained(
        args.checkpoint_path, trust_remote_code=True, resume_download=True,
    )

    if args.cpu_only:
        device_map = "cpu"
    else:
        device_map = "auto"

    model = AutoModelForCausalLM.from_pretrained(
        args.checkpoint_path,
        device_map=device_map,
        trust_remote_code=True,
        resume_download=True,
    ).eval()

    config = GenerationConfig.from_pretrained(
        args.checkpoint_path, trust_remote_code=True, resume_download=True,
    )

    return model, tokenizer, config


def postprocess(self, y):
    if y is None:
        return []
    for i, (message, response) in enumerate(y):
        y[i] = (
            None if message is None else mdtex2html.convert(message),
            None if response is None else mdtex2html.convert(response),
        )
    return y


gr.Chatbot.postprocess = postprocess


def _parse_text(text):
    lines = text.split("\n")
    lines = [line for line in lines if line != ""]
    count = 0
    for i, line in enumerate(lines):
        if "```" in line:
            count += 1
            items = line.split("`")
            if count % 2 == 1:
                lines[i] = f'<pre><code class="language-{items[-1]}">'
            else:
                lines[i] = f"<br></code></pre>"
        else:
            if i > 0:
                if count % 2 == 1:
                    line = line.replace("`", r"\`")
                    line = line.replace("<", "&lt;")
                    line = line.replace(">", "&gt;")
                    line = line.replace(" ", "&nbsp;")
                    line = line.replace("*", "&ast;")
                    line = line.replace("_", "&lowbar;")
                    line = line.replace("-", "&#45;")
                    line = line.replace(".", "&#46;")
                    line = line.replace("!", "&#33;")
                    line = line.replace("(", "&#40;")
                    line = line.replace(")", "&#41;")
                    line = line.replace("$", "&#36;")
                lines[i] = "<br>" + line
    text = "".join(lines)
    return text


def _gc():
    import gc
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def _launch_demo(args, model, tokenizer, config):
    def history_to_messages(history):
        messages = [{'role': 'system', 'content': 'You are a helpful assistant.'}]
        for h in history:
            messages.append({'role': 'user', 'content': h[0]})
            messages.append({'role': 'assistant', 'content': h[1]})
        return messages



    def predict(_query, _chatbot, _task_history):
        print(f"User: {_parse_text(_query)}")
        _chatbot.append((_parse_text(_query), ""))
        full_response = ""

        prompt = _query
        messages = history_to_messages(_task_history)
        messages.append({'role': 'user', 'content': prompt})
        
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

        streamer = TextIteratorStreamer(tokenizer,skip_special_tokens=True)

        generation_kwargs = dict(model_inputs, streamer=streamer,max_new_tokens=8192)
        thread = Thread(target=model.generate, kwargs=generation_kwargs)
        thread.start()
        text=""
        flag=True
        for response in streamer: #model.chat_stream(tokenizer, _query, history=_task_history, generation_config=config):
            if flag:
                flag=False
                continue
            text+=response
            #print(text)
            #input()
            #text=''.join([outputs[len(model_inputs):] for inputs,outputs in zip(model_inputs,text)])
            _chatbot[-1] = (_parse_text(_query), _parse_text(text))

            yield _chatbot
            full_response = _parse_text(text)

        print(f"History: {_task_history}")
        _task_history.append((_query, full_response))
        print(f"Qwen-Chat: {_parse_text(full_response)}")

    def regenerate(_chatbot, _task_history):
        if not _task_history:
            yield _chatbot
            return
        item = _task_history.pop(-1)
        _chatbot.pop(-1)
        yield from predict(item[0], _chatbot, _task_history)

    def reset_user_input():
        return gr.update(value="")

    def reset_state(_chatbot, _task_history):
        _task_history.clear()
        _chatbot.clear()
        _gc()
        return _chatbot

    with gr.Blocks() as demo:
        gr.Markdown("""<p align="center">##<p>""")
        gr.Markdown("""<center><font size=8>Qwen-Chat Bot</center>""")
        gr.Markdown(
            """<center><font size=3>This WebUI is based on Qwen-Chat. 本WebUI基于Qwen-Chat打造，实现聊天机器人功能。</center>""")
        gr.Markdown("""<center><font size=4>
Qwen</center>""")

        chatbot = gr.Chatbot(label='Qwen-Chat', elem_classes="control-height")
        query = gr.Textbox(lines=2, label='Input')
        task_history = gr.State([])

        with gr.Row():
            empty_btn = gr.Button("Clear History (清除历史)")
            submit_btn = gr.Button(" Submit (发送)")
            regen_btn = gr.Button("Regenerate (重试)")

        submit_btn.click(predict, [query, chatbot, task_history], [chatbot], show_progress=True)
        submit_btn.click(reset_user_input, [], [query])
        empty_btn.click(reset_state, [chatbot, task_history], outputs=[chatbot], show_progress=True)
        regen_btn.click(regenerate, [chatbot, task_history], [chatbot], show_progress=True)

        gr.Markdown("""<font size=2>Note: This demo is governed by the original license of Qwen. """)

    demo.queue().launch(
        share=args.share,
        inbrowser=args.inbrowser,
        server_port=args.server_port,
        server_name=args.server_name,
    )


def main():
    args = _get_args()

    model, tokenizer, config = _load_model_tokenizer(args)

    _launch_demo(args, model, tokenizer, config)


if __name__ == '__main__':
    main()

**Comment by YanshekWoo** [comment]
采用最新的transformers==4.37.2自带流式生成
如下是我在gradio函数里针对流式生成的一段代码示例，可以作参考

```
from threading import Thread
from transformers import TextIteratorStreamer, GenerationConfig

generation_config = GenerationConfig.from_pretrained("Qwen/Qwen1.5-14B-Chat")

prompt = "Give me a short introduction to large language model."
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(device)

streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
generation_kwargs = dict(model_inputs, streamer=streamer)
generation_kwargs.update(generation_config.__dict__)

thread = Thread(target=model.generate, kwargs=generation_kwargs)
thread.start()

generated_text = ""
for new_text in streamer:
    generated_text += new_text
    yield generated_text
```

**Comment by FoolMark** [comment]
> 采用最新的transformers==4.37.2自带流式生成 如下是我在gradio函数里针对流式生成的一段代码示例，可以作参考
> 
> ```
> from threading import Thread
> from transformers import TextIteratorStreamer, GenerationConfig
> 
> generation_config = GenerationConfig.from_pretrained("Qwen/Qwen1.5-14B-Chat")
> 
> prompt = "Give me a short introduction to large language model."
> messages = [
>     {"role": "system", "content": "You are a helpful assistant."},
>     {"role": "user", "content": prompt}
> ]
> text = tokenizer.apply_chat_template(
>     messages,
>     tokenize=False,
>     add_generation_prompt=True
> )
> model_inputs = tokenizer([text], return_tensors="pt").to(device)
> 
> streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
> generation_kwargs = dict(model_inputs, streamer=streamer)
> generation_kwargs.update(generation_config.__dict__)
> 
> thread = Thread(target=model.generate, kwargs=generation_kwargs)
> thread.start()
> 
> generated_text = ""
> for new_text in streamer:
>     generated_text += new_text
>     yield generated_text
> ```
感谢分享！好人一生平安

**Comment by JustinLin610** [comment]
check qwen.readthedocs.io

**Comment by xxllp** [comment]
有没有非流式的输出

**Comment by gg22mm** [comment]
怎么解决重复问题呢？

(mygptback) [root@localhost 千问]# python trains_desc.py 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
----查看聊天历史拼接---： <|im_start|>system
你是个乐于助人的助手<|im_end|>
<|im_start|>user
怀孕前需要到医院哪些常规检查<|im_end|>
<|im_start|>assistant

你好，怀孕前需要到医院做以下检查：1、血常规检查：血常规检查是检查孕妇血常规的常用方法，血常规检查包括血红蛋白、红细胞、白细胞、血小板、血沉、血常规、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、
