### ISSUE TITLE
vllm deploy with stop_token_ids

### ISSUE THREAD

**Issue by geasyheart** [QwenLM/Qwen1.5#72]
你好～请教个问题，我发现有个现象，当使用vllm进行部署时在SamplingParams中使用stop_token_ids会出现回答不完全的现象。

例如：
问：你是谁呀？ 
回答： 我是***，我能回答

然后就结束了。

而不使用stop_token_ids则正常：
```py
sampling_params = SamplingParams(temperature=0.7, top_p=0.8,top_k=20,repetition_penalty=1.05, stop_token_ids=[], max_tokens=32768)
```

请问这么处理是否合适以及为什么不需要指定stop_token_ids？？

**Comment by allendred** [comment]
同问

**Comment by LeonG7** [comment]
vllm的问题 https://github.com/vllm-project/vllm/pull/3016

**Comment by currenttime** [comment]
指定maxtoken长度，默认为16，所以会截断

**Comment by currenttime** [comment]
output = llm.generate(text, sampling_params=SamplingParams(max_tokens=512))
