### ISSUE TITLE
vllm的结果跟hf结果差距较大

### ISSUE THREAD

**Issue by Nipi64310** [QwenLM/Qwen1.5#76]
Hi  感谢开源！

请问vllm和hf的结果差异很大，基本上相同的提示词输出都不同，是算子的精度差异导致的嘛，还是哪里遗漏了？

vllm版本0.3.2，模型版本为hf最新commit
测试代码如下：

vllm:
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from vllm import LLM, SamplingParams
tokenizer = AutoTokenizer.from_pretrained('./Qwen1.5-14B-Chat',trust_remote_code=True)
llm = LLM(model="./Qwen1.5-14B-Chat/",trust_remote_code=True,dtype='half',gpu_memory_utilization=0.95,max_model_len=8192)

query = "写个关于小狗的故事"
messages = [
                 {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": query}
            ]

text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
sampling_params = SamplingParams(temperature=0.0, top_p=1,stop=["<|im_end|>", "<|endoftext|>", "<|im_start|>"],
        max_tokens=64)
outputs = llm.generate([text ],sampling_params)

generated_text = outputs[0].outputs[0].text
print(generated_text)

# output
"""
故事标题：小狗奇遇记

在一个安静的小镇上，住着一个名叫小明的男孩，他最喜欢的小动物就是一只名叫“豆豆”的小狗。豆豆是一只活泼可爱的小金毛，毛色金黄，眼睛像两颗黑宝石，总是闪烁着聪明的光芒
"""
```

hf:
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
device = "cuda" # the device to load the model onto

model = AutoModelForCausalLM.from_pretrained(
    "./Qwen1.5-14B-Chat/",
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained("./Qwen1.5-14B-Chat/")

prompt = "写个关于小狗的故事"
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(device)

generated_ids = model.generate(
    model_inputs.input_ids,
    max_new_tokens=64,
    do_sample=False
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
print(response)

# output
"""
故事标题：小勇士巧克

在一个安静的小镇上，住着一个可爱的小男孩杰米和他最好的朋友——一只名叫巧克的小狗。巧克是一只金毛猎犬，毛色如金，眼睛像两颗黑宝石，总是闪烁着聪明和好奇的光芒。
"""
```

**Comment by Nipi64310** [comment]
> 你一个用的sample一个用的是greedy吧

不是啊，明显都是greedy

**Comment by Qubitium** [comment]
@Nipi64310  You are using fp16 for vllm and auto for hf which may be float32.   I highly recommend you set both vllm/hf type to bfloat16. Based on qwen config.json, it was trained with bfloat16 and upcasted to fp32 for model save.

```
llm = LLM(model="./Qwen1.5-14B-Chat/",trust_remote_code=True,dtype='half',gpu_memory_utilization=0.95,max_model_len=8192)
```
Half = float16

You are basibcally running different models (different dtypes) so output diff is normal.

**Comment by Nipi64310** [comment]
> @Nipi64310 You are using fp16 for vllm and auto for hf which may be float32 or bfloat16. I highly recommend you set both vllm/hf type to bfloat16. Based on qwen config.json, it was trained with bfloat16 and upcasted to fp32 for model save.
> 
> ```
> llm = LLM(model="./Qwen1.5-14B-Chat/",trust_remote_code=True,dtype='half',gpu_memory_utilization=0.95,max_model_len=8192)
> ```
> 
> Half = float16
> 
> You are basically running different models (different dtypes) so output diff is normal.

指定类型，结果同上不变，仍然是差异比较大

```python
llm = LLM(model="./Qwen1.5-14B-Chat/",trust_remote_code=True,dtype='float16',gpu_memory_utilization=0.95,max_model_len=8192)


model = AutoModelForCausalLM.from_pretrained(
    "./Qwen1.5-14B-Chat/",
    torch_dtype=torch.float16,
    device_map="auto"
)
```

**Comment by laiqinghan** [comment]
> > @Nipi64310 You are using fp16 for vllm and auto for hf which may be float32 or bfloat16. I highly recommend you set both vllm/hf type to bfloat16. Based on qwen config.json, it was trained with bfloat16 and upcasted to fp32 for model save.
> > ```
> > llm = LLM(model="./Qwen1.5-14B-Chat/",trust_remote_code=True,dtype='half',gpu_memory_utilization=0.95,max_model_len=8192)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Half = float16
> > You are basically running different models (different dtypes) so output diff is normal.
> 
> 指定类型，结果同上不变，仍然是差异比较大
> 
> ```python
> llm = LLM(model="./Qwen1.5-14B-Chat/",trust_remote_code=True,dtype='float16',gpu_memory_utilization=0.95,max_model_len=8192)
> 
> 
> model = AutoModelForCausalLM.from_pretrained(
>     "./Qwen1.5-14B-Chat/",
>     torch_dtype=torch.float16,
>     device_map="auto"
> )
> ```

这是由于vllm实现机制导致的，之前跟踪过qwen1，vllm中的rope实现跟qwen1的hf轻微不一致，pageattention推理的结果跟hf轻微不一致，还有其中涉及xformer的精度和layernorm，残差连接精度轻微不一致。这里面改了之后会对速度产生影响，底层的pageattention是C实现的，难改。

**Comment by laiqinghan** [comment]
而且处理的文本长度越长，这种差异越明显，明显不如hf。

**Comment by Nipi64310** [comment]
> 这是由于vllm实现机制导致的，之前跟踪过qwen1，vllm中的rope实现跟qwen1的hf轻微不一致，pageattention推理的结果跟hf轻微不一致，还有其中涉及xformer的精度和layernorm，残差连接精度轻微不一致。这里面改了之后会对速度产生影响，底层的pageattention是C实现的，难改。

不同算子算出来有差异很正常，但是qwen1的不一致情况似乎没有qwen2这么严重，目前来看，几乎是任意输入都会不一致

**Comment by JustinLin610** [comment]
there are diffs that we cannot avoid but in our evaluation both can reach similar perf.

**Comment by boluoyu** [comment]
vllm 出来的结果很多都是有问题，很差，hf结果是正常的，这个框架貌似还处于不稳定状态

**Comment by zhenhua32** [comment]
关注, qwen2 7b 的推理结果在 hf 和 vllm 之间有挺大的差别的

**Comment by Switchsyj** [comment]
subscribe. It seems the longer output it is, the more difference of a inference result between vllm and hf it could be.

**Comment by Damelard** [comment]
关注

**Comment by Liufeiran123** [comment]
解决了吗

**Comment by foreverhell** [comment]
same problem.

**Comment by choucaicai** [comment]
same problem

**Comment by chansonzhang** [comment]
> 不同算子算出来有差异很正常，但是qwen1的不一致情况似乎没有qwen2这么严重，目前来看，几乎是任意输入都会不一致

+1，我们在 Qwen-1_8B-Chatm 没有发现这种不一致，但是在 Qwen2.5-0.5B-Instruct 就发现明显的不一致 [issues#1018](https://github.com/QwenLM/Qwen2.5/issues/1018 )

**Comment by choucaicai** [comment]
It's possible to set vllm's top_k to 50. By default, vllm's top_k is -1, while in transformers, the default top_k is 50. After I set it this way, I found that the inference results from vllm had a smaller difference compared to transformers

**Comment by xlg-go** [comment]
我也遇到同样的问题

**Comment by Zbaoli** [comment]
> It's possible to set vllm's top_k to 50. By default, vllm's top_k is -1, while in transformers, the default top_k is 50. After I set it this way, I found that the inference results from vllm had a smaller difference compared to transformers

确实，top_p 跟 top_k 改成 hf 一样的默认值之后性能好了很多，但还是会差一个点左右不知道为啥；

**Comment by xlg-go** [comment]
> 我也遇到同样的问题

我卸载了flash attention，解决了

**Comment by CharlesRiggins** [comment]
This is a Qwen2-7B problem. Highly sensitive to even subtle noise (caused by the vLLM's kernel diff with hugging face). Read this blog for further information: https://medium.com/@crclq2018/a-huge-flaw-inside-qwen2-5-14940178833f

**Comment by hellozjj** [comment]
same problem
