### ISSUE TITLE
请教一下，现在这个model.generate的方式怎么设置stop_words为“Observation:”呢？

### ISSUE THREAD

**Issue by fataldemon** [QwenLM/Qwen1.5#82]
请教一下，现在这个model.generate的方式怎么设置stop_words为“Observation:”呢？我试了一下好像没有stop_words_ids这个参数了。

**Comment by JustinLin610** [comment]
Next week I'll provide an instruction. You can take a look at `model.chat()` in our previous Qwen code and see if you can do it yourself.

**Comment by JianxinMa** [comment]
see this: https://github.com/QwenLM/Qwen1.5/issues/172#issuecomment-1999978612
