### ISSUE TITLE
fine-tuning with SFTTrainer

### ISSUE THREAD

**Issue by shao-shuai** [QwenLM/Qwen1.5#84]
Hi, was trying to fine-tuning qwen-1.5-7b with SFTTrainer from trl.

I understand the recommended way of formatting data is here https://github.com/QwenLM/Qwen1.5/blob/main/docs/source/training/SFT/example.rst

I followed the instruction and got an error when I tried to train.

```python
trainer = SFTTrainer(
        model=model,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        peft_config=peft_config,
        dataset_text_field="text",
        max_seq_length=512,
        tokenizer=tokenizer,
        args=training_arguments,
)

trainer.train()
```

my dataset format is like this
DatasetDict({
    train: Dataset({
        features: ['type', 'messages', 'source'],
        num_rows: 576
    })
})

since there's no text filed, how am I supposed to set `dataset_text_field`?

**Comment by JustinLin610** [comment]
Why not directly use the train script provided? Or you can use things like llama factory or axolotl.

**Comment by shao-shuai** [comment]
> Why not directly use the train script provided? Or you can use things like llama factory or axolotl.

thanks, will give a try
