### ISSUE TITLE
vllm中的例子跑不通，出现错误{"object":"error","message":"The model `Qwen/Qwen1.5-7B-Chat` does not exist.","type":"NotFoundError","param":null,"code":404}

### ISSUE THREAD

**Issue by LHB-kk** [QwenLM/Qwen1.5#87]

**Comment by zhangjh** [comment]
文档写的稀碎，都不带验证的。。实测，model参数可以传递”qwen“，通过启动命令日志看出来的。。
![image](https://github.com/QwenLM/Qwen1.5/assets/3371714/791e0c26-47f0-43e1-94fc-6755440733ab)

**Comment by JustinLin610** [comment]
https://docs.vllm.ai/en/latest/getting_started/quickstart.html

Check the official doc for comparison. `--served-model-name` can help with changing the model name issue. I can add it to the doc as it facilitates using it.
