### ISSUE TITLE
问一下  Qwen1.5-72B-Chat 至少需要多少显存才可以跑呀，

### ISSUE THREAD

**Issue by 1920853199** [QwenLM/Qwen1.5#88]
我 8*A10 还是没办法跑起来

**Comment by Gy1900** [comment]
看了下可能模型占用就得33G，A10不行

**Comment by White-Friday** [comment]
使用A800  80g跑vllm，两张卡，显存占用设置95%才能跑起来

**Comment by EchoShoot** [comment]
@White-Friday  请问 --dtype 设置什么？

**Comment by njupopsicle** [comment]
> @White-Friday 请问 --dtype 设置什么？

默认，我的命令式CUDA_VISIBLE_DEVICES=0,1 python -m vllm.entrypoints.openai.api_server --model ../models/Qwen1.5-72B-Chat --tensor-parallel-size 2 --gpu-memory-utilization 0.95 --max-model-len 2048

**Comment by njupopsicle** [comment]
> @White-Friday 请问 --dtype 设置什么？

默认，我的命令是CUDA_VISIBLE_DEVICES=0,1 python -m vllm.entrypoints.openai.api_server --model ../models/Qwen1.5-72B-Chat --tensor-parallel-size 2 --gpu-memory-utilization 0.95 --max-model-len 2048

**Comment by EchoShoot** [comment]
@njupopsicle 感谢

**Comment by JustinLin610** [comment]
https://qwen.readthedocs.io/en/latest/benchmark/hf_infer.html
